require "./spec_helper"

private class EditorVerticalSliceSpecState
  property active_layer : String
  property zoom : Float64
  property pan_x : Float64
  property pan_y : Float64
  property dragging : Bool
  property last_pointer : Qt6::PointF
  property accent : Qt6::Color

  def initialize
    @active_layer = "Terrain"
    @zoom = 1.0
    @pan_x = 24.0
    @pan_y = 28.0
    @dragging = false
    @last_pointer = Qt6::PointF.new(0.0, 0.0)
    @accent = Qt6::Color.new(62, 130, 109)
  end
end

private class EditableLayerListModel < Qt6::AbstractListModel
  getter layers

  def initialize(layers : Array(String), parent : Qt6::QObject? = nil)
    @layers = layers
    super(parent)
  end

  def append_layer(name : String) : String
    position = @layers.size
    begin_insert_rows(position, position)
    @layers << name
    end_insert_rows
    name
  end

  def remove_layer(row : Int) : String
    begin_remove_rows(row, row)
    removed = @layers.delete_at(row)
    end_remove_rows
    removed
  end

  def replace_layers(layers : Array(String)) : Array(String)
    begin_reset_model
    @layers = layers
    end_reset_model
    layers
  end

  protected def model_row_count : Int32
    @layers.size.to_i32
  end

  protected def model_data(index : Qt6::ModelIndex, role : Int32) : Qt6::ModelData
    return nil unless index.valid?

    case role
    when Qt6::ItemDataRole::Display.value, Qt6::ItemDataRole::Edit.value
      @layers[index.row]?
    when Qt6::ItemDataRole::User.value
      index.row
    else
      nil
    end
  end

  protected def model_set_data(index : Qt6::ModelIndex, value : Qt6::ModelData, role : Int32) : Bool
    return false unless index.valid? && role == Qt6::ItemDataRole::Edit.value

    @layers[index.row] = value.to_s
    data_changed(index)
    true
  end

  protected def model_header_data(section : Int32, orientation : Qt6::Orientation, role : Int32) : Qt6::ModelData
    return nil unless section == 0 && orientation == Qt6::Orientation::Horizontal && role == Qt6::ItemDataRole::Display.value

    "Layer"
  end

  protected def model_flags(index : Qt6::ModelIndex) : Qt6::ItemFlag
    return Qt6::ItemFlag::None unless index.valid?

    Qt6::ItemFlag::Enabled | Qt6::ItemFlag::Selectable | Qt6::ItemFlag::Editable
  end
end

describe Qt6 do
  it "renders into images and pixmaps with paths and transforms" do
    app
    image = Qt6::QImage.new(32, 32)
    image.fill(Qt6::Color.new(255, 255, 255))
    image.set_pixel_color(0, 0, Qt6::Color.new(1, 2, 3, 255))

    pen = Qt6::QPen.new(Qt6::Color.new(255, 0, 0), 3)
    brush = Qt6::QBrush.new(Qt6::Color.new(255, 0, 0))
    font = Qt6::QFont.new(point_size: 14, bold: true, italic: true)
    metrics = font.metrics
    metrics_f = font.metrics_f

    transform = Qt6::QTransform.new
    transform.translate(4, 5)

    path = Qt6::QPainterPath.new
    path.add_rect(Qt6::RectF.new(0.0, 0.0, 8.0, 8.0))
    moved_path = path.transformed(transform)

    Qt6::QPainter.paint(image) do |painter|
      painter.active?.should be_true
      painter.antialiasing = false
      painter.pen = pen
      painter.brush = brush
      painter.font = font
      painter.draw_path(moved_path)
      painter.fill_rect(Qt6::RectF.new(20.0, 20.0, 4.0, 4.0), Qt6::Color.new(0, 0, 255))
      painter.draw_line(Qt6::PointF.new(0.0, 31.0), Qt6::PointF.new(31.0, 31.0))
      painter.draw_text(Qt6::PointF.new(1.0, 16.0), "qt6")
    end

    pixmap = Qt6::QPixmap.from_image(image)
    pixmap_canvas = Qt6::QPixmap.new(40, 40)
    pixmap_canvas.fill(Qt6::Color.new(0, 0, 0, 0))
    svg_path = File.join(Dir.tempdir, "crystal-qt6-render-scene-#{Process.pid}.svg")
    svg = Qt6::QSvgGenerator.new(svg_path, 40, 40, title: "Render Scene", description: "Generated by crystal-qt6 specs")
    svg.resolution = 96
    pdf_path = File.join(Dir.tempdir, "crystal-qt6-render-scene-#{Process.pid}.pdf")
    pdf = Qt6::QPdfWriter.new(pdf_path, title: "Render Scene PDF", creator: "crystal-qt6 specs")
    pdf.page_size_points = Qt6::Size.new(120, 120)
    pdf.resolution = 144

    Qt6::QPainter.paint(pixmap_canvas) do |painter|
      painter.draw_image(Qt6::PointF.new(2.0, 2.0), image)
      painter.draw_pixmap(Qt6::PointF.new(0.0, 0.0), pixmap)
    end

    Qt6::QPainter.paint(svg) do |painter|
      painter.antialiasing = false
      painter.pen = pen
      painter.brush = brush
      painter.font = font
      painter.draw_path(moved_path)
      painter.fill_rect(Qt6::RectF.new(20.0, 20.0, 4.0, 4.0), Qt6::Color.new(0, 0, 255))
      painter.draw_text(Qt6::PointF.new(1.0, 16.0), "qt6-svg")
    end

    Qt6::QPainter.paint(pdf) do |painter|
      painter.antialiasing = false
      painter.pen = pen
      painter.brush = brush
      painter.font = font
      painter.draw_path(moved_path)
      painter.fill_rect(Qt6::RectF.new(20.0, 20.0, 4.0, 4.0), Qt6::Color.new(0, 0, 255))
      painter.draw_text(Qt6::PointF.new(1.0, 16.0), "qt6-pdf")
      pdf.new_page.should be_true
      painter.reset_transform
      painter.draw_line(Qt6::PointF.new(0.0, 0.0), Qt6::PointF.new(30.0, 30.0))
    end

    svg_file_name = svg.file_name
    svg_size = svg.size
    svg_view_box = svg.view_box
    svg_title = svg.title
    svg_description = svg.description
    svg_resolution = svg.resolution
    pdf_file_name = pdf.file_name
    pdf_title = pdf.title
    pdf_creator = pdf.creator
    pdf_resolution = pdf.resolution

    svg_markup = begin
      svg.release
      File.read(svg_path)
    end

    svg_renderer = Qt6::QSvgRenderer.new(svg_path)
    svg_renderer.valid?.should be_true

    svg_canvas = Qt6::QImage.new(40, 40)
    svg_canvas.fill(Qt6::Color.new(255, 255, 255))
    Qt6::QPainter.paint(svg_canvas) do |painter|
      svg_renderer.render(painter, Qt6::RectF.new(0.0, 0.0, 40.0, 40.0))
    end

    svg_default_size = svg_renderer.default_size
    svg_render_view_box = svg_renderer.view_box

    pdf_header = begin
      pdf.release
      File.open(pdf_path) do |file|
        bytes = Bytes.new(5)
        file.read_fully(bytes)
        String.new(bytes)
      end
    end

    pixmap_image = pixmap_canvas.to_image
    image_path = File.join(Dir.tempdir, "crystal-qt6-render-image-#{Process.pid}.png")
    pixmap_path = File.join(Dir.tempdir, "crystal-qt6-render-pixmap-#{Process.pid}.png")
    text_bounds = metrics.bounding_rect("qt6")
    text_bounds_f = metrics_f.bounding_rect("qt6")

    pen.width.should eq(3.0)
    pen.color.should eq(Qt6::Color.new(255, 0, 0, 255))
    brush.color.should eq(Qt6::Color.new(255, 0, 0, 255))
    font.point_size.should eq(14)
    font.bold?.should be_true
    font.italic?.should be_true
    metrics.height.should be > 0
    metrics.ascent.should be > 0
    metrics.descent.should be >= 0
    metrics.horizontal_advance("qt6").should be > 0
    text_bounds.width.should be > 0.0
    text_bounds.height.should be > 0.0
    metrics_f.height.should be > 0.0
    metrics_f.ascent.should be > 0.0
    metrics_f.descent.should be >= 0.0
    metrics_f.horizontal_advance("qt6").should be > 0.0
    text_bounds_f.width.should be > 0.0
    text_bounds_f.height.should be > 0.0
    transform.map(Qt6::PointF.new(1.0, 1.0)).should eq(Qt6::PointF.new(5.0, 6.0))
    transform.map(Qt6::RectF.new(0.0, 0.0, 8.0, 8.0)).should eq(Qt6::RectF.new(4.0, 5.0, 8.0, 8.0))
    moved_path.bounding_rect.should eq(Qt6::RectF.new(4.0, 5.0, 8.0, 8.0))
    image.pixel_color(0, 0).should eq(Qt6::Color.new(1, 2, 3, 255))
    image.pixel_color(6, 7).should eq(Qt6::Color.new(255, 0, 0, 255))
    image.pixel_color(21, 21).should eq(Qt6::Color.new(0, 0, 255, 255))
    pixmap.width.should eq(32)
    pixmap.height.should eq(32)
    pixmap.null?.should be_false
    svg_file_name.should eq(svg_path)
    svg_size.should eq(Qt6::Size.new(40, 40))
    svg_view_box.should eq(Qt6::RectF.new(0.0, 0.0, 40.0, 40.0))
    svg_default_size.width.should be > 0
    svg_default_size.height.should be > 0
    svg_render_view_box.should eq(Qt6::RectF.new(0.0, 0.0, 40.0, 40.0))
    svg_title.should eq("Render Scene")
    svg_description.should eq("Generated by crystal-qt6 specs")
    svg_resolution.should eq(96)
    pdf_file_name.should eq(pdf_path)
    pdf_title.should eq("Render Scene PDF")
    pdf_creator.should eq("crystal-qt6 specs")
    pdf_resolution.should eq(144)
    pixmap_image.pixel_color(1, 1).should eq(Qt6::Color.new(255, 255, 255, 255))
    pixmap_image.pixel_color(6, 7).should eq(Qt6::Color.new(255, 0, 0, 255))
    image.save(image_path).should be_true
    pixmap.save(pixmap_path).should be_true
    File.exists?(image_path).should be_true
    File.exists?(pixmap_path).should be_true
    File.exists?(svg_path).should be_true
    File.exists?(pdf_path).should be_true
    svg_markup.includes?("<svg").should be_true
    svg_markup.includes?("<title>Render Scene</title>").should be_true
    svg_markup.includes?("Generated by crystal-qt6 specs").should be_true
    pdf_header.should eq("%PDF-")
    svg_canvas.pixel_color(6, 7).should eq(Qt6::Color.new(255, 0, 0, 255))
    svg_canvas.pixel_color(21, 21).should eq(Qt6::Color.new(0, 0, 255, 255))
  end

  it "loads standalone SVG files and exposes element bounds" do
    app
    svg_path = File.join(Dir.tempdir, "crystal-qt6-standalone-#{Process.pid}.svg")
    File.write(svg_path, <<-SVG)
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="12" viewBox="0 0 20 12">
        <rect id="box" x="2" y="1" width="6" height="4" fill="#ff0000"/>
        <rect id="accent" x="12" y="2" width="4" height="6" fill="#0000ff"/>
      </svg>
    SVG

    renderer = Qt6::QSvgRenderer.new(svg_path)
    renderer.load(svg_path).should be_true
    canvas = Qt6::QImage.new(20, 12)
    canvas.fill(Qt6::Color.new(255, 255, 255))
    element_canvas = Qt6::QImage.new(20, 12)
    element_canvas.fill(Qt6::Color.new(255, 255, 255))
    bounded_element_canvas = Qt6::QImage.new(10, 10)
    bounded_element_canvas.fill(Qt6::Color.new(255, 255, 255))

    Qt6::QPainter.paint(canvas) do |painter|
      renderer.render(painter)
    end

    Qt6::QPainter.paint(element_canvas) do |painter|
      renderer.render(painter, "box")
    end

    Qt6::QPainter.paint(bounded_element_canvas) do |painter|
      renderer.render(painter, "accent", Qt6::RectF.new(0.0, 0.0, 10.0, 10.0))
    end

    renderer.valid?.should be_true
    renderer.default_size.should eq(Qt6::Size.new(20, 12))
    renderer.view_box.should eq(Qt6::RectF.new(0.0, 0.0, 20.0, 12.0))
    renderer.element_exists?("box").should be_true
    renderer.element_exists?("accent").should be_true
    renderer.element_exists?("missing").should be_false
    renderer.bounds_on_element("box").should eq(Qt6::RectF.new(2.0, 1.0, 6.0, 4.0))
    renderer.bounds_on_element("accent").should eq(Qt6::RectF.new(12.0, 2.0, 4.0, 6.0))
    canvas.pixel_color(3, 2).should eq(Qt6::Color.new(255, 0, 0, 255))
    canvas.pixel_color(13, 3).should eq(Qt6::Color.new(0, 0, 255, 255))
    element_canvas.pixel_color(3, 2).should eq(Qt6::Color.new(255, 0, 0, 255))
    bounded_element_canvas.pixel_color(1, 1).should eq(Qt6::Color.new(0, 0, 255, 255))
  end

  it "supports clipboard access and file-backed image loading helpers" do
    application = app
    source_path = File.join(Dir.tempdir, "crystal-qt6-image-source-#{Process.pid}.png")
    source = Qt6::QImage.new(12, 10)
    source.fill(Qt6::Color.new(255, 255, 255))
    source.set_pixel_color(4, 3, Qt6::Color.new(12, 34, 56, 255))
    source.save(source_path).should be_true

    loaded_image = Qt6::QImage.from_file(source_path)
    loaded_image.null?.should be_false
    loaded_image.size.should eq(Qt6::Size.new(12, 10))
    loaded_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    reusable_image = Qt6::QImage.new(1, 1)
    reusable_image.load(source_path).should be_true
    reusable_image.size.should eq(Qt6::Size.new(12, 10))
    reusable_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    loaded_pixmap = Qt6::QPixmap.from_file(source_path)
    loaded_pixmap.null?.should be_false
    loaded_pixmap.size.should eq(Qt6::Size.new(12, 10))
    loaded_pixmap.to_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    reusable_pixmap = Qt6::QPixmap.new(1, 1)
    reusable_pixmap.load(source_path).should be_true
    reusable_pixmap.size.should eq(Qt6::Size.new(12, 10))
    reusable_pixmap.to_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    reader = Qt6::QImageReader.new(source_path)
    reader.file_name.should eq(source_path)
    reader.can_read?.should be_true
    reader.size.should eq(Qt6::Size.new(12, 10))
    reader.format.should eq("png")
    reader.auto_transform?.should be_false
    reader.auto_transform = true
    reader.auto_transform?.should be_true
    reader.format = "png"
    reader.format.should eq("png")

    reader_image = reader.read
    reader_image.null?.should be_false
    reader_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    second_reader = Qt6::QImageReader.new(source_path)
    reused_reader_image = Qt6::QImage.new(1, 1)
    second_reader.read(reused_reader_image).should be_true
    reused_reader_image.size.should eq(Qt6::Size.new(12, 10))
    reused_reader_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    clipboard = application.clipboard
    clipboard.clear
    clipboard.text = "clipboard sample"
    application.process_events
    clipboard.text.should eq("clipboard sample")

    clipboard.image = loaded_image
    application.process_events
    clipboard_image = clipboard.image
    clipboard_image.null?.should be_false
    clipboard_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    clipboard.pixmap = loaded_pixmap
    application.process_events
    clipboard_pixmap = clipboard.pixmap
    clipboard_pixmap.null?.should be_false
    clipboard_pixmap.to_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    mime_data = Qt6::MimeData.new
    mime_data.text = "mime sample"
    mime_data.set_data("application/x-crystal-qt6-layer", Bytes[1_u8, 7_u8, 9_u8])
    clipboard.mime_data = mime_data
    application.process_events

    clipboard_mime = clipboard.mime_data
    clipboard_mime.should_not be_nil
    clipboard_mime = clipboard_mime.not_nil!
    clipboard_mime.has_text?.should be_true
    clipboard_mime.text.should eq("mime sample")
    clipboard_mime.has_format?("application/x-crystal-qt6-layer").should be_true
    clipboard_mime.data("application/x-crystal-qt6-layer").should eq(Bytes[1_u8, 7_u8, 9_u8])
    clipboard.clear
  end

  it "loads SVG content from memory" do
    app
    svg_markup = <<-SVG
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="10" viewBox="0 0 18 10">
        <rect id="memory-box" x="4" y="2" width="6" height="4" fill="#00aa00"/>
      </svg>
    SVG

    renderer = Qt6::QSvgRenderer.from_data(svg_markup)
    renderer.valid?.should be_true
    renderer.default_size.should eq(Qt6::Size.new(18, 10))
    renderer.element_exists?("memory-box").should be_true

    image = Qt6::QImage.new(18, 10)
    image.fill(Qt6::Color.new(255, 255, 255))

    Qt6::QPainter.paint(image) do |painter|
      renderer.render(painter)
    end

    image.pixel_color(5, 3).should eq(Qt6::Color.new(0, 170, 0, 255))

    widget = Qt6::QSvgWidget.from_data(svg_markup)
    widget.size_hint.should eq(Qt6::Size.new(18, 10))
    widget.resize(18, 10)
    widget.show
    app.process_events

    preview = widget.grab
    preview.null?.should be_false
    preview.width.should be >= 18
    preview.height.should be >= 10
    widget.release
  end

  it "displays SVG content in QSvgWidget" do
    application = app
    svg_path = File.join(Dir.tempdir, "crystal-qt6-widget-#{Process.pid}.svg")
    File.write(svg_path, <<-SVG)
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="16" viewBox="0 0 24 16">
        <rect x="3" y="2" width="8" height="6" fill="#ff0000"/>
      </svg>
    SVG

    widget = Qt6::QSvgWidget.new(svg_path)
    renderer = widget.renderer

    renderer.valid?.should be_true
    renderer.default_size.should eq(Qt6::Size.new(24, 16))
    renderer.element_exists?("missing").should be_false
    widget.size_hint.should eq(Qt6::Size.new(24, 16))
    widget.resize(24, 16)
    widget.visible?.should be_false
    widget.show
    application.process_events
    widget.update
    application.process_events

    preview = widget.grab

    widget.visible?.should be_true
    widget.size.should eq(Qt6::Size.new(24, 16))
    preview.null?.should be_false
    preview.width.should be >= 24
    preview.height.should be >= 16

    render_probe = Qt6::QImage.new(24, 16)
    render_probe.fill(Qt6::Color.new(255, 255, 255))
    Qt6::QPainter.paint(render_probe) do |painter|
      renderer.render(painter)
    end
    render_probe.pixel_color(4, 3).should eq(Qt6::Color.new(255, 0, 0, 255))

    widget.release
  end

  it "provides convenience helpers for common dialogs" do
    app
    window = Qt6::MainWindow.new

    message_result = Qt6::MessageBox.information(window, title: "About", text: "Helper test") do |dialog|
      timer = Qt6::QTimer.new(dialog)
      timer.single_shot = true
      timer.on_timeout { dialog.accept }
      timer.start(0)
    end

    selected_color = Qt6::ColorDialog.get_color(window, current_color: Qt6::Color.new(8, 16, 32, 64), title: "Accent", show_alpha_channel: true) do |dialog|
      dialog.native_dialog = false
      dialog.current_color = Qt6::Color.new(32, 64, 96, 128)
      timer = Qt6::QTimer.new(dialog)
      timer.single_shot = true
      timer.on_timeout { dialog.accept }
      timer.start(0)
    end

    text_value = Qt6::InputDialog.get_text(window, title: "Rename", label: "Layer", value: "Terrain") do |dialog|
      dialog.text_value = "Roads"
      timer = Qt6::QTimer.new(dialog)
      timer.single_shot = true
      timer.on_timeout { dialog.accept }
      timer.start(0)
    end

    int_value = Qt6::InputDialog.get_int(window, title: "Count", label: "Columns", value: 3, minimum: 1, maximum: 12) do |dialog|
      dialog.int_value = 7
      timer = Qt6::QTimer.new(dialog)
      timer.single_shot = true
      timer.on_timeout { dialog.accept }
      timer.start(0)
    end

    double_value = Qt6::InputDialog.get_double(window, title: "Scale", label: "Zoom", value: 1.0, minimum: 0.5, maximum: 4.0) do |dialog|
      dialog.double_value = 1.25
      timer = Qt6::QTimer.new(dialog)
      timer.single_shot = true
      timer.on_timeout { dialog.accept }
      timer.start(0)
    end

    message_result.should eq(Qt6::MessageBoxButton::Ok)
    selected_color.should eq(Qt6::Color.new(32, 64, 96, 128))
    text_value.should eq("Roads")
    int_value.should eq(7)
    double_value.should eq(1.25)
    window.release
  end

  it "configures color and input dialogs" do
    app
    window = Qt6::MainWindow.new
    color_dialog = Qt6::ColorDialog.new(window)
    input_dialog = Qt6::InputDialog.new(window)

    color_dialog.window_title = "Pick Accent Color"
    color_dialog.native_dialog = false
    color_dialog.show_alpha_channel = true
    color_dialog.current_color = Qt6::Color.new(32, 96, 192, 180)

    input_dialog.window_title = "Layer Details"
    input_dialog.input_mode = Qt6::InputDialogInputMode::Text
    input_dialog.label_text = "Layer name"
    input_dialog.text_value = "Terrain"
    input_dialog.input_mode = Qt6::InputDialogInputMode::Int
    input_dialog.int_range = 1..12
    input_dialog.int_value = 4
    input_dialog.input_mode = Qt6::InputDialogInputMode::Double
    input_dialog.double_range = 0.5..4.0
    input_dialog.double_value = 1.5

    color_dialog.window_title.should eq("Pick Accent Color")
    color_dialog.native_dialog?.should be_false
    color_dialog.current_color.should eq(Qt6::Color.new(32, 96, 192, 180))
    color_dialog.show_alpha_channel?.should be_true

    input_dialog.window_title.should eq("Layer Details")
    input_dialog.label_text.should eq("Layer name")
    input_dialog.text_value.should eq("Terrain")
    input_dialog.int_minimum.should eq(1)
    input_dialog.int_maximum.should eq(12)
    input_dialog.int_value.should eq(4)
    input_dialog.double_minimum.should eq(0.5)
    input_dialog.double_maximum.should eq(4.0)
    input_dialog.double_value.should eq(1.5)
    window.release
  end

  it "configures standard message and file dialogs" do
    app
    window = Qt6::MainWindow.new
    message_box = Qt6::MessageBox.new(window)
    file_dialog = Qt6::FileDialog.new(window, "/tmp", "Maps (*.map *.json)")

    message_box.window_title = "Unsaved Changes"
    message_box.icon = Qt6::MessageBoxIcon::Warning
    message_box.text = "This map has unsaved changes."
    message_box.informative_text = "Save before closing?"
    message_box.standard_buttons = Qt6::MessageBoxButton::Save | Qt6::MessageBoxButton::Discard | Qt6::MessageBoxButton::Cancel
    message_box.accept

    file_dialog.accept_mode = Qt6::FileDialogAcceptMode::Save
    file_dialog.file_mode = Qt6::FileDialogFileMode::AnyFile
    file_dialog.directory = "/tmp"
    file_dialog.name_filter = "Maps (*.map *.json)"
    file_dialog.select_file("/tmp/example.map")

    message_box.window_title.should eq("Unsaved Changes")
    message_box.icon.should eq(Qt6::MessageBoxIcon::Warning)
    message_box.text.should eq("This map has unsaved changes.")
    message_box.informative_text.should eq("Save before closing?")
    message_box.standard_buttons.includes?(Qt6::MessageBoxButton::Save).should be_true
    message_box.standard_buttons.includes?(Qt6::MessageBoxButton::Discard).should be_true
    message_box.standard_buttons.includes?(Qt6::MessageBoxButton::Cancel).should be_true
    message_box.result.should eq(Qt6::DialogCode::Accepted)

    file_dialog.accept_mode.should eq(Qt6::FileDialogAcceptMode::Save)
    file_dialog.file_mode.should eq(Qt6::FileDialogFileMode::AnyFile)
    file_dialog.directory.should eq("/tmp")
    file_dialog.name_filter.should eq("Maps (*.map *.json)")
    window.release
  end

  it "supports action shortcuts and exclusive action groups" do
    app
    window = Qt6::MainWindow.new
    menu = window.menu_bar.add_menu("View")
    group = Qt6::ActionGroup.new(window)
    map_action = Qt6::Action.new("Map", window)
    units_action = Qt6::Action.new("Units", window)

    map_action.shortcut = Qt6::KeySequence.new("Ctrl+1")
    units_action.shortcut = "Ctrl+2"
    map_action.checkable = true
    units_action.checkable = true
    group.exclusive = true
    group << map_action
    group << units_action
    menu << map_action
    menu << units_action

    map_action.checked = true
    units_action.checked = true

    map_action.shortcut.to_s.should eq("Ctrl+1")
    units_action.shortcut.to_s.should eq("Ctrl+2")
    map_action.checkable?.should be_true
    units_action.checkable?.should be_true
    group.exclusive?.should be_true
    map_action.checked?.should be_false
    units_action.checked?.should be_true
    window.release
  end

  it "builds a reduced shell with menus, toolbars, docks, dialogs, and controls" do
    application = app
    main = Qt6::MainWindow.new
    triggered = 0
    accepted = 0
    rejected = 0
    toggled = [] of Bool
    indices = [] of Int32

    main.window_title = "Editor Shell"
    main.resize(960, 640)
    main.central_widget = Qt6::Label.new("Canvas")

    file_menu = main.menu_bar.add_menu("File")
    recent_menu = file_menu.add_menu("Recent")
    open_action = Qt6::Action.new("Open", main)
    open_action.on_triggered do
      triggered += 1
    end
    file_menu << open_action
    file_menu.add_separator

    tool_bar = Qt6::ToolBar.new("Primary", main)
    main.add_tool_bar(tool_bar)
    tool_bar << open_action

    dock = Qt6::DockWidget.new("Inspector", main)
    inspector = Qt6::Widget.new
    line_edit = Qt6::LineEdit.new("Hexes")
    check_box = Qt6::CheckBox.new("Snap")
    combo_box = Qt6::ComboBox.new
    check_box.on_toggled do |value|
      toggled << value
    end
    combo_box.on_current_index_changed do |index|
      indices << index
    end
    combo_box << "Units" << "Terrain"

    inspector.vbox do |column|
      column << line_edit
      column << check_box
      column << combo_box
    end

    dock.widget = inspector
    main.add_dock_widget(dock, Qt6::DockArea::Left)
    main.status_bar.show_message("Ready")

    dialog = Qt6::Dialog.new(main)
    dialog.on_accepted do
      accepted += 1
    end
    dialog.on_rejected do
      rejected += 1
    end

    dialog.accept
    check_box.checked = true
    combo_box.current_index = 1
    open_action.trigger
    application.process_events

    recent_menu.title.should eq("Recent")
    main.status_bar.current_message.should eq("Ready")
    line_edit.text = "Terrain"
    line_edit.text.should eq("Terrain")
    check_box.checked?.should be_true
    combo_box.count.should eq(2)
    combo_box.current_text.should eq("Terrain")
    toggled.last.should be_true
    indices.last.should eq(1)
    triggered.should eq(1)
    dialog.result.should eq(Qt6::DialogCode::Accepted)
    accepted.should eq(1)
    rejected.should eq(0)
    main.release
  end

  it "supports editor controls and container widgets" do
    application = app
    window = Qt6::MainWindow.new
    radio_states = [] of Bool
    slider_values = [] of Int32
    spin_values = [] of Int32
    double_values = [] of Float64
    group_states = [] of Bool
    tab_indices = [] of Int32

    splitter = Qt6::Splitter.new(Qt6::Orientation::Horizontal)
    scroll_area = Qt6::ScrollArea.new
    tab_widget = Qt6::TabWidget.new
    inspector = Qt6::Widget.new
    options_group = Qt6::GroupBox.new("Options")
    auto_mode = Qt6::RadioButton.new("Auto")
    manual_mode = Qt6::RadioButton.new("Manual")
    slider = Qt6::Slider.new
    spin_box = Qt6::SpinBox.new
    double_spin_box = Qt6::DoubleSpinBox.new

    manual_mode.on_toggled do |value|
      radio_states << value
    end
    slider.on_value_changed do |value|
      slider_values << value
    end
    spin_box.on_value_changed do |value|
      spin_values << value
    end
    double_spin_box.on_value_changed do |value|
      double_values << value
    end
    options_group.on_toggled do |value|
      group_states << value
    end
    tab_widget.on_current_index_changed do |value|
      tab_indices << value
    end

    options_group.checkable = true
    options_group.vbox do |column|
      column << auto_mode
      column << manual_mode
      column << slider
      column << spin_box
      column << double_spin_box
    end

    inspector.vbox do |column|
      column << options_group
    end

    scroll_area.widget_resizable = true
    scroll_area.widget = inspector
    tab_widget.add_tab(Qt6::Label.new("Layers"), "Layers")
    tab_widget.add_tab(Qt6::Label.new("Export"), "Export")
    splitter << scroll_area
    splitter << tab_widget
    window.central_widget = splitter

    slider.set_range(0, 100)
    slider.value = 42
    spin_box.set_range(1, 9)
    spin_box.single_step = 2
    spin_box.value = 5
    double_spin_box.set_range(0.5, 4.0)
    double_spin_box.single_step = 0.25
    double_spin_box.value = 1.75
    manual_mode.checked = true
    options_group.checked = false
    options_group.checked = true
    tab_widget.current_index = 1
    splitter.orientation = Qt6::Orientation::Vertical
    application.process_events

    scroll_area.widget_resizable?.should be_true
    splitter.count.should eq(2)
    splitter.orientation.should eq(Qt6::Orientation::Vertical)
    tab_widget.count.should eq(2)
    tab_widget.current_index.should eq(1)
    options_group.title.should eq("Options")
    options_group.checkable?.should be_true
    options_group.checked?.should be_true
    auto_mode.checked?.should be_false
    manual_mode.checked?.should be_true
    slider.orientation.should eq(Qt6::Orientation::Horizontal)
    slider.minimum.should eq(0)
    slider.maximum.should eq(100)
    slider.value.should eq(42)
    spin_box.minimum.should eq(1)
    spin_box.maximum.should eq(9)
    spin_box.single_step.should eq(2)
    spin_box.value.should eq(5)
    double_spin_box.minimum.should eq(0.5)
    double_spin_box.maximum.should eq(4.0)
    double_spin_box.single_step.should eq(0.25)
    double_spin_box.value.should eq(1.75)
    radio_states.last.should be_true
    slider_values.last.should eq(42)
    spin_values.last.should eq(5)
    double_values.last.should eq(1.75)
    group_states.last.should be_true
    tab_indices.last.should eq(1)
    window.release
  end

  it "provides QObject-derived signals and timer callbacks" do
    application = app
    timer = Qt6::QTimer.new
    destroyed = 0
    fired = 0

    timer.destroyed.connect do
      destroyed += 1
    end

    timer.on_timeout do
      fired += 1
    end

    timer.single_shot = true
    timer.start(0)

    10.times do
      application.process_events
      break if fired == 1
    end

    fired.should eq(1)
    timer.active?.should be_false
    timer.release
    destroyed.should eq(1)
  end

  it "supports nested event loops driven by timers" do
    app
    exit_loop = Qt6::QEventLoop.new
    exit_timer = Qt6::QTimer.new(exit_loop)
    exit_codes = [] of Int32

    exit_timer.single_shot = true
    exit_timer.on_timeout do
      exit_loop.running?.should be_true
      exit_codes << exit_loop.exit(23)
    end
    exit_timer.start(0)

    exit_loop.running?.should be_false
    exit_loop.run.should eq(23)
    exit_loop.running?.should be_false
    exit_codes.should eq([23])

    quit_loop = Qt6::QEventLoop.new
    quit_timer = Qt6::QTimer.new(quit_loop)
    quit_timer.single_shot = true
    quit_timer.on_timeout do
      quit_loop.running?.should be_true
      quit_loop.quit
    end
    quit_timer.start(0)

    quit_loop.run.should eq(0)
    quit_loop.running?.should be_false
  end

  it "supports list and tree widgets for editor panels" do
    application = app
    list_widget = Qt6::ListWidget.new
    tree_widget = Qt6::TreeWidget.new
    row_changes = [] of Int32
    tree_changes = 0

    list_widget.on_current_row_changed do |row|
      row_changes << row
    end

    terrain_item = list_widget.add_item("Terrain")
    unit_item = Qt6::ListWidgetItem.new("Units")
    list_widget.add_item(unit_item)
    list_widget.current_row = 1

    tree_widget.on_current_item_changed do
      tree_changes += 1
    end

    tree_widget.column_count = 2
    tree_widget.header_label = "Layer"
    tree_widget.set_header_label(1, "State")
    root_item = tree_widget.add_top_level_item("Terrain")
    root_item.set_text(1, "Visible")
    child_item = Qt6::TreeWidgetItem.new("Contours")
    child_item.set_text(1, "Locked")
    root_item.add_child(child_item)
    overlay_item = Qt6::TreeWidgetItem.new("Units")
    overlay_item.set_text(1, "Hidden")
    tree_widget.add_top_level_item(overlay_item)
    tree_widget.current_item = child_item
    tree_widget.expand_all
    application.process_events

    list_widget.count.should eq(2)
    terrain_item.text.should eq("Terrain")
    list_widget.item(1).not_nil!.text.should eq("Units")
    list_widget.item_text(0).should eq("Terrain")
    list_widget.current_row.should eq(1)
    list_widget.current_item.not_nil!.text.should eq("Units")
    list_widget.current_text.should eq("Units")
    row_changes.last.should eq(1)

    tree_widget.column_count.should eq(2)
    tree_widget.header_label.should eq("Layer")
    tree_widget.header_label(1).should eq("State")
    tree_widget.top_level_item_count.should eq(2)
    tree_widget.top_level_item(0).not_nil!.text.should eq("Terrain")
    root_item.child_count.should eq(1)
    root_item.child(0).not_nil!.text.should eq("Contours")
    root_item.child(0).not_nil!.text(1).should eq("Locked")
    tree_widget.current_item.not_nil!.text.should eq("Contours")
    tree_widget.current_item_text(1).should eq("Locked")
    tree_changes.should be >= 1

    list_widget.clear
    tree_widget.collapse_all
    tree_widget.clear

    list_widget.count.should eq(0)
    tree_widget.top_level_item_count.should eq(0)
    list_widget.release
    tree_widget.release
  end

  it "supports model-view panels with roles, delegates, and proxy sorting/filtering" do
    application = app
    list_view = Qt6::ListView.new
    tree_view = Qt6::TreeView.new
    list_model = Qt6::StandardItemModel.new(list_view)
    tree_model = Qt6::StandardItemModel.new(tree_view)
    proxy_model = Qt6::SortFilterProxyModel.new(list_view)
    delegate = Qt6::StyledItemDelegate.new(list_view)
    list_changes = 0
    tree_changes = 0

    list_view.on_current_index_changed do
      list_changes += 1
    end

    tree_view.on_current_index_changed do
      tree_changes += 1
    end

    terrain_list_item = Qt6::StandardItem.new("Terrain")
    terrain_list_item.set_data("Terrain tools", Qt6::ItemDataRole::ToolTip)
    terrain_list_item.set_data(20, Qt6::ItemDataRole::User)
    units_list_item = Qt6::StandardItem.new("Units")
    units_list_item.set_data(Qt6::Color.new(0, 64, 192), Qt6::ItemDataRole::Foreground)
    units_list_item.set_data(10, Qt6::ItemDataRole::User)
    list_model << terrain_list_item
    list_model << units_list_item

    tree_model.set_horizontal_header_label(0, "Layer")
    tree_model.set_horizontal_header_label(1, "State")
    terrain_item = Qt6::StandardItem.new("Terrain")
    terrain_state = Qt6::StandardItem.new("Visible")
    tree_model.set_item(0, 0, terrain_item)
    tree_model.set_item(0, 1, terrain_state)
    contour_item = Qt6::StandardItem.new("Contours")
    contour_state = Qt6::StandardItem.new("Locked")
    terrain_item.set_child(0, 0, contour_item)
    terrain_item.set_child(0, 1, contour_state)

    terrain_state_index = tree_model.index(0, 1)
    tree_model.set_data(terrain_state_index, "Shown", Qt6::ItemDataRole::Edit).should be_true

    delegate.on_display_text do |text|
      ">> #{text.upcase}"
    end

    proxy_model.source_model = list_model
    proxy_model.sort_role = Qt6::ItemDataRole::User
    proxy_model.filter_role = Qt6::ItemDataRole::Display
    proxy_model.filter_case_sensitivity = Qt6::CaseSensitivity::Insensitive
    proxy_model.dynamic_sort_filter = true
    proxy_model.sort

    list_view.model = proxy_model
    list_view.item_delegate = delegate
    tree_view.model = tree_model
    tree_view.expand_all

    list_index = proxy_model.index(0)
    tree_index = tree_model.index_from_item(contour_item)
    list_view.current_index = list_index
    tree_view.current_index = tree_index
    application.process_events

    current_list_index = list_view.current_index
    current_tree_index = tree_view.current_index
    source_list_index = proxy_model.map_to_source(current_list_index)

    list_model.row_count.should eq(2)
    list_model.column_count.should eq(1)
    list_model.item(0).not_nil!.text.should eq("Terrain")
    terrain_list_item.data(Qt6::ItemDataRole::ToolTip).should eq("Terrain tools")
    units_list_item.data(Qt6::ItemDataRole::Foreground).should eq(Qt6::Color.new(0, 64, 192, 255))
    list_model.data(source_list_index, Qt6::ItemDataRole::User).should eq(10)
    proxy_model.data(current_list_index).should eq("Units")
    delegate.display_text(proxy_model.data(current_list_index)).should eq(">> UNITS")
    current_list_index.valid?.should be_true
    current_list_index.row.should eq(0)
    current_list_index.column.should eq(0)
    source_list_index.row.should eq(1)
    list_changes.should be >= 1

    proxy_model.filter_fixed_string = "unit"
    proxy_model.invalidate
    application.process_events
    proxy_model.row_count.should eq(1)

    tree_model.row_count.should eq(1)
    tree_model.column_count.should eq(2)
    tree_model.horizontal_header_label.should eq("Layer")
    tree_model.horizontal_header_label(1).should eq("State")
    tree_model.data(terrain_state_index).should eq("Shown")
    terrain_item.row_count.should eq(1)
    terrain_item.child(0).not_nil!.text.should eq("Contours")
    terrain_item.child(0, 1).not_nil!.text.should eq("Locked")
    current_tree_index.valid?.should be_true
    current_tree_index.row.should eq(0)
    current_tree_index.column.should eq(0)
    tree_model.item_from_index(current_tree_index).not_nil!.text.should eq("Contours")
    tree_changes.should be >= 1

    current_list_index.release
    current_tree_index.release
    source_list_index.release
    terrain_state_index.release
    list_index.release
    tree_index.release
    list_view.release
    tree_view.release
  end

  it "supports custom delegate editor creation and commit hooks" do
    app
    host = Qt6::Widget.new
    model = Qt6::StandardItemModel.new(host)
    item = Qt6::StandardItem.new("terrain")
    model << item
    index = model.index(0)
    delegate = Qt6::StyledItemDelegate.new(host)
    created_editors = [] of Qt6::LineEdit
    populated_values = [] of Qt6::ModelData
    committed_values = [] of String

    delegate.on_create_editor do |parent, editor_index|
      editor_index.row.should eq(0)
      editor = Qt6::LineEdit.new(parent: parent)
      created_editors << editor
      editor
    end

    delegate.on_set_editor_data do |editor, value, editor_index|
      editor_index.column.should eq(0)
      line_edit = editor.as(Qt6::LineEdit)
      populated_values << value
      line_edit.text = "#{value}-editor"
    end

    delegate.on_set_model_data do |editor, target_model, editor_index|
      line_edit = editor.as(Qt6::LineEdit)
      committed_values << line_edit.text
      target_model.set_data(editor_index, line_edit.text.upcase)
    end

    editor = delegate.create_editor(host, index)
    editor.should be_a(Qt6::LineEdit)
    line_edit = editor.as(Qt6::LineEdit)
    delegate.set_editor_data(line_edit, index)
    line_edit.text.should eq("terrain-editor")
    line_edit.text = "contours"
    delegate.set_model_data(line_edit, model, index)

    created_editors.size.should eq(1)
    populated_values.should eq(["terrain"])
    committed_values.should eq(["contours"])
    model.data(index).should eq("CONTOURS")

    index.release
    host.release
  end

  it "supports proxy headers and shared selection models across views" do
    application = app
    list_view = Qt6::ListView.new
    tree_view = Qt6::TreeView.new
    source_model = Qt6::StandardItemModel.new(list_view)
    proxy_model = Qt6::SortFilterProxyModel.new(list_view)
    source_model << Qt6::StandardItem.new("Terrain")
    source_model << Qt6::StandardItem.new("Units")
    source_model.set_header_data(0, "Panel", Qt6::Orientation::Horizontal).should be_true
    proxy_model.source_model = source_model
    list_view.model = proxy_model
    tree_view.model = proxy_model

    shared_selection = Qt6::ItemSelectionModel.new(proxy_model, list_view)
    selection_changes = 0
    list_changes = 0
    tree_changes = 0

    shared_selection.on_current_index_changed do
      selection_changes += 1
    end

    list_view.on_current_index_changed do
      list_changes += 1
    end

    tree_view.on_current_index_changed do
      tree_changes += 1
    end

    list_view.selection_model = shared_selection
    tree_view.selection_model = shared_selection

    units_index = proxy_model.index(1)
    list_view.current_index = units_index
    application.process_events

    proxy_model.header_data.should eq("Panel")
    list_view.selection_model.not_nil!.current_index.row.should eq(1)
    tree_view.selection_model.not_nil!.current_index.row.should eq(1)
    tree_view.current_index.row.should eq(1)
    selection_changes.should be >= 1
    list_changes.should be >= 1
    tree_changes.should be >= 1

    units_index.release
    list_view.release
    tree_view.release
  end

  it "hosts a vertical editor slice with docks, canvas interaction, and PNG export" do
    application = app
    state = EditorVerticalSliceSpecState.new
    main = Qt6::MainWindow.new
    main.window_title = "Vertical Slice Spec"
    main.resize(960, 680)
    status_bar = main.status_bar
    canvas = Qt6::EventWidget.new
    canvas.resize(720, 480)
    export_path = File.join(Dir.tempdir, "crystal-qt6-vertical-slice-#{Process.pid}.png")

    grid_pen = Qt6::QPen.new(Qt6::Color.new(198, 206, 214), 1.0)
    frame_pen = Qt6::QPen.new(Qt6::Color.new(72, 80, 90), 2.0)
    route_pen = Qt6::QPen.new(state.accent, 3.0)
    hud_font = Qt6::QFont.new(point_size: 11, bold: true)

    scene_to_view = ->(point : Qt6::PointF) do
      Qt6::PointF.new(state.pan_x + point.x * state.zoom, state.pan_y + point.y * state.zoom)
    end

    canvas.on_mouse_press do |event|
      state.dragging = true
      state.last_pointer = event.position
    end

    canvas.on_mouse_move do |event|
      next unless state.dragging

      state.pan_x += event.position.x - state.last_pointer.x
      state.pan_y += event.position.y - state.last_pointer.y
      state.last_pointer = event.position
      canvas.update
    end

    canvas.on_mouse_release do |_event|
      state.dragging = false
    end

    canvas.on_wheel do |event|
      state.zoom = (state.zoom * (event.angle_delta.y >= 0 ? 1.1 : 0.9)).clamp(0.5, 3.0)
      canvas.update
    end

    canvas.on_paint_with_painter do |event, painter|
      painter.fill_rect(event.rect, Qt6::Color.new(245, 243, 238))

      scene_rect = Qt6::RectF.new(0.0, 0.0, 520.0, 320.0)
      painter.pen = frame_pen
      painter.brush = Qt6::Color.new(255, 255, 255)
      painter.draw_rect(Qt6::RectF.new(state.pan_x, state.pan_y, scene_rect.width * state.zoom, scene_rect.height * state.zoom))

      painter.pen = grid_pen
      x = 0
      while x <= scene_rect.width
        painter.draw_line(scene_to_view.call(Qt6::PointF.new(x.to_f, 0.0)), scene_to_view.call(Qt6::PointF.new(x.to_f, scene_rect.height)))
        x += 48
      end

      y = 0
      while y <= scene_rect.height
        painter.draw_line(scene_to_view.call(Qt6::PointF.new(0.0, y.to_f)), scene_to_view.call(Qt6::PointF.new(scene_rect.width, y.to_f)))
        y += 48
      end

      route_pen.color = state.accent
      painter.pen = route_pen
      painter.brush = state.accent
      points = case state.active_layer
               when "Units"
                 [
                   Qt6::PointF.new(96.0, 88.0),
                   Qt6::PointF.new(180.0, 156.0),
                   Qt6::PointF.new(276.0, 132.0),
                 ]
               else
                 [
                   Qt6::PointF.new(112.0, 92.0),
                   Qt6::PointF.new(210.0, 142.0),
                   Qt6::PointF.new(308.0, 118.0),
                 ]
               end.map { |point| scene_to_view.call(point) }

      points.each_cons(2) do |segment|
        painter.draw_line(segment[0], segment[1])
      end

      points.each_with_index do |point, index|
        size = 18.0 * state.zoom
        painter.draw_ellipse(Qt6::RectF.new(point.x - size / 2.0, point.y - size / 2.0, size, size))
        painter.draw_text(Qt6::PointF.new(point.x + size / 2.0 + 6.0, point.y + 4.0), "#{index + 1}")
      end

      painter.font = hud_font
      painter.pen = Qt6::Color.new(50, 56, 62)
      painter.draw_text(Qt6::PointF.new(18.0, 24.0), "Layer #{state.active_layer} | zoom #{state.zoom.round(2)}x")
    end

    main.central_widget = canvas

    layer_model = Qt6::StandardItemModel.new(main)
    terrain_item = Qt6::StandardItem.new("Terrain")
    terrain_item.set_data(10, Qt6::ItemDataRole::User)
    units_item = Qt6::StandardItem.new("Units")
    units_item.set_data(20, Qt6::ItemDataRole::User)
    layer_model.set_item(0, 0, terrain_item)
    layer_model.set_item(0, 1, Qt6::StandardItem.new("Visible"))
    layer_model.set_item(1, 0, units_item)
    layer_model.set_item(1, 1, Qt6::StandardItem.new("Visible"))
    layer_model.set_horizontal_header_label(0, "Layer")
    layer_model.set_horizontal_header_label(1, "State")

    proxy_model = Qt6::SortFilterProxyModel.new(main)
    proxy_model.source_model = layer_model
    proxy_model.sort_role = Qt6::ItemDataRole::User
    proxy_model.sort

    tree_view = Qt6::TreeView.new
    tree_view.model = proxy_model
    selection_model = Qt6::ItemSelectionModel.new(proxy_model, tree_view)
    tree_view.selection_model = selection_model
    tree_view.on_current_index_changed do
      current = tree_view.current_index
      if current.valid?
        name_index = proxy_model.index(current.row, 0)
        state.active_layer = proxy_model.data(name_index).to_s
        state.accent = state.active_layer == "Units" ? Qt6::Color.new(204, 86, 62) : Qt6::Color.new(62, 130, 109)
        status_bar.show_message("Active #{state.active_layer}", 1200)
        name_index.release
      end
      current.release
      canvas.update
    end

    layers_dock = Qt6::DockWidget.new("Layers", main)
    layers_dock.widget = Qt6::Widget.new.tap do |panel|
      panel.vbox do |column|
        column << Qt6::Label.new("Manager")
        column << tree_view
      end
    end
    main.add_dock_widget(layers_dock, Qt6::DockArea::Left)

    inspector_dock = Qt6::DockWidget.new("Inspector", main)
    inspector_dock.widget = Qt6::Widget.new.tap do |panel|
      panel.form do |form|
        form.add_row("Layer", Qt6::Label.new("Driven by the manager dock"))
        form.add_row(Qt6::PushButton.new("Reset View").tap do |button|
          button.on_clicked do
            state.zoom = 1.0
            state.pan_x = 24.0
            state.pan_y = 28.0
            canvas.update
          end
        end)
      end
    end
    main.add_dock_widget(inspector_dock, Qt6::DockArea::Right)

    file_menu = main.menu_bar.add_menu("File")
    export_action = Qt6::Action.new("Export PNG", main)
    export_action.shortcut = "Ctrl+E"
    export_action.on_triggered do
      canvas.grab.save(export_path).should be_true
      status_bar.show_message("Exported PNG", 1200)
    end
    file_menu << export_action

    toolbar = Qt6::ToolBar.new("Editor", main)
    toolbar << export_action
    main.add_tool_bar(toolbar)

    initial_index = proxy_model.index(1, 0)
    tree_view.current_index = initial_index
    initial_index.release

    main.show
    application.process_events

    zoom_before = state.zoom
    pan_x_before = state.pan_x
    pan_y_before = state.pan_y

    canvas.simulate_wheel(Qt6::PointF.new(180.0, 180.0))
    canvas.simulate_mouse_press(Qt6::PointF.new(140.0, 140.0))
    canvas.simulate_mouse_move(Qt6::PointF.new(196.0, 188.0), buttons: 1)
    canvas.simulate_mouse_release(Qt6::PointF.new(196.0, 188.0))
    5.times { application.process_events }

    export_action.trigger
    application.process_events

    png_header = File.open(export_path) do |file|
      bytes = Bytes.new(8)
      file.read_fully(bytes)
      bytes
    end

    state.active_layer.should eq("Units")
    proxy_model.header_data.should eq("Layer")
    tree_view.selection_model.not_nil!.current_index.row.should eq(1)
    state.zoom.should be > zoom_before
    state.pan_x.should be > pan_x_before
    state.pan_y.should be > pan_y_before
    File.exists?(export_path).should be_true
    png_header.should eq(Bytes[0x89_u8, 0x50_u8, 0x4E_u8, 0x47_u8, 0x0D_u8, 0x0A_u8, 0x1A_u8, 0x0A_u8])

    main.release
  end

  it "supports callback-backed abstract list models with edits and row notifications" do
    application = app
    model = EditableLayerListModel.new(["Terrain", "Units"])
    proxy = Qt6::SortFilterProxyModel.new
    proxy.source_model = model
    list_view = Qt6::ListView.new
    list_view.model = proxy

    delegate = Qt6::StyledItemDelegate.new(list_view)
    delegate.on_create_editor do |parent, _index|
      Qt6::LineEdit.new(parent: parent)
    end
    delegate.on_set_editor_data do |editor, value, _index|
      editor.as(Qt6::LineEdit).text = value.to_s
    end
    delegate.on_set_model_data do |editor, target_model, index|
      target_model.set_data(index, editor.as(Qt6::LineEdit).text).should be_true
    end
    list_view.item_delegate = delegate

    source_index = model.index(0)
    proxy_index = proxy.index(1)
    editor = delegate.create_editor(list_view, proxy_index)
    editor.should be_a(Qt6::LineEdit)
    line_edit = editor.as(Qt6::LineEdit)
    delegate.set_editor_data(line_edit, proxy_index)
    line_edit.text.should eq("Units")
    line_edit.text = "Counter"
    delegate.set_model_data(line_edit, proxy, proxy_index)
    application.process_events

    model.layers.should eq(["Terrain", "Counter"])
    proxy.data(proxy_index).should eq("Counter")
    proxy.header_data.should eq("Layer")
    model.flags(source_index).should eq(Qt6::ItemFlag::Enabled | Qt6::ItemFlag::Selectable | Qt6::ItemFlag::Editable)

    model.append_layer("Labels")
    application.process_events
    proxy.row_count.should eq(3)

    removed = model.remove_layer(0)
    application.process_events
    removed.should eq("Terrain")
    proxy.row_count.should eq(2)

    refreshed_index = proxy.index(0)
    proxy.data(refreshed_index).should eq("Counter")

    model.replace_layers(["Roads"])
    application.process_events
    proxy.row_count.should eq(1)

    reset_index = proxy.index(0)
    proxy.data(reset_index).should eq("Roads")

    source_index.release
    proxy_index.release
    refreshed_index.release
    reset_index.release
    list_view.release
    proxy.release
    model.release
  end

  it "exposes geometry types and custom widget event hooks" do
    application = app
    widget = Qt6::EventWidget.new
    paint_events = [] of Qt6::PaintEvent
    painter_events = [] of Qt6::PaintEvent
    resize_events = [] of Qt6::ResizeEvent
    mouse_presses = [] of Qt6::MouseEvent
    mouse_moves = [] of Qt6::MouseEvent
    mouse_releases = [] of Qt6::MouseEvent
    wheels = [] of Qt6::WheelEvent
    keys = [] of Qt6::KeyEvent

    widget.on_paint { |event| paint_events << event }
    widget.on_paint_with_painter do |event, painter|
      painter_events << event
      painter.active?.should be_true
      painter.fill_rect(Qt6::RectF.new(0.0, 0.0, 24.0, 16.0), Qt6::Color.new(255, 0, 0))
    end
    widget.on_resize { |event| resize_events << event }
    widget.on_mouse_press { |event| mouse_presses << event }
    widget.on_mouse_move { |event| mouse_moves << event }
    widget.on_mouse_release { |event| mouse_releases << event }
    widget.on_wheel { |event| wheels << event }
    widget.on_key_press { |event| keys << event }

    widget.resize(200, 120)
    widget.show
    application.process_events

    widget.repaint_now
    10.times do
      application.process_events
      break unless paint_events.empty?
    end
    widget.simulate_mouse_press(Qt6::PointF.new(10.0, 20.0))
    widget.simulate_mouse_move(Qt6::PointF.new(15.0, 25.0))
    widget.simulate_mouse_release(Qt6::PointF.new(18.0, 28.0))
    widget.simulate_wheel(Qt6::PointF.new(20.0, 30.0), angle_delta: Qt6::PointF.new(0.0, 120.0))
    widget.simulate_key_press(65)
    application.process_events
    snapshot = widget.grab.to_image

    widget.size.should eq(Qt6::Size.new(200, 120))
    widget.rect.width.should eq(200.0)
    resize_events.last.size.should eq(Qt6::Size.new(200, 120))
    paint_events.empty?.should be_false
    painter_events.empty?.should be_false
    mouse_presses.last.position.should eq(Qt6::PointF.new(10.0, 20.0))
    mouse_moves.last.position.should eq(Qt6::PointF.new(15.0, 25.0))
    mouse_releases.last.position.should eq(Qt6::PointF.new(18.0, 28.0))
    wheels.last.angle_delta.should eq(Qt6::PointF.new(0.0, 120.0))
    keys.last.key.should eq(65)
    snapshot.pixel_color(5, 5).should eq(Qt6::Color.new(255, 0, 0, 255))
    widget.release
  end

  it "supports drop callbacks and synthetic text drops on event widgets" do
    application = app
    widget = Qt6::EventWidget.new
    drag_enter_payloads = [] of String
    drag_move_positions = [] of Qt6::PointF
    dropped_payloads = [] of String
    acceptance_states = [] of Bool

    widget.accept_drops = true
    widget.on_drag_enter do |event|
      drag_enter_payloads << event.mime_data.not_nil!.text
      event.accept_proposed_action
      acceptance_states << event.accepted?
    end
    widget.on_drag_move do |event|
      drag_move_positions << event.position
      event.accept
    end
    widget.on_drop do |event|
      dropped_payloads << event.mime_data.not_nil!.text
      event.accept_proposed_action
      acceptance_states << event.accepted?
    end

    widget.resize(180, 100)
    widget.show
    application.process_events

    widget.simulate_drag_enter_text(Qt6::PointF.new(12.0, 14.0), "terrain")
    widget.simulate_drag_move_text(Qt6::PointF.new(18.0, 24.0), "terrain")
    widget.simulate_drop_text(Qt6::PointF.new(20.0, 26.0), "terrain")
    application.process_events

    widget.accept_drops?.should be_true
    drag_enter_payloads.should eq(["terrain"])
    drag_move_positions.should eq([Qt6::PointF.new(18.0, 24.0)])
    dropped_payloads.should eq(["terrain"])
    acceptance_states.should eq([true, true])
    widget.release
  end

  it "shuts down without the Qt thread storage warning" do
    stdout = IO::Memory.new
    stderr = IO::Memory.new
    status = Process.run(
      "crystal",
      ["run", "spec/support/exit_warning_probe.cr"],
      output: stdout,
      error: stderr
    )

    status.success?.should be_true
    stderr.to_s.should_not contain("QThreadStorage: entry")
  end

  it "creates a widget with a readable title and visibility state" do
    application = app
    window = Qt6::Widget.new
    window.window_title = "Spec Window"
    window.resize(320, 180)

    window.window_title.should eq("Spec Window")
    window.visible?.should be_false

    window.show
    application.process_events
    window.visible?.should be_true

    window.close
    application.process_events
    window.visible?.should be_false
    window.release
  end

  it "supports application metadata, stylesheets, and window icons" do
    application = app
    icon_path = File.join(Dir.tempdir, "crystal-qt6-window-icon-#{Process.pid}.png")
    icon_image = Qt6::QImage.new(16, 16)
    icon_image.fill(Qt6::Color.new(0, 0, 0, 0))
    icon_image.set_pixel_color(4, 4, Qt6::Color.new(32, 96, 180, 255))
    icon_image.save(icon_path).should be_true

    previous_name = application.name
    previous_organization_name = application.organization_name
    previous_organization_domain = application.organization_domain
    previous_style_sheet = application.style_sheet
    previous_window_icon = application.window_icon

    icon = Qt6::QIcon.from_file(icon_path)
    icon.null?.should be_false

    application.name = "crystal-qt6 specs"
    application.organization_name = "Spec Org"
    application.organization_domain = "spec.example"
    application.style_sheet = "QWidget { color: rgb(12, 34, 56); }"
    application.window_icon = icon

    window = Qt6::Widget.new
    window.style_sheet = "QWidget { background-color: rgb(22, 44, 66); }"
    window.window_icon = icon

    application.name.should eq("crystal-qt6 specs")
    application.organization_name.should eq("Spec Org")
    application.organization_domain.should eq("spec.example")
    application.style_sheet.should eq("QWidget { color: rgb(12, 34, 56); }")
    application.window_icon.null?.should be_false
    window.style_sheet.should eq("QWidget { background-color: rgb(22, 44, 66); }")
    window.window_icon.null?.should be_false

    window.release
    application.name = previous_name
    application.organization_name = previous_organization_name
    application.organization_domain = previous_organization_domain
    application.style_sheet = previous_style_sheet
    application.window_icon = previous_window_icon
  end

  it "updates label and button text" do
    app
    label = Qt6::Label.new("Ready")
    button = Qt6::PushButton.new("Launch")

    label.text.should eq("Ready")
    button.text.should eq("Launch")

    label.text = "Running"
    button.text = "Stop"

    label.text.should eq("Running")
    button.text.should eq("Stop")
    label.release
    button.release
  end

  it "supports layouts and click callbacks" do
    application = app
    window = Qt6::Widget.new
    layout = Qt6::VBoxLayout.new(window)
    label = Qt6::Label.new("0")
    button = Qt6::PushButton.new("Increment")
    clicks = 0

    layout << label
    layout << button

    button.on_clicked do
      clicks += 1
      label.text = clicks.to_s
    end

    button.click
    application.process_events

    clicks.should eq(1)
    label.text.should eq("1")
    window.release
  end

  it "supports hbox, form, and grid layouts" do
    app
    window = Qt6::Widget.new
    name_field = Qt6::LineEdit.new("Terrain")
    kind_field = Qt6::ComboBox.new
    kind_field << "Hexes" << "Terrain"
    primary = Qt6::PushButton.new("Primary")
    secondary = Qt6::PushButton.new("Secondary")
    top_left = Qt6::Label.new("A")
    top_right = Qt6::Label.new("B")
    footer = Qt6::Label.new("Footer")

    window.form do |form|
      form.add_row("Name", name_field)
      form.add_row(Qt6::Label.new("Kind"), kind_field)
      form.add_row(Qt6::Widget.new.tap do |button_row|
        button_row.hbox do |row|
          row << primary
          row << secondary
        end
      end)
      form.add_row(Qt6::Widget.new.tap do |grid_host|
        grid_host.grid do |grid|
          grid.add(top_left, 0, 0)
          grid.add(top_right, 0, 1)
          grid.add(footer, 1, 0, 1, 2)
        end
      end)
    end

    name_field.text.should eq("Terrain")
    kind_field.count.should eq(2)
    top_left.text.should eq("A")
    top_right.text.should eq("B")
    footer.text.should eq("Footer")
    window.release
  end

  it "builds a window with the helper DSL" do
    app
    window = Qt6.window("Helper Window", 420, 240) do |widget|
      widget.vbox do |column|
        column << Qt6::Label.new("Top")
        column << Qt6::PushButton.new("Action")
      end
    end

    window.window_title.should eq("Helper Window")
    window.release
  end
end
