require "./spec_helper"

describe Qt6 do
  it "renders into images and pixmaps with paths and transforms" do
    app
    image = Qt6::QImage.new(32, 32)
    image.fill(Qt6::Color.new(255, 255, 255))
    image.set_pixel_color(0, 0, Qt6::Color.new(1, 2, 3, 255))

    pen = Qt6::QPen.new(Qt6::Color.new(255, 0, 0), 3)
    brush = Qt6::QBrush.new(Qt6::Color.new(255, 0, 0))
    font = Qt6::QFont.new(point_size: 14, bold: true, italic: true)
    metrics = font.metrics
    metrics_f = font.metrics_f

    transform = Qt6::QTransform.new
    transform.translate(4, 5)

    path = Qt6::QPainterPath.new
    path.add_rect(Qt6::RectF.new(0.0, 0.0, 8.0, 8.0))
    moved_path = path.transformed(transform)
    translated_path = path.translated(10, 12)
    simplified_path = path.simplified

    curve_path = Qt6::QPainterPath.new
    curve_path.empty?.should be_true
    curve_path.move_to(Qt6::PointF.new(1.0, 2.0))
    curve_path.line_to(Qt6::PointF.new(5.0, 2.0))
    curve_path.quad_to(Qt6::PointF.new(8.0, 8.0), Qt6::PointF.new(10.0, 2.0))

    curve_path.empty?.should be_false
    curve_path.current_position.should eq(Qt6::PointF.new(10.0, 2.0))
    curve_path.element_count.should eq(5)
    curve_path[0].type.should eq(Qt6::PainterPathElementType::MoveTo)
    curve_path[0].point.should eq(Qt6::PointF.new(1.0, 2.0))
    curve_path[1].type.should eq(Qt6::PainterPathElementType::LineTo)
    curve_path[2].type.should eq(Qt6::PainterPathElementType::CurveTo)
    curve_path[3].type.should eq(Qt6::PainterPathElementType::CurveToData)
    curve_path[4].type.should eq(Qt6::PainterPathElementType::CurveToData)
    curve_path.control_point_rect.height.should be > curve_path.bounding_rect.height

    path.contains(Qt6::PointF.new(2.0, 2.0)).should be_true
    path.contains(Qt6::RectF.new(1.0, 1.0, 2.0, 2.0)).should be_true
    path.intersects?(Qt6::RectF.new(7.0, 7.0, 4.0, 4.0)).should be_true
    path.intersects?(Qt6::RectF.new(20.0, 20.0, 4.0, 4.0)).should be_false
    moved_path.bounding_rect.x.should eq(4.0)
    moved_path.bounding_rect.y.should eq(5.0)
    translated_path.bounding_rect.x.should eq(10.0)
    translated_path.bounding_rect.y.should eq(12.0)
    simplified_path.empty?.should be_false

    overlay_path = Qt6::QPainterPath.new
    overlay_path.add_rect(Qt6::RectF.new(10.0, 0.0, 4.0, 4.0))
    path.add_path(overlay_path)
    path.contains(Qt6::PointF.new(12.0, 2.0)).should be_true
    path.connect_path(curve_path)
    path.current_position.should eq(curve_path.current_position)

    disposable_path = Qt6::QPainterPath.new
    disposable_path.add_ellipse(Qt6::RectF.new(0.0, 0.0, 6.0, 6.0))
    disposable_path.empty?.should be_false
    disposable_path.clear
    disposable_path.empty?.should be_true

    Qt6::QPainter.paint(image) do |painter|
      painter.active?.should be_true
      painter.antialiasing = false
      painter.pen = pen
      painter.brush = brush
      painter.font = font
      painter.draw_path(moved_path)
      painter.fill_rect(Qt6::RectF.new(20.0, 20.0, 4.0, 4.0), Qt6::Color.new(0, 0, 255))
      painter.draw_line(Qt6::PointF.new(0.0, 31.0), Qt6::PointF.new(31.0, 31.0))
      painter.draw_text(Qt6::PointF.new(1.0, 16.0), "qt6")
    end

    pixmap = Qt6::QPixmap.from_image(image)
    pixmap_canvas = Qt6::QPixmap.new(40, 40)
    pixmap_canvas.fill(Qt6::Color.new(0, 0, 0, 0))
    svg_path = File.join(Dir.tempdir, "crystal-qt6-render-scene-#{Process.pid}.svg")
    svg = Qt6::QSvgGenerator.new(svg_path, 40, 40, title: "Render Scene", description: "Generated by crystal-qt6 specs")
    svg.resolution = 96
    pdf_path = File.join(Dir.tempdir, "crystal-qt6-render-scene-#{Process.pid}.pdf")
    pdf = Qt6::QPdfWriter.new(pdf_path, title: "Render Scene PDF", creator: "crystal-qt6 specs")
    pdf.page_size_points = Qt6::Size.new(120, 120)
    pdf.resolution = 144

    Qt6::QPainter.paint(pixmap_canvas) do |painter|
      painter.draw_image(Qt6::PointF.new(2.0, 2.0), image)
      painter.draw_pixmap(Qt6::PointF.new(0.0, 0.0), pixmap)
    end

    Qt6::QPainter.paint(svg) do |painter|
      painter.antialiasing = false
      painter.pen = pen
      painter.brush = brush
      painter.font = font
      painter.draw_path(moved_path)
      painter.fill_rect(Qt6::RectF.new(20.0, 20.0, 4.0, 4.0), Qt6::Color.new(0, 0, 255))
      painter.draw_text(Qt6::PointF.new(1.0, 16.0), "qt6-svg")
    end

    Qt6::QPainter.paint(pdf) do |painter|
      painter.antialiasing = false
      painter.pen = pen
      painter.brush = brush
      painter.font = font
      painter.draw_path(moved_path)
      painter.fill_rect(Qt6::RectF.new(20.0, 20.0, 4.0, 4.0), Qt6::Color.new(0, 0, 255))
      painter.draw_text(Qt6::PointF.new(1.0, 16.0), "qt6-pdf")
      pdf.new_page.should be_true
      painter.reset_transform
      painter.draw_line(Qt6::PointF.new(0.0, 0.0), Qt6::PointF.new(30.0, 30.0))
    end

    svg_file_name = svg.file_name
    svg_size = svg.size
    svg_view_box = svg.view_box
    svg_title = svg.title
    svg_description = svg.description
    svg_resolution = svg.resolution
    pdf_file_name = pdf.file_name
    pdf_title = pdf.title
    pdf_creator = pdf.creator
    pdf_resolution = pdf.resolution

    svg_markup = begin
      svg.release
      File.read(svg_path)
    end

    svg_renderer = Qt6::QSvgRenderer.new(svg_path)
    svg_renderer.valid?.should be_true

    svg_canvas = Qt6::QImage.new(40, 40)
    svg_canvas.fill(Qt6::Color.new(255, 255, 255))
    Qt6::QPainter.paint(svg_canvas) do |painter|
      svg_renderer.render(painter, Qt6::RectF.new(0.0, 0.0, 40.0, 40.0))
    end

    svg_default_size = svg_renderer.default_size
    svg_render_view_box = svg_renderer.view_box

    pdf_header = begin
      pdf.release
      File.open(pdf_path) do |file|
        bytes = Bytes.new(5)
        file.read_fully(bytes)
        String.new(bytes)
      end
    end

    pixmap_image = pixmap_canvas.to_image
    image_path = File.join(Dir.tempdir, "crystal-qt6-render-image-#{Process.pid}.png")
    pixmap_path = File.join(Dir.tempdir, "crystal-qt6-render-pixmap-#{Process.pid}.png")
    text_bounds = metrics.bounding_rect("qt6")
    text_bounds_f = metrics_f.bounding_rect("qt6")

    pen.width.should eq(3.0)
    pen.color.should eq(Qt6::Color.new(255, 0, 0, 255))
    brush.color.should eq(Qt6::Color.new(255, 0, 0, 255))
    font.point_size.should eq(14)
    font.bold?.should be_true
    font.italic?.should be_true
    metrics.height.should be > 0
    metrics.ascent.should be > 0
    metrics.descent.should be >= 0
    metrics.horizontal_advance("qt6").should be > 0
    text_bounds.width.should be > 0.0
    text_bounds.height.should be > 0.0
    metrics_f.height.should be > 0.0
    metrics_f.ascent.should be > 0.0
    metrics_f.descent.should be >= 0.0
    metrics_f.horizontal_advance("qt6").should be > 0.0
    text_bounds_f.width.should be > 0.0
    text_bounds_f.height.should be > 0.0
    transform.map(Qt6::PointF.new(1.0, 1.0)).should eq(Qt6::PointF.new(5.0, 6.0))
    transform.map(Qt6::RectF.new(0.0, 0.0, 8.0, 8.0)).should eq(Qt6::RectF.new(4.0, 5.0, 8.0, 8.0))
    moved_path.bounding_rect.should eq(Qt6::RectF.new(4.0, 5.0, 8.0, 8.0))
    image.pixel_color(0, 0).should eq(Qt6::Color.new(1, 2, 3, 255))
    image.pixel_color(6, 7).should eq(Qt6::Color.new(255, 0, 0, 255))
    image.pixel_color(21, 21).should eq(Qt6::Color.new(0, 0, 255, 255))
    pixmap.width.should eq(32)
    pixmap.height.should eq(32)
    pixmap.null?.should be_false
    svg_file_name.should eq(svg_path)
    svg_size.should eq(Qt6::Size.new(40, 40))
    svg_view_box.should eq(Qt6::RectF.new(0.0, 0.0, 40.0, 40.0))
    svg_default_size.width.should be > 0
    svg_default_size.height.should be > 0
    svg_render_view_box.should eq(Qt6::RectF.new(0.0, 0.0, 40.0, 40.0))
    svg_title.should eq("Render Scene")
    svg_description.should eq("Generated by crystal-qt6 specs")
    svg_resolution.should eq(96)
    pdf_file_name.should eq(pdf_path)
    pdf_title.should eq("Render Scene PDF")
    pdf_creator.should eq("crystal-qt6 specs")
    pdf_resolution.should eq(144)
    pixmap_image.pixel_color(1, 1).should eq(Qt6::Color.new(255, 255, 255, 255))
    pixmap_image.pixel_color(6, 7).should eq(Qt6::Color.new(255, 0, 0, 255))
    image.save(image_path).should be_true
    pixmap.save(pixmap_path).should be_true
    File.exists?(image_path).should be_true
    File.exists?(pixmap_path).should be_true
    File.exists?(svg_path).should be_true
    File.exists?(pdf_path).should be_true
    svg_markup.includes?("<svg").should be_true
    svg_markup.includes?("<title>Render Scene</title>").should be_true
    svg_markup.includes?("Generated by crystal-qt6 specs").should be_true
    pdf_header.should eq("%PDF-")
    svg_canvas.pixel_color(6, 7).should eq(Qt6::Color.new(255, 0, 0, 255))
    svg_canvas.pixel_color(21, 21).should eq(Qt6::Color.new(0, 0, 255, 255))
  end

  it "supports richer painter state, polygons, strokers, and textured brushes" do
    app

    polygon = Qt6::QPolygonF.new([
      Qt6::PointF.new(0.0, 0.0),
      Qt6::PointF.new(4.0, 0.0),
      Qt6::PointF.new(4.0, 4.0),
      Qt6::PointF.new(0.0, 4.0),
    ])
    polygon << Qt6::PointF.new(0.0, 0.0)

    path = Qt6::QPainterPath.new
    path.add_polygon(polygon)

    map_transform = Qt6::QTransform.new
    map_transform.translate(6, 0)
    moved_path = map_transform.map(path)

    stroker = Qt6::QPainterPathStroker.new
    stroker.width = 2.0
    stroked_path = stroker.create_stroke(path)

    pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1)
    pen.style = Qt6::PenStyle::NoPen
    pen.cap_style = Qt6::PenCapStyle::RoundCap

    texture = Qt6::QPixmap.new(1, 1)
    texture.fill(Qt6::Color.new(220, 40, 40))
    textured_brush = Qt6::QBrush.new(texture)
    brush_transform = Qt6::QTransform.new
    brush_transform.translate(1, 0)
    textured_brush.transform = brush_transform

    source = Qt6::QImage.new(2, 2)
    source.fill(Qt6::Color.new(30, 60, 220))
    source_pixmap = Qt6::QPixmap.from_image(source)

    canvas = Qt6::QImage.new(12, 12)
    canvas.fill(Qt6::Color.new(0, 0, 0, 0))

    Qt6::QPainter.paint(canvas) do |painter|
      painter.smooth_pixmap_transform = true
      painter.pen = pen
      painter.brush = textured_brush
      painter.draw_polygon(polygon)

      painter.save
      painter.clip_path = moved_path
      painter.fill_rect(Qt6::RectF.new(0.0, 0.0, 12.0, 12.0), Qt6::Color.new(40, 220, 80))
      painter.restore

      painter.save
      painter.translate(8, 8)
      painter.opacity = 0.5
      painter.draw_image(0, 0, source)
      painter.restore

      painter.draw_pixmap(0, 8, source_pixmap)
      painter.composition_mode = Qt6::PainterCompositionMode::Clear
      painter.fill_rect(Qt6::RectF.new(8.0, 8.0, 1.0, 1.0), Qt6::Color.new(255, 255, 255))
      painter.composition_mode.should eq(Qt6::PainterCompositionMode::Clear)
      painter.composition_mode = Qt6::PainterCompositionMode::SourceOver
      painter.brush = Qt6::Color.new(70, 170, 240)
      painter.draw_ellipse(Qt6::PointF.new(10.0, 2.0), 1.0, 1.0)
    end

    polygon.size.should eq(5)
    polygon[2].should eq(Qt6::PointF.new(4.0, 4.0))
    polygon.bounding_rect.should eq(Qt6::RectF.new(0.0, 0.0, 4.0, 4.0))
    path.empty?.should be_false
    path.contains(Qt6::PointF.new(2.0, 2.0)).should be_true
    path.contains(Qt6::PointF.new(5.5, 2.0)).should be_false
    moved_path.bounding_rect.should eq(Qt6::RectF.new(6.0, 0.0, 4.0, 4.0))
    stroked_path.contains(Qt6::PointF.new(0.2, 2.0)).should be_true
    pen.style.should eq(Qt6::PenStyle::NoPen)
    pen.cap_style.should eq(Qt6::PenCapStyle::RoundCap)
    textured_brush.transform.map(Qt6::PointF.new(1.0, 1.0)).should eq(Qt6::PointF.new(2.0, 1.0))

    canvas.pixel_color(2, 2).should eq(Qt6::Color.new(220, 40, 40, 255))
    canvas.pixel_color(7, 2).should eq(Qt6::Color.new(40, 220, 80, 255))
    canvas.pixel_color(5, 2).should eq(Qt6::Color.new(0, 0, 0, 0))
    canvas.pixel_color(8, 8).should eq(Qt6::Color.new(0, 0, 0, 0))
    faded = canvas.pixel_color(9, 9)
    faded.red.should eq(30)
    faded.green.should eq(60)
    faded.blue.should eq(220)
    faded.alpha.should eq(127)
    canvas.pixel_color(0, 8).should eq(Qt6::Color.new(30, 60, 220, 255))
    canvas.pixel_color(10, 2).should eq(Qt6::Color.new(70, 170, 240, 255))

    deep_source = Qt6::QImage.new(4, 4)
    deep_source.fill(Qt6::Color.new(0, 0, 0, 0))
    deep_source.set_pixel_color(2, 2, Qt6::Color.new(240, 30, 30))
    deep_pixmap = Qt6::QPixmap.from_image(deep_source)
    deep_canvas = Qt6::QImage.new(12, 12)
    deep_canvas.fill(Qt6::Color.new(0, 0, 0, 0))

    painter = Qt6::QPainter.new(deep_canvas)
    painter.active?.should be_true
    painter.antialiasing = false
    painter.draw_image(
      Qt6::RectF.new(0.0, 0.0, 4.0, 4.0),
      deep_source,
      Qt6::RectF.new(2.0, 2.0, 1.0, 1.0)
    )
    painter.draw_pixmap(
      Qt6::RectF.new(4.0, 0.0, 4.0, 4.0),
      deep_pixmap,
      Qt6::RectF.new(2.0, 2.0, 1.0, 1.0)
    )
    painter.clip_rect = Qt6::RectF.new(0.0, 4.0, 2.0, 2.0)
    painter.fill_rect(Qt6::RectF.new(0.0, 4.0, 4.0, 4.0), Qt6::QBrush.new(Qt6::Color.new(30, 220, 90)))
    painter.clipping = false
    painter.save
    painter.translate(12, 12)
    painter.rotate(180)
    painter.fill_rect(Qt6::RectF.new(0.0, 0.0, 2.0, 2.0), Qt6::Color.new(80, 40, 220))
    painter.restore
    painter.draw_point(Qt6::PointF.new(8.0, 8.0))
    painter.end.should be_true
    painter.active?.should be_false
    painter.release

    deep_canvas.pixel_color(0, 0).should eq(Qt6::Color.new(240, 30, 30, 255))
    deep_canvas.pixel_color(4, 0).should eq(Qt6::Color.new(240, 30, 30, 255))
    deep_canvas.pixel_color(1, 5).should eq(Qt6::Color.new(30, 220, 90, 255))
    deep_canvas.pixel_color(3, 5).should eq(Qt6::Color.new(0, 0, 0, 0))
    deep_canvas.pixel_color(10, 10).should eq(Qt6::Color.new(80, 40, 220, 255))
    deep_canvas.pixel_color(8, 8).should eq(Qt6::Color.new(0, 0, 0, 255))
  end

  it "supports gradients and advanced pen styling" do
    app

    gradient_canvas = Qt6::QImage.new(12, 12)
    gradient_canvas.fill(Qt6::Color.new(0, 0, 0, 0))
    conical_canvas = Qt6::QImage.new(12, 12)
    conical_canvas.fill(Qt6::Color.new(0, 0, 0, 0))

    linear = Qt6::QLinearGradient.new(0.0, 0.0, 10.0, 0.0)
    linear.set_color_at(0.0, Qt6::Color.new(255, 0, 0))
    linear.set_color_at(1.0, Qt6::Color.new(0, 0, 255))
    linear.stops.should eq([
      Qt6::GradientStop.new(0.0, Qt6::Color.new(255, 0, 0, 255)),
      Qt6::GradientStop.new(1.0, Qt6::Color.new(0, 0, 255, 255)),
    ])
    linear.start.should eq(Qt6::PointF.new(0.0, 0.0))
    linear.final_stop.should eq(Qt6::PointF.new(10.0, 0.0))
    linear.spread.should eq(Qt6::GradientSpread::PadSpread)
    linear.coordinate_mode.should eq(Qt6::GradientCoordinateMode::LogicalMode)

    configured_linear = Qt6::QLinearGradient.new(0.0, 0.0, 10.0, 0.0)
    configured_linear.spread = Qt6::GradientSpread::RepeatSpread
    configured_linear.coordinate_mode = Qt6::GradientCoordinateMode::ObjectBoundingMode
    configured_linear.spread.should eq(Qt6::GradientSpread::RepeatSpread)
    configured_linear.coordinate_mode.should eq(Qt6::GradientCoordinateMode::ObjectBoundingMode)

    radial = Qt6::QRadialGradient.new(Qt6::PointF.new(6.0, 8.0), 4.0)
    radial.set_color_at(0.0, Qt6::Color.new(255, 255, 255))
    radial.set_color_at(1.0, Qt6::Color.new(0, 0, 0))
    radial.stops.should eq([
      Qt6::GradientStop.new(0.0, Qt6::Color.new(255, 255, 255, 255)),
      Qt6::GradientStop.new(1.0, Qt6::Color.new(0, 0, 0, 255)),
    ])
    radial.center.should eq(Qt6::PointF.new(6.0, 8.0))
    radial.focal_point.should eq(Qt6::PointF.new(6.0, 8.0))
    radial.radius.should eq(4.0)
    radial.spread.should eq(Qt6::GradientSpread::PadSpread)
    radial.coordinate_mode.should eq(Qt6::GradientCoordinateMode::LogicalMode)
    configured_radial = Qt6::QRadialGradient.new(Qt6::PointF.new(6.0, 8.0), 4.0)
    configured_radial.spread = Qt6::GradientSpread::ReflectSpread
    configured_radial.coordinate_mode = Qt6::GradientCoordinateMode::StretchToDeviceMode
    configured_radial.spread.should eq(Qt6::GradientSpread::ReflectSpread)
    configured_radial.coordinate_mode.should eq(Qt6::GradientCoordinateMode::StretchToDeviceMode)

    offset_radial = Qt6::QRadialGradient.new(Qt6::PointF.new(6.0, 8.0), 4.0, Qt6::PointF.new(8.0, 8.0))
    offset_radial.set_color_at(0.0, Qt6::Color.new(255, 255, 255))
    offset_radial.set_color_at(1.0, Qt6::Color.new(0, 0, 0))
    offset_radial.focal_point.should eq(Qt6::PointF.new(8.0, 8.0))
    offset_radial.focal_point = Qt6::PointF.new(7.0, 8.0)
    offset_radial.focal_point.should eq(Qt6::PointF.new(7.0, 8.0))

    conical = Qt6::QConicalGradient.new(Qt6::PointF.new(6.0, 6.0), 0.0)
    conical.set_color_at(0.0, Qt6::Color.new(255, 0, 0))
    conical.set_color_at(0.5, Qt6::Color.new(0, 0, 255))
    conical.set_color_at(1.0, Qt6::Color.new(255, 0, 0))
    conical.stops.should eq([
      Qt6::GradientStop.new(0.0, Qt6::Color.new(255, 0, 0, 255)),
      Qt6::GradientStop.new(0.5, Qt6::Color.new(0, 0, 255, 255)),
      Qt6::GradientStop.new(1.0, Qt6::Color.new(255, 0, 0, 255)),
    ])
    conical.center.should eq(Qt6::PointF.new(6.0, 6.0))
    conical.angle.should eq(0.0)
    conical.angle = 90.0
    conical.angle.should eq(90.0)
    conical.spread.should eq(Qt6::GradientSpread::PadSpread)
    conical.coordinate_mode.should eq(Qt6::GradientCoordinateMode::LogicalMode)
    configured_conical = Qt6::QConicalGradient.new(Qt6::PointF.new(6.0, 6.0), 90.0)
    configured_conical.spread = Qt6::GradientSpread::ReflectSpread
    configured_conical.coordinate_mode = Qt6::GradientCoordinateMode::ObjectMode
    configured_conical.spread.should eq(Qt6::GradientSpread::ReflectSpread)
    configured_conical.coordinate_mode.should eq(Qt6::GradientCoordinateMode::ObjectMode)

    Qt6::QPainter.paint(gradient_canvas) do |painter|
      painter.antialiasing = false
      painter.pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1).tap { |pen| pen.style = Qt6::PenStyle::NoPen }
      painter.brush = Qt6::QBrush.new(linear)
      painter.draw_rect(Qt6::RectF.new(0.0, 0.0, 10.0, 4.0))
      painter.brush = Qt6::QBrush.new(radial)
      painter.draw_rect(Qt6::RectF.new(2.0, 4.0, 8.0, 8.0))
    end

    Qt6::QPainter.paint(conical_canvas) do |painter|
      painter.antialiasing = false
      painter.pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1).tap { |pen| pen.style = Qt6::PenStyle::NoPen }
      painter.brush = Qt6::QBrush.new(conical)
      painter.draw_ellipse(Qt6::RectF.new(0.0, 0.0, 12.0, 12.0))
    end

    offset_radial_canvas = Qt6::QImage.new(14, 14)
    offset_radial_canvas.fill(Qt6::Color.new(0, 0, 0, 0))
    Qt6::QPainter.paint(offset_radial_canvas) do |painter|
      painter.antialiasing = false
      painter.pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1).tap { |pen| pen.style = Qt6::PenStyle::NoPen }
      painter.brush = Qt6::QBrush.new(offset_radial)
      painter.draw_rect(Qt6::RectF.new(1.0, 1.0, 12.0, 12.0))
    end

    left = gradient_canvas.pixel_color(1, 1)
    middle = gradient_canvas.pixel_color(5, 1)
    right = gradient_canvas.pixel_color(8, 1)
    radial_center = gradient_canvas.pixel_color(6, 8)
    radial_edge = gradient_canvas.pixel_color(2, 8)
    offset_radial_left = offset_radial_canvas.pixel_color(6, 8)
    offset_radial_center = offset_radial_canvas.pixel_color(7, 8)
    offset_radial_right = offset_radial_canvas.pixel_color(8, 8)
    conical_samples = [
      conical_canvas.pixel_color(6, 1),
      conical_canvas.pixel_color(10, 6),
      conical_canvas.pixel_color(6, 10),
      conical_canvas.pixel_color(1, 6),
    ]

    left.red.should be > left.blue
    middle.red.should be > 0
    middle.blue.should be > 0
    right.blue.should be > right.red
    radial_center.red.should be > radial_edge.red
    radial_center.green.should be > radial_edge.green
    radial_center.blue.should be > radial_edge.blue
    offset_radial_left.red.should be > offset_radial_center.red
    offset_radial_center.red.should be > offset_radial_right.red
    offset_radial_left.green.should be > offset_radial_center.green
    offset_radial_center.green.should be > offset_radial_right.green
    offset_radial_left.blue.should be > offset_radial_center.blue
    offset_radial_center.blue.should be > offset_radial_right.blue
    conical_samples.all? { |sample| sample.alpha > 0 }.should be_true
    conical_samples.map { |sample| {sample.red, sample.green, sample.blue, sample.alpha} }.uniq.size.should be > 1
    conical_samples.any? { |sample| sample.red > 0 }.should be_true
    conical_samples.any? { |sample| sample.blue > 0 }.should be_true

    repeated_canvas = Qt6::QImage.new(12, 4)
    repeated_canvas.fill(Qt6::Color.new(0, 0, 0, 0))
    repeating = Qt6::QLinearGradient.new(0.0, 0.0, 0.5, 0.0)
    repeating.coordinate_mode = Qt6::GradientCoordinateMode::ObjectBoundingMode
    repeating.spread = Qt6::GradientSpread::RepeatSpread
    repeating.set_color_at(0.0, Qt6::Color.new(255, 0, 0))
    repeating.set_color_at(1.0, Qt6::Color.new(0, 0, 255))

    Qt6::QPainter.paint(repeated_canvas) do |painter|
      painter.antialiasing = false
      painter.pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1).tap { |pen| pen.style = Qt6::PenStyle::NoPen }
      painter.brush = Qt6::QBrush.new(repeating)
      painter.draw_rect(Qt6::RectF.new(0.0, 0.0, 12.0, 4.0))
    end

    repeat_left = repeated_canvas.pixel_color(1, 1)
    repeat_middle = repeated_canvas.pixel_color(4, 1)
    repeat_second_cycle = repeated_canvas.pixel_color(7, 1)
    repeat_right = repeated_canvas.pixel_color(10, 1)
    repeat_left.red.should be > repeat_left.blue
    repeat_middle.blue.should be > repeat_middle.red
    repeat_second_cycle.red.should be > repeat_second_cycle.blue
    repeat_right.blue.should be > repeat_right.red

    dash_canvas = Qt6::QImage.new(12, 12)
    dash_canvas.fill(Qt6::Color.new(0, 0, 0, 0))

    dashed_pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1)
    dashed_pen.cap_style = Qt6::PenCapStyle::FlatCap
    dashed_pen.join_style = Qt6::PenJoinStyle::RoundJoin
    dashed_pen.dash_pattern = [2.0, 2.0]
    dashed_pen.dash_offset = 0.0

    Qt6::QPainter.paint(dash_canvas) do |painter|
      painter.antialiasing = false
      painter.pen = dashed_pen
      painter.draw_line(Qt6::PointF.new(0.0, 6.0), Qt6::PointF.new(11.0, 6.0))
    end

    dashed_pen.style.should eq(Qt6::PenStyle::CustomDashLine)
    dashed_pen.join_style.should eq(Qt6::PenJoinStyle::RoundJoin)
    dashed_pen.dash_offset.should eq(0.0)
    dash_canvas.pixel_color(0, 6).should eq(Qt6::Color.new(0, 0, 0, 255))
    dash_canvas.pixel_color(1, 6).should eq(Qt6::Color.new(0, 0, 0, 255))
    dash_canvas.pixel_color(3, 6).should eq(Qt6::Color.new(0, 0, 0, 0))
    dash_canvas.pixel_color(4, 6).should eq(Qt6::Color.new(0, 0, 0, 255))
    dash_canvas.pixel_color(5, 6).should eq(Qt6::Color.new(0, 0, 0, 255))
    dash_canvas.pixel_color(7, 6).should eq(Qt6::Color.new(0, 0, 0, 0))
  end

  it "supports rounded primitives, polylines, arcs, and rect-based text" do
    app

    canvas = Qt6::QImage.new(40, 40)
    canvas.fill(Qt6::Color.new(0, 0, 0, 0))

    outline_pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1)
    fill_pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1)
    fill_pen.style = Qt6::PenStyle::NoPen
    polyline_pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 255), 1)
    polyline_pen.cap_style = Qt6::PenCapStyle::FlatCap

    polyline = Qt6::QPolygonF.new
    polyline << Qt6::PointF.new(2.0, 20.0)
    polyline << Qt6::PointF.new(10.0, 12.0)
    polyline << Qt6::PointF.new(18.0, 20.0)

    Qt6::QPainter.paint(canvas) do |painter|
      painter.antialiasing = false

      painter.pen = fill_pen
      painter.brush = Qt6::Color.new(240, 80, 80)
      painter.draw_rounded_rect(Qt6::RectF.new(2.0, 2.0, 12.0, 12.0), 3.0, 3.0)

      painter.pen = polyline_pen
      painter.brush = Qt6::QBrush.new(Qt6::Color.new(0, 0, 0, 0))
      painter.draw_polyline(polyline)

      painter.pen = outline_pen
      painter.draw_arc(Qt6::RectF.new(20.0, 2.0, 12.0, 12.0), 0, 90 * 16)

      painter.pen = fill_pen
      painter.brush = Qt6::Color.new(80, 220, 80)
      painter.draw_pie(Qt6::RectF.new(20.0, 16.0, 12.0, 12.0), 0, 90 * 16)

      painter.brush = Qt6::Color.new(80, 80, 240)
      painter.draw_chord(Qt6::RectF.new(20.0, 28.0, 12.0, 10.0), 0, 180 * 16)

      painter.pen = Qt6::Color.new(255, 255, 255)
      painter.draw_text(
        Qt6::RectF.new(0.0, 28.0, 18.0, 10.0),
        Qt6::AlignmentFlag::Center,
        "A"
      )
    end

    canvas.pixel_color(8, 8).should eq(Qt6::Color.new(240, 80, 80, 255))
    canvas.pixel_color(2, 2).should eq(Qt6::Color.new(0, 0, 0, 0))
    canvas.pixel_color(10, 12).should eq(Qt6::Color.new(0, 0, 255, 255))
    canvas.pixel_color(32, 8).should eq(Qt6::Color.new(0, 0, 0, 255))
    canvas.pixel_color(31, 20).should eq(Qt6::Color.new(80, 220, 80, 255))
    canvas.pixel_color(26, 31).should eq(Qt6::Color.new(80, 80, 240, 255))
    text_pixels = (28..37).sum do |y|
      (0..17).count { |x| canvas.pixel_color(x, y).alpha > 0 }
    end
    text_pixels.should be > 0
  end

  it "supports regions for clipping, combination, and widget masks" do
    app

    base = Qt6::QRegion.new(Qt6::Rect.new(0, 0, 8, 8))
    ellipse = Qt6::QRegion.new(Qt6::Rect.new(4, 0, 8, 8), Qt6::RegionType::Ellipse)
    combined = base.united(ellipse)
    overlap = combined.intersected(Qt6::Rect.new(4, 0, 4, 8))
    translated = overlap.translated(0, 8)
    xor_region = base.xored(Qt6::QRegion.new(Qt6::Rect.new(4, 0, 8, 8)))
    subtracted = combined.subtracted(base)

    base.empty?.should be_false
    base.null?.should be_false
    base.bounding_rect.should eq(Qt6::Rect.new(0, 0, 8, 8))
    base.contains?(Qt6::Rect.new(1, 1, 2, 2)).should be_true
    base.intersects?(Qt6::Rect.new(7, 7, 4, 4)).should be_true
    combined.intersects?(ellipse).should be_true
    overlap.bounding_rect.should eq(Qt6::Rect.new(4, 0, 4, 8))
    translated.bounding_rect.should eq(Qt6::Rect.new(4, 8, 4, 8))
    xor_region.contains?(Qt6::Rect.new(0, 0, 2, 2)).should be_true
    xor_region.contains?(Qt6::Rect.new(5, 0, 2, 2)).should be_false
    subtracted.empty?.should be_false
    combined.rect_count.should be > 0

    mutable = Qt6::QRegion.new(Qt6::Rect.new(0, 0, 4, 4))
    mutable.unite(Qt6::Rect.new(4, 0, 4, 4))
    mutable.bounding_rect.should eq(Qt6::Rect.new(0, 0, 8, 4))
    mutable.intersect(Qt6::Rect.new(2, 0, 4, 4))
    mutable.bounding_rect.should eq(Qt6::Rect.new(2, 0, 4, 4))
    mutable.subtract(Qt6::QRegion.new(Qt6::Rect.new(4, 0, 2, 4)))
    mutable.contains?(Qt6::Rect.new(4, 0, 1, 1)).should be_false
    mutable.exclusive_or(Qt6::QRegion.new(Qt6::Rect.new(0, 0, 2, 4)))
    mutable.contains?(Qt6::Rect.new(0, 0, 2, 2)).should be_true
    mutable.clear
    mutable.empty?.should be_true

    canvas = Qt6::QImage.new(16, 16)
    canvas.fill(Qt6::Color.new(0, 0, 0, 0))
    clip_region = Qt6::QRegion.new(Qt6::Rect.new(4, 4, 4, 4))

    Qt6::QPainter.paint(canvas) do |painter|
      painter.clip_region = clip_region
      painter.fill_rect(Qt6::RectF.new(0.0, 0.0, 16.0, 16.0), Qt6::Color.new(220, 40, 40))
    end

    canvas.pixel_color(5, 5).should eq(Qt6::Color.new(220, 40, 40, 255))
    canvas.pixel_color(2, 2).should eq(Qt6::Color.new(0, 0, 0, 0))

    window = Qt6::Widget.new
    window.resize(16, 16)
    window.mask = ellipse
    window.mask.bounding_rect.should eq(Qt6::Rect.new(4, 0, 8, 8))
    window.mask.empty?.should be_false
    window.mask = nil
    window.mask.empty?.should be_true
    window.release

    widget = Qt6::Widget.new
    widget.resize(24, 24)
    widget.show
    app.process_events

    update_region = Qt6::QRegion.new(Qt6::Rect.new(6, 8, 5, 4))
    widget.update(update_region).should eq(widget)
    widget.update(Qt6::Rect.new(2, 3, 4, 5)).should eq(widget)
    widget.release
  end

  it "supports monochrome bitmaps for masks, transforms, and file round-trips" do
    app

    source = Qt6::QImage.new(8, 8)
    source.fill(Qt6::Color.new(255, 255, 255))
    Qt6::QPainter.paint(source) do |painter|
      painter.fill_rect(Qt6::RectF.new(0.0, 0.0, 4.0, 8.0), Qt6::Color.new(0, 0, 0))
    end

    bitmap = Qt6::QBitmap.from_image(source)
    bitmap.null?.should be_false
    bitmap.size.should eq(Qt6::Size.new(8, 8))
    bitmap.to_image.pixel_color(1, 1).should eq(Qt6::Color.new(0, 0, 0, 255))
    bitmap.to_image.pixel_color(6, 1).should eq(Qt6::Color.new(255, 255, 255, 255))

    bitmap_region = Qt6::QRegion.new(bitmap)
    bitmap_region.bounding_rect.should eq(Qt6::Rect.new(0, 0, 4, 8))

    pixmap_bitmap = Qt6::QBitmap.from_pixmap(Qt6::QPixmap.from_image(source))
    Qt6::QRegion.new(pixmap_bitmap).bounding_rect.should eq(Qt6::Rect.new(0, 0, 4, 8))

    raw_bitmap = Qt6::QBitmap.from_data(
      Qt6::Size.new(8, 8),
      Bytes[
        0b00001111_u8,
        0b00001111_u8,
        0b00001111_u8,
        0b00001111_u8,
        0b00001111_u8,
        0b00001111_u8,
        0b00001111_u8,
        0b00001111_u8,
      ]
    )
    raw_bitmap.to_image.pixel_color(1, 1).should eq(Qt6::Color.new(0, 0, 0, 255))
    raw_bitmap.to_image.pixel_color(6, 1).should eq(Qt6::Color.new(255, 255, 255, 255))
    Qt6::QRegion.new(raw_bitmap).bounding_rect.should eq(Qt6::Rect.new(0, 0, 4, 8))

    transformed = raw_bitmap.transformed(Qt6::QTransform.new.scale(2.0, 1.0))
    transformed.size.should eq(Qt6::Size.new(16, 8))

    bitmap_path = File.join(Dir.tempdir, "crystal-qt6-bitmap-#{Process.pid}.png")
    bitmap.save(bitmap_path).should be_true
    loaded_bitmap = Qt6::QBitmap.from_file(bitmap_path)
    loaded_bitmap.null?.should be_false
    loaded_bitmap.size.should eq(Qt6::Size.new(8, 8))

    raw_bitmap.clear
    cleared_region = Qt6::QRegion.new(raw_bitmap)
    cleared_region.empty?.should be_true
    cleared_region.bounding_rect.should eq(Qt6::Rect.new(0, 0, 0, 0))
  end

  it "supports byte arrays, buffers, data-backed images, and mm-based pdf sizing" do
    app

    raw = Qt6::QByteArray.new(Bytes[1_u8, 2_u8, 3_u8, 4_u8])
    raw.size.should eq(4)
    raw.bytes.should eq(Bytes[1_u8, 2_u8, 3_u8, 4_u8])
    raw.clear
    raw.empty?.should be_true

    raw_pixels = Bytes[
      30_u8, 20_u8, 10_u8, 255_u8,
      60_u8, 50_u8, 40_u8, 255_u8,
      90_u8, 80_u8, 70_u8, 255_u8,
      120_u8, 110_u8, 100_u8, 255_u8,
    ]
    raw_image = Qt6::QImage.from_raw_data(raw_pixels, 2, 2, 8, Qt6::ImageFormat::ARGB32)
    raw_image.null?.should be_false
    raw_image.format.should eq(Qt6::ImageFormat::ARGB32)
    raw_image.bytes_per_line.should eq(8)
    raw_image.size_in_bytes.should eq(16)
    raw_image.bytes.should eq(raw_pixels)
    raw_image.pixel_color(0, 0).should eq(Qt6::Color.new(10, 20, 30, 255))
    raw_image.pixel_color(1, 1).should eq(Qt6::Color.new(100, 110, 120, 255))

    raw_copy = raw_image.copy
    raw_copy.set_pixel_color(0, 0, Qt6::Color.new(200, 10, 20, 255))
    raw_image.pixel_color(0, 0).should eq(Qt6::Color.new(10, 20, 30, 255))
    raw_copy.pixel_color(0, 0).should eq(Qt6::Color.new(200, 10, 20, 255))

    raw_region = raw_image.copy(Qt6::Rect.new(1, 0, 1, 2))
    raw_region.size.should eq(Qt6::Size.new(1, 2))
    raw_region.pixel_color(0, 0).should eq(Qt6::Color.new(40, 50, 60, 255))
    raw_region.pixel_color(0, 1).should eq(Qt6::Color.new(100, 110, 120, 255))

    premultiplied = raw_image.convert_to_format(Qt6::ImageFormat::ARGB32Premultiplied)
    premultiplied.format.should eq(Qt6::ImageFormat::ARGB32Premultiplied)
    premultiplied.bytes.size.should eq(premultiplied.size_in_bytes)

    grayscale = raw_image.convert_to_format(Qt6::ImageFormat::Grayscale8)
    grayscale.format.should eq(Qt6::ImageFormat::Grayscale8)
    grayscale.grayscale?.should be_true
    grayscale.depth.should eq(8)
    raw_image.has_alpha_channel?.should be_true
    raw_image.all_gray?.should be_false

    scaled = raw_image.scaled(4, 8, Qt6::AspectRatioMode::Keep, Qt6::TransformationMode::Smooth)
    scaled.size.should eq(Qt6::Size.new(4, 4))
    raw_image.scaled_to_width(6).size.should eq(Qt6::Size.new(6, 6))
    raw_image.scaled_to_height(8).size.should eq(Qt6::Size.new(8, 8))

    mirrored_horizontal = raw_image.mirrored(horizontal: true, vertical: false)
    mirrored_horizontal.pixel_color(0, 0).should eq(Qt6::Color.new(40, 50, 60, 255))
    mirrored_vertical = raw_image.mirrored(horizontal: false, vertical: true)
    mirrored_vertical.pixel_color(0, 0).should eq(Qt6::Color.new(70, 80, 90, 255))
    raw_image.rgb_swapped.pixel_color(0, 0).should eq(Qt6::Color.new(30, 20, 10, 255))

    inverted = raw_image.copy.invert_pixels
    inverted.pixel_color(0, 0).should eq(Qt6::Color.new(245, 235, 225, 255))

    image_scale = Qt6::QTransform.new.scale(2.0, 2.0)
    transformed_image = raw_image.transformed(image_scale)
    transformed_image.size.should eq(Qt6::Size.new(4, 4))

    image = Qt6::QImage.new(4, 4)
    image.fill(Qt6::Color.new(0, 0, 0, 0))
    image.set_pixel_color(1, 1, Qt6::Color.new(10, 20, 30))
    image.set_pixel_color(2, 2, Qt6::Color.new(200, 150, 100))

    byte_array = Qt6::QByteArray.new
    buffer = Qt6::QBuffer.new(byte_array)
    buffer.open(Qt6::IODeviceOpenMode::WriteOnly).should be_true
    image.save(buffer, "PNG").should be_true
    buffer.close
    buffer.open?.should be_false

    encoded = byte_array.bytes
    encoded.size.should be > 0

    image_from_data = Qt6::QImage.from_data(encoded, "PNG")
    image_from_data.null?.should be_false
    image_from_data.pixel_color(1, 1).should eq(Qt6::Color.new(10, 20, 30, 255))
    image_from_data.pixel_color(2, 2).should eq(Qt6::Color.new(200, 150, 100, 255))
    image.save_to_data("PNG").size.should be > 0

    pixmap_from_data = Qt6::QPixmap.from_data(encoded, "PNG")
    pixmap_from_data.null?.should be_false
    pixmap_from_data.depth.should be > 0
    pixmap_from_data.has_alpha_channel?.should be_true
    pixmap_from_data.to_image.pixel_color(2, 2).should eq(Qt6::Color.new(200, 150, 100, 255))
    pixmap_from_data.scaled(8, 4, Qt6::AspectRatioMode::Ignore, Qt6::TransformationMode::Smooth).size.should eq(Qt6::Size.new(8, 4))
    pixmap_from_data.scaled_to_width(8).size.should eq(Qt6::Size.new(8, 8))
    pixmap_from_data.scaled_to_height(6).size.should eq(Qt6::Size.new(6, 6))
    pixmap_from_data.transformed(image_scale).size.should eq(Qt6::Size.new(8, 8))
    pixmap_from_data.save_to_data("PNG").size.should be > 0

    implicit_buffer = Qt6::QBuffer.new
    implicit_buffer.open(Qt6::IODeviceOpenMode::WriteOnly).should be_true
    image.save(implicit_buffer, "PNG").should be_true
    implicit_buffer.close
    implicit_buffer.data.bytes.size.should be > 0

    pdf_path = File.join(Dir.tempdir, "crystal-qt6-mm-layout-#{Process.pid}.pdf")
    pdf = Qt6::QPdfWriter.new(pdf_path, title: "MM Layout", creator: "crystal-qt6 specs")
    pdf.set_page_size_millimeters(50.0, 40.0, Qt6::PageOrientation::Portrait)
    pdf.resolution = 96
    layout = Qt6::PageLayout.new(
      Qt6::PageSize.new(50.0, 40.0, Qt6::PageSizeUnit::Millimeter),
      Qt6::PageOrientation::Portrait,
      Qt6::MarginsF.new(5.0, 2.5, 5.0, 2.5)
    )
    pdf.page_layout = layout

    full_rect = pdf.page_layout_full_rect_points
    paint_rect = pdf.page_layout_paint_rect_points

    full_rect.width.should be > paint_rect.width
    full_rect.height.should be > paint_rect.height
    paint_rect.x.should be > 0.0
    paint_rect.y.should be > 0.0

    Qt6::QPainter.paint(pdf) do |painter|
      painter.draw_line(Qt6::PointF.new(0.0, 0.0), Qt6::PointF.new(20.0, 20.0))
    end

    pdf_header = begin
      pdf.release
      File.open(pdf_path) do |file|
        bytes = Bytes.new(5)
        file.read_fully(bytes)
        String.new(bytes)
      end
    end

    File.exists?(pdf_path).should be_true
    pdf_header.should eq("%PDF-")
  end

  it "supports url and filesystem utility wrappers" do
    app

    root_path = File.join(Dir.tempdir, "crystal-qt6-utils-#{Process.pid}")
    nested_relative = "maps/exports"
    nested_path = File.join(root_path, "maps", "exports")
    maps_path = File.join(root_path, "maps")
    file_path = File.join(root_path, "terrain.map")

    Dir.mkdir_p(root_path)
    File.write(file_path, "terrain")

    url = Qt6::QUrl.from_local_file(file_path)
    web_url = Qt6::QUrl.new("https://example.com/maps/view?id=7")
    dir = Qt6::QDir.new(root_path)
    file_info = Qt6::QFileInfo.new(file_path)

    url.valid?.should be_true
    url.local_file?.should be_true
    url.scheme.should eq("file")
    url.to_local_file.should eq(file_path)
    url.to_string.should contain(file_path)

    web_url.valid?.should be_true
    web_url.local_file?.should be_false
    web_url.scheme.should eq("https")
    web_url.path.should eq("/maps/view")

    dir.exists?.should be_true
    dir.path.should eq(root_path)
    dir.file_path("terrain.map").should eq(file_path)
    dir.absolute_file_path("terrain.map").should eq(file_path)
    dir.mkpath(nested_relative).should be_true

    Qt6::QDir.clean_path("#{root_path}/maps/../maps/exports").should eq(nested_path)
    Qt6::QDir.current_path.should eq(Dir.current)
    Qt6::QDir.home_path.should_not be_empty

    file_info.exists?.should be_true
    file_info.file?.should be_true
    file_info.dir?.should be_false
    file_info.file_name.should eq("terrain.map")
    file_info.base_name.should eq("terrain")
    file_info.suffix.should eq("map")
    file_info.absolute_file_path.should eq(file_path)
    file_info.absolute_path.should eq(root_path)
    file_info.directory.absolute_path.should eq(root_path)
    file_info.size.should eq(7_i64)
  ensure
    File.delete?(file_path) if file_path
    Dir.delete?(nested_path) if nested_path
    Dir.delete?(maps_path) if maps_path
    Dir.delete?(root_path) if root_path
  end

  it "supports file-backed qt io helpers" do
    app

    file_path = File.join(Dir.tempdir, "crystal-qt6-qfile-#{Process.pid}.txt")
    file = Qt6::QFile.new(file_path)

    Qt6::QFile.exists?(file_path).should be_false
    file.exists?.should be_false
    file.file_name.should eq(file_path)

    file.open(Qt6::IODeviceOpenMode::WriteOnly).should be_true
    file.open?.should be_true
    file.write("terrain\n").should eq(8_i64)
    file.flush.should be_true
    file.size.should eq(8_i64)
    file.close

    Qt6::QFile.exists?(file_path).should be_true
    file.exists?.should be_true

    file.open(Qt6::IODeviceOpenMode::ReadOnly).should be_true
    file.read_all.bytes.should eq("terrain\n".to_slice)
    file.close
    file.open?.should be_false

    renamed_path = File.join(Dir.tempdir, "crystal-qt6-qfile-renamed-#{Process.pid}.txt")
    file.file_name = renamed_path
    file.file_name.should eq(renamed_path)
    file.exists?.should be_false

    renamed = Qt6::QFile.new(renamed_path)
    renamed.open(Qt6::IODeviceOpenMode::WriteOnly).should be_true
    renamed.write(Bytes[1_u8, 2_u8, 3_u8, 4_u8]).should eq(4_i64)
    renamed.close
    renamed.size.should eq(4_i64)
    renamed.remove.should be_true
    renamed.exists?.should be_false
  ensure
    File.delete?(file_path) if file_path
    File.delete?(renamed_path) if renamed_path
  end

  it "supports shared qiodevice-style helpers for buffers and files" do
    app

    backing = Qt6::QByteArray.new
    buffer = Qt6::QBuffer.new(backing)

    buffer.open(Qt6::IODeviceOpenMode::ReadWrite).should be_true
    buffer.open?.should be_true
    buffer.position.should eq(0_i64)
    buffer.at_end?.should be_true
    buffer.write("roads").should eq(5_i64)
    buffer.size.should eq(5_i64)
    buffer.position.should eq(5_i64)
    buffer.at_end?.should be_true
    buffer.seek(0).should be_true
    buffer.position.should eq(0_i64)
    buffer.bytes_available.should eq(5_i64)
    buffer.at_end?.should be_false
    buffer.read_all.bytes.should eq("roads".to_slice)
    buffer.at_end?.should be_true
    buffer.seek(2).should be_true
    buffer.write("X").should eq(1_i64)
    buffer.close
    buffer.data.bytes.should eq("roXds".to_slice)

    file_path = File.join(Dir.tempdir, "crystal-qt6-iodevice-#{Process.pid}.txt")
    file = Qt6::QFile.new(file_path)
    file.open(Qt6::IODeviceOpenMode::WriteOnly).should be_true
    file.write("terrain\nroads").should eq(13_i64)
    file.position.should eq(13_i64)
    file.size.should eq(13_i64)
    file.close

    file.open(Qt6::IODeviceOpenMode::ReadOnly).should be_true
    file.position.should eq(0_i64)
    file.bytes_available.should eq(13_i64)
    file.at_end?.should be_false
    file.seek(8).should be_true
    file.position.should eq(8_i64)
    file.read_all.bytes.should eq("roads".to_slice)
    file.at_end?.should be_true
    file.close
  ensure
    File.delete?(file_path) if file_path
  end

  it "supports persisted settings stores" do
    app

    settings_path = File.join(Dir.tempdir, "crystal-qt6-settings-#{Process.pid}.ini")
    File.delete?(settings_path)

    settings = Qt6::QSettings.new(settings_path)
    settings.file_name.should eq(settings_path)
    settings.contains?("window/title").should be_false
    settings.value("window/title").should be_nil
    settings.value("window/missing", "fallback").should eq("fallback")

    settings.set_value("window/title", "Map Tool").should eq("Map Tool")
    settings.set_value("window/width", 1280).should eq(1280)
    settings.set_value("window/opacity", 0.85).should eq(0.85)
    settings.set_value("window/pinned", true).should eq(true)
    settings.sync

    File.exists?(settings_path).should be_true

    reopened = Qt6::QSettings.new(settings_path)
    reopened.contains?("window/title").should be_true
    reopened.value("window/title").should eq("Map Tool")
    reopened.value("window/width").should eq(1280)
    reopened.value("window/opacity").should eq(0.85)
    reopened.value("window/pinned").should eq(true)
    reopened.all_keys.sort.should eq(["window/opacity", "window/pinned", "window/title", "window/width"])

    reopened.remove("window/title").sync
    reopened.contains?("window/title").should be_false

    reopened.clear.sync
    reopened.all_keys.should be_empty
  ensure
    File.delete?(settings_path) if settings_path
  end

  it "supports desktop integration helpers" do
    app

    temp_path = Qt6::StandardPaths.writable_location(Qt6::StandardLocation::TempLocation)
    home_path = Qt6::StandardPaths.writable_location(Qt6::StandardLocation::HomeLocation)
    home_locations = Qt6::StandardPaths.standard_locations(Qt6::StandardLocation::HomeLocation)
    app_config_locations = Qt6::StandardPaths.standard_locations(Qt6::StandardLocation::AppConfigLocation)

    temp_path.should_not be_empty
    home_path.should_not be_empty
    home_locations.should contain(home_path)
    app_config_locations.should_not be_empty
    Qt6::StandardPaths.display_name(Qt6::StandardLocation::DocumentsLocation).should_not be_empty

    Qt6::DesktopServices.open_url(Qt6::QUrl.new).should be_false
  end

  it "loads standalone SVG files and exposes element bounds" do
    app
    svg_path = File.join(Dir.tempdir, "crystal-qt6-standalone-#{Process.pid}.svg")
    File.write(svg_path, <<-SVG)
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="12" viewBox="0 0 20 12">
        <rect id="box" x="2" y="1" width="6" height="4" fill="#ff0000"/>
        <rect id="accent" x="12" y="2" width="4" height="6" fill="#0000ff"/>
      </svg>
    SVG

    renderer = Qt6::QSvgRenderer.new(svg_path)
    renderer.load(svg_path).should be_true
    canvas = Qt6::QImage.new(20, 12)
    canvas.fill(Qt6::Color.new(255, 255, 255))
    element_canvas = Qt6::QImage.new(20, 12)
    element_canvas.fill(Qt6::Color.new(255, 255, 255))
    bounded_element_canvas = Qt6::QImage.new(10, 10)
    bounded_element_canvas.fill(Qt6::Color.new(255, 255, 255))

    Qt6::QPainter.paint(canvas) do |painter|
      renderer.render(painter)
    end

    Qt6::QPainter.paint(element_canvas) do |painter|
      renderer.render(painter, "box")
    end

    Qt6::QPainter.paint(bounded_element_canvas) do |painter|
      renderer.render(painter, "accent", Qt6::RectF.new(0.0, 0.0, 10.0, 10.0))
    end

    renderer.valid?.should be_true
    renderer.default_size.should eq(Qt6::Size.new(20, 12))
    renderer.view_box.should eq(Qt6::RectF.new(0.0, 0.0, 20.0, 12.0))
    renderer.element_exists?("box").should be_true
    renderer.element_exists?("accent").should be_true
    renderer.element_exists?("missing").should be_false
    renderer.bounds_on_element("box").should eq(Qt6::RectF.new(2.0, 1.0, 6.0, 4.0))
    renderer.bounds_on_element("accent").should eq(Qt6::RectF.new(12.0, 2.0, 4.0, 6.0))
    canvas.pixel_color(3, 2).should eq(Qt6::Color.new(255, 0, 0, 255))
    canvas.pixel_color(13, 3).should eq(Qt6::Color.new(0, 0, 255, 255))
    element_canvas.pixel_color(3, 2).should eq(Qt6::Color.new(255, 0, 0, 255))
    bounded_element_canvas.pixel_color(1, 1).should eq(Qt6::Color.new(0, 0, 255, 255))
  end

  it "supports clipboard access and file-backed image loading helpers" do
    application = app
    source_path = File.join(Dir.tempdir, "crystal-qt6-image-source-#{Process.pid}.png")
    source = Qt6::QImage.new(12, 10)
    source.fill(Qt6::Color.new(255, 255, 255))
    source.set_pixel_color(4, 3, Qt6::Color.new(12, 34, 56, 255))
    source.save(source_path).should be_true

    loaded_image = Qt6::QImage.from_file(source_path)
    loaded_image.null?.should be_false
    loaded_image.size.should eq(Qt6::Size.new(12, 10))
    loaded_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    reusable_image = Qt6::QImage.new(1, 1)
    reusable_image.load(source_path).should be_true
    reusable_image.size.should eq(Qt6::Size.new(12, 10))
    reusable_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    loaded_pixmap = Qt6::QPixmap.from_file(source_path)
    loaded_pixmap.null?.should be_false
    loaded_pixmap.size.should eq(Qt6::Size.new(12, 10))
    loaded_pixmap.to_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    reusable_pixmap = Qt6::QPixmap.new(1, 1)
    reusable_pixmap.load(source_path).should be_true
    reusable_pixmap.size.should eq(Qt6::Size.new(12, 10))
    reusable_pixmap.to_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    reader = Qt6::QImageReader.new(source_path)
    reader.file_name.should eq(source_path)
    reader.can_read?.should be_true
    reader.size.should eq(Qt6::Size.new(12, 10))
    reader.format.should eq("png")
    reader.auto_transform?.should be_false
    reader.auto_transform = true
    reader.auto_transform?.should be_true
    reader.format = "png"
    reader.format.should eq("png")

    reader_image = reader.read
    reader_image.null?.should be_false
    reader_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    second_reader = Qt6::QImageReader.new(source_path)
    reused_reader_image = Qt6::QImage.new(1, 1)
    second_reader.read(reused_reader_image).should be_true
    reused_reader_image.size.should eq(Qt6::Size.new(12, 10))
    reused_reader_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    encoded_png = source.save_to_data("PNG")
    buffer = Qt6::QBuffer.new
    buffer.open(Qt6::IODeviceOpenMode::ReadWrite).should be_true
    source.save(buffer, "PNG").should be_true
    buffer.position.should be > 0
    buffer.seek(0).should be_true
    buffer.peek(8).bytes.should eq(encoded_png[0, 8])
    buffer.read(8).bytes.should eq(encoded_png[0, 8])

    device_loaded_image = Qt6::QImage.new(1, 1)
    buffer.seek(0).should be_true
    device_loaded_image.load(buffer, "PNG").should be_true
    device_loaded_image.size.should eq(Qt6::Size.new(12, 10))
    device_loaded_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    buffer.seek(0).should be_true
    device_reader = Qt6::QImageReader.new(buffer, "png")
    device_reader.can_read?.should be_true
    device_reader.size.should eq(Qt6::Size.new(12, 10))
    device_reader.read.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    writable_formats = Qt6::QImageWriter.supported_image_formats.map(&.downcase)
    writable_mime_types = Qt6::QImageWriter.supported_mime_types
    writable_formats.includes?("png").should be_true
    writable_mime_types.includes?("image/png").should be_true

    writer_path = File.join(Dir.tempdir, "crystal-qt6-image-writer-#{Process.pid}.png")
    writer = Qt6::QImageWriter.new(writer_path, "png")
    writer.file_name.should eq(writer_path)
    writer.format.should eq("png")
    writer.quality = 90
    writer.quality.should eq(90)
    writer.compression = 1
    writer.compression.should eq(1)
    writer.optimized_write = true
    writer.optimized_write?.should be_true
    writer.progressive_scan_write = true
    writer.progressive_scan_write?.should be_true
    writer.can_write?.should be_true
    writer.write(source).should be_true

    writer_loaded_image = Qt6::QImageReader.new(writer_path).read
    writer_loaded_image.size.should eq(Qt6::Size.new(12, 10))
    writer_loaded_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    writer_buffer_bytes = Qt6::QByteArray.new
    writer_buffer = Qt6::QBuffer.new(writer_buffer_bytes)
    writer_buffer.open(Qt6::IODeviceOpenMode::WriteOnly).should be_true
    device_writer = Qt6::QImageWriter.new(writer_buffer, "png")
    device_writer.format.should eq("png")
    device_writer.can_write?.should be_true
    device_writer.write(source).should be_true
    writer_buffer.close
    writer_buffer_bytes.bytes.size.should be > 0

    device_writer_image = Qt6::QImage.from_data(writer_buffer_bytes.bytes, "PNG")
    device_writer_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    clipboard = application.clipboard
    clipboard.clear
    clipboard.text = "clipboard sample"
    application.process_events
    clipboard.has_text?.should be_true
    clipboard.text.should eq("clipboard sample")

    clipboard.image = loaded_image
    application.process_events
    clipboard.has_image?.should be_true
    clipboard_image = clipboard.image
    clipboard_image.null?.should be_false
    clipboard_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    clipboard.pixmap = loaded_pixmap
    application.process_events
    clipboard.has_pixmap?.should be_true
    clipboard_pixmap = clipboard.pixmap
    clipboard_pixmap.null?.should be_false
    clipboard_pixmap.to_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    mime_data = Qt6::MimeData.new
    mime_data.text = "mime sample"
    mime_data.html = "<b>mime sample</b>"
    mime_data.image = loaded_image
    mime_data.set_data("application/x-crystal-qt6-layer", Bytes[1_u8, 7_u8, 9_u8])
    mime_data.has_html?.should be_true
    mime_data.has_image?.should be_true
    mime_data.image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))
    mime_data.formats.should contain("application/x-crystal-qt6-layer")
    clipboard.mime_data = mime_data
    application.process_events

    clipboard_mime = clipboard.mime_data
    clipboard_mime.should_not be_nil
    clipboard_mime = clipboard_mime.not_nil!
    clipboard_mime.has_text?.should be_true
    clipboard_mime.text.should eq("mime sample")
    clipboard_mime.has_html?.should be_true
    clipboard_mime.html.should contain("mime sample")
    clipboard_mime.formats.should contain("application/x-crystal-qt6-layer")
    clipboard_mime.has_format?("application/x-crystal-qt6-layer").should be_true
    clipboard_mime.data("application/x-crystal-qt6-layer").should eq(Bytes[1_u8, 7_u8, 9_u8])
    clipboard.clear
  end

  it "loads SVG content from memory" do
    app
    svg_markup = <<-SVG
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="10" viewBox="0 0 18 10">
        <rect id="memory-box" x="4" y="2" width="6" height="4" fill="#00aa00"/>
      </svg>
    SVG

    renderer = Qt6::QSvgRenderer.from_data(svg_markup)
    renderer.valid?.should be_true
    renderer.default_size.should eq(Qt6::Size.new(18, 10))
    renderer.element_exists?("memory-box").should be_true

    image = Qt6::QImage.new(18, 10)
    image.fill(Qt6::Color.new(255, 255, 255))

    Qt6::QPainter.paint(image) do |painter|
      renderer.render(painter)
    end

    image.pixel_color(5, 3).should eq(Qt6::Color.new(0, 170, 0, 255))

    widget = Qt6::QSvgWidget.from_data(svg_markup)
    widget.size_hint.should eq(Qt6::Size.new(18, 10))
    widget.resize(18, 10)
    widget.show
    app.process_events

    preview = widget.grab
    preview.null?.should be_false
    preview.width.should be >= 18
    preview.height.should be >= 10
    widget.release
  end

  it "displays SVG content in QSvgWidget" do
    application = app
    svg_path = File.join(Dir.tempdir, "crystal-qt6-widget-#{Process.pid}.svg")
    File.write(svg_path, <<-SVG)
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="16" viewBox="0 0 24 16">
        <rect x="3" y="2" width="8" height="6" fill="#ff0000"/>
      </svg>
    SVG

    widget = Qt6::QSvgWidget.new(svg_path)
    renderer = widget.renderer

    renderer.valid?.should be_true
    renderer.default_size.should eq(Qt6::Size.new(24, 16))
    renderer.element_exists?("missing").should be_false
    widget.size_hint.should eq(Qt6::Size.new(24, 16))
    widget.resize(24, 16)
    widget.visible?.should be_false
    widget.show
    application.process_events
    widget.update
    application.process_events

    preview = widget.grab

    widget.visible?.should be_true
    widget.size.should eq(Qt6::Size.new(24, 16))
    preview.null?.should be_false
    preview.width.should be >= 24
    preview.height.should be >= 16

    render_probe = Qt6::QImage.new(24, 16)
    render_probe.fill(Qt6::Color.new(255, 255, 255))
    Qt6::QPainter.paint(render_probe) do |painter|
      renderer.render(painter)
    end
    render_probe.pixel_color(4, 3).should eq(Qt6::Color.new(255, 0, 0, 255))

    widget.release
  end

end
