require "./spec_helper"

describe Qt6 do
  it "renders into images and pixmaps with paths and transforms" do
    app
    image = Qt6::QImage.new(32, 32)
    image.fill(Qt6::Color.new(255, 255, 255))
    image.set_pixel_color(0, 0, Qt6::Color.new(1, 2, 3, 255))

    pen = Qt6::QPen.new(Qt6::Color.new(255, 0, 0), 3)
    brush = Qt6::QBrush.new(Qt6::Color.new(255, 0, 0))
    font = Qt6::QFont.new(point_size: 14, bold: true, italic: true)
    metrics = font.metrics
    metrics_f = font.metrics_f

    transform = Qt6::QTransform.new
    transform.translate(4, 5)

    path = Qt6::QPainterPath.new
    path.add_rect(Qt6::RectF.new(0.0, 0.0, 8.0, 8.0))
    moved_path = path.transformed(transform)
    translated_path = path.translated(10, 12)
    simplified_path = path.simplified

    curve_path = Qt6::QPainterPath.new
    curve_path.empty?.should be_true
    curve_path.move_to(Qt6::PointF.new(1.0, 2.0))
    curve_path.line_to(Qt6::PointF.new(5.0, 2.0))
    curve_path.quad_to(Qt6::PointF.new(8.0, 8.0), Qt6::PointF.new(10.0, 2.0))

    curve_path.empty?.should be_false
    curve_path.current_position.should eq(Qt6::PointF.new(10.0, 2.0))
    curve_path.element_count.should eq(5)
    curve_path[0].type.should eq(Qt6::PainterPathElementType::MoveTo)
    curve_path[0].point.should eq(Qt6::PointF.new(1.0, 2.0))
    curve_path[1].type.should eq(Qt6::PainterPathElementType::LineTo)
    curve_path[2].type.should eq(Qt6::PainterPathElementType::CurveTo)
    curve_path[3].type.should eq(Qt6::PainterPathElementType::CurveToData)
    curve_path[4].type.should eq(Qt6::PainterPathElementType::CurveToData)
    curve_path.control_point_rect.height.should be > curve_path.bounding_rect.height
    curve_path.fill_rule.should eq(Qt6::FillRule::OddEven)

    path.contains(Qt6::PointF.new(2.0, 2.0)).should be_true
    path.contains(Qt6::RectF.new(1.0, 1.0, 2.0, 2.0)).should be_true
    path.intersects?(Qt6::RectF.new(7.0, 7.0, 4.0, 4.0)).should be_true
    path.intersects?(Qt6::RectF.new(20.0, 20.0, 4.0, 4.0)).should be_false
    moved_path.bounding_rect.x.should eq(4.0)
    moved_path.bounding_rect.y.should eq(5.0)
    translated_path.bounding_rect.x.should eq(10.0)
    translated_path.bounding_rect.y.should eq(12.0)
    simplified_path.empty?.should be_false

    overlay_path = Qt6::QPainterPath.new
    overlay_path.add_rect(Qt6::RectF.new(10.0, 0.0, 4.0, 4.0))
    path.add_path(overlay_path)
    path.contains(Qt6::PointF.new(12.0, 2.0)).should be_true
    path.connect_path(curve_path)
    path.current_position.should eq(curve_path.current_position)

    winding_points = [
      Qt6::Point.new(0, 0),
      Qt6::Point.new(8, 0),
      Qt6::Point.new(8, 8),
      Qt6::Point.new(0, 8),
      Qt6::Point.new(0, 0),
      Qt6::Point.new(2, 2),
      Qt6::Point.new(6, 2),
      Qt6::Point.new(6, 6),
      Qt6::Point.new(2, 6),
      Qt6::Point.new(2, 2),
    ]
    winding_path = Qt6::QPainterPath.new
    winding_path.fill_rule = Qt6::FillRule::Winding
    winding_path.add_polygon(Qt6::QPolygon.new(winding_points))
    odd_even_path = Qt6::QPainterPath.new
    odd_even_path.fill_rule = Qt6::FillRule::OddEven
    odd_even_path.add_polygon(Qt6::QPolygon.new(winding_points))

    winding_path.contains(Qt6::PointF.new(3.0, 3.0)).should be_true
    odd_even_path.contains(Qt6::PointF.new(3.0, 3.0)).should be_false

    disposable_path = Qt6::QPainterPath.new
    disposable_path.add_ellipse(Qt6::RectF.new(0.0, 0.0, 6.0, 6.0))
    disposable_path.empty?.should be_false
    disposable_path.clear
    disposable_path.empty?.should be_true

    Qt6::QPainter.paint(image) do |painter|
      painter.active?.should be_true
      painter.antialiasing = false
      painter.pen = pen
      painter.brush = brush
      painter.font = font
      painter.draw_path(moved_path)
      painter.fill_rect(Qt6::RectF.new(20.0, 20.0, 4.0, 4.0), Qt6::Color.new(0, 0, 255))
      painter.draw_line(Qt6::PointF.new(0.0, 31.0), Qt6::PointF.new(31.0, 31.0))
      painter.draw_text(Qt6::PointF.new(1.0, 16.0), "qt6")
    end

    pixmap = Qt6::QPixmap.from_image(image)
    pixmap_canvas = Qt6::QPixmap.new(40, 40)
    pixmap_canvas.fill(Qt6::Color.new(0, 0, 0, 0))
    svg_path = File.join(Dir.tempdir, "crystal-qt6-render-scene-#{Process.pid}.svg")
    svg = Qt6::QSvgGenerator.new(svg_path, 40, 40, title: "Render Scene", description: "Generated by crystal-qt6 specs")
    svg.resolution = 96
    pdf_path = File.join(Dir.tempdir, "crystal-qt6-render-scene-#{Process.pid}.pdf")
    pdf = Qt6::QPdfWriter.new(pdf_path, title: "Render Scene PDF", creator: "crystal-qt6 specs")
    pdf.page_size_points = Qt6::Size.new(120, 120)
    pdf.resolution = 144

    Qt6::QPainter.paint(pixmap_canvas) do |painter|
      painter.draw_image(Qt6::PointF.new(2.0, 2.0), image)
      painter.draw_pixmap(Qt6::PointF.new(0.0, 0.0), pixmap)
    end

    Qt6::QPainter.paint(svg) do |painter|
      painter.antialiasing = false
      painter.pen = pen
      painter.brush = brush
      painter.font = font
      painter.draw_path(moved_path)
      painter.fill_rect(Qt6::RectF.new(20.0, 20.0, 4.0, 4.0), Qt6::Color.new(0, 0, 255))
      painter.draw_text(Qt6::PointF.new(1.0, 16.0), "qt6-svg")
    end

    Qt6::QPainter.paint(pdf) do |painter|
      painter.antialiasing = false
      painter.pen = pen
      painter.brush = brush
      painter.font = font
      painter.draw_path(moved_path)
      painter.fill_rect(Qt6::RectF.new(20.0, 20.0, 4.0, 4.0), Qt6::Color.new(0, 0, 255))
      painter.draw_text(Qt6::PointF.new(1.0, 16.0), "qt6-pdf")
      pdf.new_page.should be_true
      painter.reset_transform
      painter.draw_line(Qt6::PointF.new(0.0, 0.0), Qt6::PointF.new(30.0, 30.0))
    end

    svg_file_name = svg.file_name
    svg_size = svg.size
    svg_view_box = svg.view_box
    svg_title = svg.title
    svg_description = svg.description
    svg_resolution = svg.resolution
    pdf_file_name = pdf.file_name
    pdf_title = pdf.title
    pdf_creator = pdf.creator
    pdf_resolution = pdf.resolution

    svg_markup = begin
      svg.release
      File.read(svg_path)
    end

    svg_renderer = Qt6::QSvgRenderer.new(svg_path)
    svg_renderer.valid?.should be_true

    svg_canvas = Qt6::QImage.new(40, 40)
    svg_canvas.fill(Qt6::Color.new(255, 255, 255))
    Qt6::QPainter.paint(svg_canvas) do |painter|
      svg_renderer.render(painter, Qt6::RectF.new(0.0, 0.0, 40.0, 40.0))
    end

    svg_default_size = svg_renderer.default_size
    svg_render_view_box = svg_renderer.view_box

    pdf_header = begin
      pdf.release
      File.open(pdf_path) do |file|
        bytes = Bytes.new(5)
        file.read_fully(bytes)
        String.new(bytes)
      end
    end

    pixmap_image = pixmap_canvas.to_image
    image_path = File.join(Dir.tempdir, "crystal-qt6-render-image-#{Process.pid}.png")
    pixmap_path = File.join(Dir.tempdir, "crystal-qt6-render-pixmap-#{Process.pid}.png")
    text_bounds = metrics.bounding_rect("qt6")
    text_bounds_f = metrics_f.bounding_rect("qt6")

    pen.width.should eq(3.0)
    pen.color.should eq(Qt6::Color.new(255, 0, 0, 255))
    brush.color.should eq(Qt6::Color.new(255, 0, 0, 255))
    font.point_size.should eq(14)
    font.bold?.should be_true
    font.italic?.should be_true
    metrics.height.should be > 0
    metrics.ascent.should be > 0
    metrics.descent.should be >= 0
    metrics.horizontal_advance("qt6").should be > 0
    text_bounds.width.should be > 0.0
    text_bounds.height.should be > 0.0
    metrics_f.height.should be > 0.0
    metrics_f.ascent.should be > 0.0
    metrics_f.descent.should be >= 0.0
    metrics_f.horizontal_advance("qt6").should be > 0.0
    text_bounds_f.width.should be > 0.0
    text_bounds_f.height.should be > 0.0
    transform.map(Qt6::PointF.new(1.0, 1.0)).should eq(Qt6::PointF.new(5.0, 6.0))
    transform.map(Qt6::RectF.new(0.0, 0.0, 8.0, 8.0)).should eq(Qt6::RectF.new(4.0, 5.0, 8.0, 8.0))
    moved_path.bounding_rect.should eq(Qt6::RectF.new(4.0, 5.0, 8.0, 8.0))
    image.pixel_color(0, 0).should eq(Qt6::Color.new(1, 2, 3, 255))
    image.pixel_color(6, 7).should eq(Qt6::Color.new(255, 0, 0, 255))
    image.pixel_color(21, 21).should eq(Qt6::Color.new(0, 0, 255, 255))
    pixmap.width.should eq(32)
    pixmap.height.should eq(32)
    pixmap.null?.should be_false
    svg_file_name.should eq(svg_path)
    svg_size.should eq(Qt6::Size.new(40, 40))
    svg_view_box.should eq(Qt6::RectF.new(0.0, 0.0, 40.0, 40.0))
    svg_default_size.width.should be > 0
    svg_default_size.height.should be > 0
    svg_render_view_box.should eq(Qt6::RectF.new(0.0, 0.0, 40.0, 40.0))
    svg_title.should eq("Render Scene")
    svg_description.should eq("Generated by crystal-qt6 specs")
    svg_resolution.should eq(96)
    pdf_file_name.should eq(pdf_path)
    pdf_title.should eq("Render Scene PDF")
    pdf_creator.should eq("crystal-qt6 specs")
    pdf_resolution.should eq(144)
    pixmap_image.pixel_color(1, 1).should eq(Qt6::Color.new(255, 255, 255, 255))
    pixmap_image.pixel_color(6, 7).should eq(Qt6::Color.new(255, 0, 0, 255))
    image.save(image_path).should be_true
    pixmap.save(pixmap_path).should be_true
    File.exists?(image_path).should be_true
    File.exists?(pixmap_path).should be_true
    File.exists?(svg_path).should be_true
    File.exists?(pdf_path).should be_true
    svg_markup.includes?("<svg").should be_true
    svg_markup.includes?("<title>Render Scene</title>").should be_true
    svg_markup.includes?("Generated by crystal-qt6 specs").should be_true
    pdf_header.should eq("%PDF-")
    svg_canvas.pixel_color(6, 7).should eq(Qt6::Color.new(255, 0, 0, 255))
    svg_canvas.pixel_color(21, 21).should eq(Qt6::Color.new(0, 0, 255, 255))
  end

  it "supports richer painter state, polygons, strokers, and textured brushes" do
    app

    polygon = Qt6::QPolygonF.new([
      Qt6::PointF.new(0.0, 0.0),
      Qt6::PointF.new(4.0, 0.0),
      Qt6::PointF.new(4.0, 4.0),
      Qt6::PointF.new(0.0, 4.0),
    ])
    polygon << Qt6::PointF.new(0.0, 0.0)

    path = Qt6::QPainterPath.new
    path.add_polygon(polygon)

    map_transform = Qt6::QTransform.new
    map_transform.translate(6, 0)
    moved_path = map_transform.map(path)

    stroker = Qt6::QPainterPathStroker.new
    stroker.width = 2.0
    stroked_path = stroker.create_stroke(path)

    pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1)
    pen.style = Qt6::PenStyle::NoPen
    pen.cap_style = Qt6::PenCapStyle::RoundCap

    texture = Qt6::QPixmap.new(1, 1)
    texture.fill(Qt6::Color.new(220, 40, 40))
    textured_brush = Qt6::QBrush.new(texture)
    brush_transform = Qt6::QTransform.new
    brush_transform.translate(1, 0)
    textured_brush.transform = brush_transform

    source = Qt6::QImage.new(2, 2)
    source.fill(Qt6::Color.new(30, 60, 220))
    source_pixmap = Qt6::QPixmap.from_image(source)

    canvas = Qt6::QImage.new(12, 12)
    canvas.fill(Qt6::Color.new(0, 0, 0, 0))

    Qt6::QPainter.paint(canvas) do |painter|
      painter.smooth_pixmap_transform = true
      painter.pen = pen
      painter.brush = textured_brush
      painter.draw_polygon(polygon)

      painter.save
      painter.clip_path = moved_path
      painter.fill_rect(Qt6::RectF.new(0.0, 0.0, 12.0, 12.0), Qt6::Color.new(40, 220, 80))
      painter.restore

      painter.save
      painter.translate(8, 8)
      painter.opacity = 0.5
      painter.draw_image(0, 0, source)
      painter.restore

      painter.draw_pixmap(0, 8, source_pixmap)
      painter.composition_mode = Qt6::PainterCompositionMode::Clear
      painter.fill_rect(Qt6::RectF.new(8.0, 8.0, 1.0, 1.0), Qt6::Color.new(255, 255, 255))
      painter.composition_mode.should eq(Qt6::PainterCompositionMode::Clear)
      painter.composition_mode = Qt6::PainterCompositionMode::SourceOver
      painter.brush = Qt6::Color.new(70, 170, 240)
      painter.draw_ellipse(Qt6::PointF.new(10.0, 2.0), 1.0, 1.0)
    end

    polygon.size.should eq(5)
    polygon[2].should eq(Qt6::PointF.new(4.0, 4.0))
    polygon.bounding_rect.should eq(Qt6::RectF.new(0.0, 0.0, 4.0, 4.0))
    path.empty?.should be_false
    path.contains(Qt6::PointF.new(2.0, 2.0)).should be_true
    path.contains(Qt6::PointF.new(5.5, 2.0)).should be_false
    moved_path.bounding_rect.should eq(Qt6::RectF.new(6.0, 0.0, 4.0, 4.0))
    stroked_path.contains(Qt6::PointF.new(0.2, 2.0)).should be_true
    pen.style.should eq(Qt6::PenStyle::NoPen)
    pen.cap_style.should eq(Qt6::PenCapStyle::RoundCap)
    textured_brush.transform.map(Qt6::PointF.new(1.0, 1.0)).should eq(Qt6::PointF.new(2.0, 1.0))

    canvas.pixel_color(2, 2).should eq(Qt6::Color.new(220, 40, 40, 255))
    canvas.pixel_color(7, 2).should eq(Qt6::Color.new(40, 220, 80, 255))
    canvas.pixel_color(5, 2).should eq(Qt6::Color.new(0, 0, 0, 0))
    canvas.pixel_color(8, 8).should eq(Qt6::Color.new(0, 0, 0, 0))
    faded = canvas.pixel_color(9, 9)
    faded.red.should eq(30)
    faded.green.should eq(60)
    faded.blue.should eq(220)
    faded.alpha.should eq(127)
    canvas.pixel_color(0, 8).should eq(Qt6::Color.new(30, 60, 220, 255))
    canvas.pixel_color(10, 2).should eq(Qt6::Color.new(70, 170, 240, 255))

    deep_source = Qt6::QImage.new(4, 4)
    deep_source.fill(Qt6::Color.new(0, 0, 0, 0))
    deep_source.set_pixel_color(2, 2, Qt6::Color.new(240, 30, 30))
    deep_pixmap = Qt6::QPixmap.from_image(deep_source)
    deep_canvas = Qt6::QImage.new(12, 12)
    deep_canvas.fill(Qt6::Color.new(0, 0, 0, 0))

    painter = Qt6::QPainter.new(deep_canvas)
    painter.active?.should be_true
    painter.antialiasing = false
    painter.draw_image(
      Qt6::RectF.new(0.0, 0.0, 4.0, 4.0),
      deep_source,
      Qt6::RectF.new(2.0, 2.0, 1.0, 1.0)
    )
    painter.draw_pixmap(
      Qt6::RectF.new(4.0, 0.0, 4.0, 4.0),
      deep_pixmap,
      Qt6::RectF.new(2.0, 2.0, 1.0, 1.0)
    )
    painter.clip_rect = Qt6::RectF.new(0.0, 4.0, 2.0, 2.0)
    painter.fill_rect(Qt6::RectF.new(0.0, 4.0, 4.0, 4.0), Qt6::QBrush.new(Qt6::Color.new(30, 220, 90)))
    painter.clipping = false
    painter.save
    painter.translate(12, 12)
    painter.rotate(180)
    painter.fill_rect(Qt6::RectF.new(0.0, 0.0, 2.0, 2.0), Qt6::Color.new(80, 40, 220))
    painter.restore
    painter.draw_point(Qt6::PointF.new(8.0, 8.0))
    painter.end.should be_true
    painter.active?.should be_false
    painter.release

    deep_canvas.pixel_color(0, 0).should eq(Qt6::Color.new(240, 30, 30, 255))
    deep_canvas.pixel_color(4, 0).should eq(Qt6::Color.new(240, 30, 30, 255))
    deep_canvas.pixel_color(1, 5).should eq(Qt6::Color.new(30, 220, 90, 255))
    deep_canvas.pixel_color(3, 5).should eq(Qt6::Color.new(0, 0, 0, 0))
    deep_canvas.pixel_color(10, 10).should eq(Qt6::Color.new(80, 40, 220, 255))
    deep_canvas.pixel_color(8, 8).should eq(Qt6::Color.new(0, 0, 0, 255))
  end

  it "supports brush styles, textures, and opacity queries" do
    app

    brush = Qt6::QBrush.new(Qt6::BrushStyle::Dense4Pattern)
    brush.style.should eq(Qt6::BrushStyle::Dense4Pattern)
    brush.opaque?.should be_false

    texture_image = Qt6::QImage.new(2, 2)
    texture_image.fill(Qt6::Color.new(10, 20, 30))
    texture_image.set_pixel_color(1, 1, Qt6::Color.new(200, 150, 100))
    brush.texture_image = texture_image

    brush.style.should eq(Qt6::BrushStyle::TexturePattern)
    copied_texture_image = brush.texture_image
    copied_texture_image.size.should eq(Qt6::Size.new(2, 2))
    copied_texture_image.pixel_color(1, 1).should eq(Qt6::Color.new(200, 150, 100, 255))

    texture_pixmap = brush.texture
    texture_pixmap.size.should eq(Qt6::Size.new(2, 2))
    texture_pixmap.to_image.pixel_color(1, 1).should eq(Qt6::Color.new(200, 150, 100, 255))

    replacement = Qt6::QPixmap.new(2, 2)
    replacement.fill(Qt6::Color.new(40, 90, 160))
    brush.texture = replacement
    brush.style.should eq(Qt6::BrushStyle::TexturePattern)
    brush.texture.to_image.pixel_color(0, 0).should eq(Qt6::Color.new(40, 90, 160, 255))

    brush.style = Qt6::BrushStyle::DiagCrossPattern
    brush.style.should eq(Qt6::BrushStyle::DiagCrossPattern)

    solid = Qt6::QBrush.new(Qt6::Color.new(1, 2, 3, 255))
    translucent = Qt6::QBrush.new(Qt6::Color.new(1, 2, 3, 100))
    solid.opaque?.should be_true
    translucent.opaque?.should be_false
  end

  it "supports abstract graphics shape items" do
    app

    parent = Qt6::AbstractGraphicsShapeItem.new
    child = Qt6::AbstractGraphicsShapeItem.new(parent)
    pen = Qt6::QPen.new(Qt6::Color.new(12, 34, 56), 2.5)
    brush = Qt6::QBrush.new(Qt6::Color.new(78, 90, 102, 180))

    child.pen = pen
    child.brush = brush
    child.visible = false
    child.visible?.should be_false
    child.show
    child.enabled = false
    child.enabled?.should be_false
    child.enabled = true
    child.opacity = 0.6

    child.parent_item.not_nil!.to_unsafe.should eq(parent.to_unsafe)
    child.pen.color.should eq(Qt6::Color.new(12, 34, 56, 255))
    child.pen.width.should eq(2.5)
    child.brush.color.should eq(Qt6::Color.new(78, 90, 102, 180))
    child.visible?.should be_true
    child.enabled?.should be_true
    child.opacity.should eq(0.6)
    child.obscured_by?(parent).should be_false
    child.opaque_area.empty?.should be_true
    child.opaque_area.element_count.should eq(0)

    parent.release
  end

  it "supports richer graphics item state and transforms" do
    app

    parent = Qt6::AbstractGraphicsShapeItem.new
    child = Qt6::GraphicsEllipseItem.new(Qt6::RectF.new(0.0, 0.0, 12.0, 8.0), parent)

    child.flags = Qt6::GraphicsItemFlag::ItemIsMovable | Qt6::GraphicsItemFlag::ItemIsSelectable
    child.set_flag(Qt6::GraphicsItemFlag::ItemClipsToShape)
    child.selected = true
    child.accept_drops = true
    child.opacity = 0.5
    child.set_pos(4, 6)
    child.move_by(1, 2)
    child.rotation = 30
    child.scale = 1.25
    child.transform_origin_point = Qt6::PointF.new(2.0, 3.0)
    child.z_value = 7.5
    child.cache_mode = Qt6::GraphicsItemCacheMode::DeviceCoordinateCache

    transform = Qt6::QTransform.new
    transform.translate(3, 4)
    child.set_transform(transform)

    child.parent_item.not_nil!.to_unsafe.should eq(parent.to_unsafe)
    child.top_level_item.not_nil!.to_unsafe.should eq(parent.to_unsafe)
    child.flags.includes?(Qt6::GraphicsItemFlag::ItemIsMovable).should be_true
    child.flags.includes?(Qt6::GraphicsItemFlag::ItemIsSelectable).should be_true
    child.flags.includes?(Qt6::GraphicsItemFlag::ItemClipsToShape).should be_true
    child.selected?.should be_true
    child.accept_drops?.should be_true
    child.effective_opacity.should eq(0.5)
    child.pos.should eq(Qt6::PointF.new(5.0, 8.0))
    child.x.should eq(5.0)
    child.y.should eq(8.0)
    child.scene_pos.should_not eq(Qt6::PointF.new(0.0, 0.0))
    child.rotation.should eq(30.0)
    child.scale.should eq(1.25)
    child.transform_origin_point.should eq(Qt6::PointF.new(2.0, 3.0))
    child.z_value.should eq(7.5)
    child.cache_mode.should eq(Qt6::GraphicsItemCacheMode::DeviceCoordinateCache)
    child.transform.map(Qt6::PointF.new(0.0, 0.0)).should eq(Qt6::PointF.new(3.0, 4.0))
    child.scene_transform.map(Qt6::PointF.new(0.0, 0.0)).should_not eq(Qt6::PointF.new(0.0, 0.0))
    child.scene_bounding_rect.width.should be > 0.0
    child.scene_bounding_rect.height.should be > 0.0
    child.widget?.should be_false
    child.window?.should be_false
    child.panel?.should be_false

    widget = Qt6::GraphicsWidget.new
    widget.set_pos(9, 11)
    widget.rotation = 15
    widget.scale = 1.5
    widget.z_value = 2.0
    widget.set_flag(Qt6::GraphicsItemFlag::ItemIsSelectable)
    widget.selected = true
    widget.widget?.should be_true
    widget.pos.should eq(Qt6::PointF.new(9.0, 11.0))
    widget.rotation.should eq(15.0)
    widget.scale.should eq(1.5)
    widget.z_value.should eq(2.0)
    widget.selected?.should be_true

    parent.release
    widget.release
  end

  it "supports graphics rotations and transformation lists" do
    app

    item = Qt6::GraphicsRectItem.new(0, 0, 12, 8)
    widget = Qt6::GraphicsWidget.new
    rotation = Qt6::GraphicsRotation.new
    widget_rotation_source = Qt6::GraphicsRotation.new
    origin_changes = 0
    angle_changes = 0
    axis_changes = 0

    rotation.on_origin_changed { origin_changes += 1 }
    rotation.on_angle_changed { angle_changes += 1 }
    rotation.on_axis_changed { axis_changes += 1 }

    rotation.origin = Qt6::Vector3D.new(1.0, 2.0, 3.0)
    rotation.angle = 45
    rotation.axis = Qt6::Vector3D.new(0.0, 1.0, 0.0)
    rotation.set_axis(Qt6::Axis::XAxis)

    item.transformations = [rotation]
    widget_rotation_source.angle = 12
    widget_rotation_source.axis = Qt6::Axis::YAxis

    widget.transformations = [widget_rotation_source]

    item_rotation = item.transformations.first.as(Qt6::GraphicsRotation)
    widget_rotation = widget.transformations.first.as(Qt6::GraphicsRotation)

    rotation.origin.should eq(Qt6::Vector3D.new(1.0, 2.0, 3.0))
    rotation.angle.should eq(45.0)
    rotation.axis.should eq(Qt6::Vector3D.new(1.0, 0.0, 0.0))
    origin_changes.should eq(1)
    angle_changes.should eq(1)
    axis_changes.should eq(2)
    item.transformations.size.should eq(1)
    widget.transformations.size.should eq(1)
    item_rotation.to_unsafe.should eq(rotation.to_unsafe)
    widget_rotation.to_unsafe.should eq(widget_rotation_source.to_unsafe)
    widget_rotation.angle.should eq(12.0)
    widget_rotation.axis.should eq(Qt6::Vector3D.new(0.0, 1.0, 0.0))

    widget.transformations = [] of Qt6::GraphicsTransform
    widget.transformations.should be_empty

    # Qt expects graphics transforms to outlive graphics widgets that used them.
    rotation.release
    widget_rotation_source.release
    item.release
    widget.release
  end

  it "supports graphics scales" do
    app

    item = Qt6::GraphicsRectItem.new(0, 0, 12, 8)
    scale = Qt6::GraphicsScale.new
    origin_changes = 0
    x_scale_changes = 0
    y_scale_changes = 0
    z_scale_changes = 0
    scale_changes = 0

    scale.on_origin_changed { origin_changes += 1 }
    scale.on_x_scale_changed { x_scale_changes += 1 }
    scale.on_y_scale_changed { y_scale_changes += 1 }
    scale.on_z_scale_changed { z_scale_changes += 1 }
    scale.on_scale_changed { scale_changes += 1 }

    scale.origin = Qt6::Vector3D.new(2.0, 3.0, 4.0)
    scale.x_scale = 1.5
    scale.set_y_scale(2.0)
    scale.set_z_scale(0.75)
    item.transformations = [scale]

    item_scale = item.transformations.first.as(Qt6::GraphicsScale)

    scale.origin.should eq(Qt6::Vector3D.new(2.0, 3.0, 4.0))
    scale.x_scale.should eq(1.5)
    scale.y_scale.should eq(2.0)
    scale.z_scale.should eq(0.75)
    origin_changes.should eq(1)
    x_scale_changes.should eq(1)
    y_scale_changes.should eq(1)
    z_scale_changes.should eq(1)
    scale_changes.should eq(3)
    item.transformations.size.should eq(1)
    item_scale.to_unsafe.should eq(scale.to_unsafe)

    scale.release
    item.release
  end

  it "supports graphics scenes" do
    app

    scene = Qt6::GraphicsScene.new(Qt6::RectF.new(0.0, 0.0, 40.0, 30.0))
    view = Qt6::GraphicsView.new
    rect_pen = Qt6::QPen.new(Qt6::Color.new(180, 20, 40), 2.0)
    rect_brush = Qt6::QBrush.new(Qt6::Color.new(220, 80, 90, 220))
    ellipse_brush = Qt6::QBrush.new(Qt6::Color.new(40, 150, 90, 220))
    font = Qt6::QFont.new("Courier", 12)
    palette = Qt6::QPalette.new
    scene_rect_changes = 0
    selection_changes = 0

    scene.on_scene_rect_changed { |rect| scene_rect_changes += 1; rect.should eq(Qt6::RectF.new(0.0, 0.0, 60.0, 45.0)) }
    scene.on_selection_changed { selection_changes += 1 }

    view.scene = scene
    view.scene.not_nil!.to_unsafe.should eq(scene.to_unsafe)
    scene.views.size.should eq(1)
    scene.views.first.to_unsafe.should eq(view.to_unsafe)

    scene.scene_rect = Qt6::RectF.new(0.0, 0.0, 60.0, 45.0)
    scene.bsp_tree_depth = 3
    scene.bsp_tree_depth.should eq(3)
    scene.item_index_method = Qt6::GraphicsSceneItemIndexMethod::NoIndex
    scene.background_brush = Qt6::QBrush.new(Qt6::Color.new(245, 245, 248))
    scene.foreground_brush = Qt6::QBrush.new(Qt6::Color.new(10, 10, 10, 24))
    palette.set_color(Qt6::ColorRole::Window, Qt6::Color.new(230, 230, 235))
    scene.font = font
    scene.palette = palette
    scene.sticky_focus = true
    scene.minimum_render_size = 0.5
    scene.focus_on_touch = false

    panel = Qt6::GraphicsWidget.new
    panel.set_geometry(1, 1, 12, 10)
    panel.set_flag(Qt6::GraphicsItemFlag::ItemIsFocusable)
    scene.add_item(panel)

    ellipse = Qt6::GraphicsEllipseItem.new(6, 5, 12, 10)
    ellipse.brush = ellipse_brush
    ellipse.set_flag(Qt6::GraphicsItemFlag::ItemIsSelectable)
    scene.add_item(ellipse)
    ellipse.selected = true

    rect = scene.add_rect(Qt6::RectF.new(2.0, 2.0, 18.0, 12.0), rect_pen, rect_brush)

    scene.item_index_method.should eq(Qt6::GraphicsSceneItemIndexMethod::NoIndex)
    scene.scene_rect.should eq(Qt6::RectF.new(0.0, 0.0, 60.0, 45.0))
    scene.background_brush.color.should eq(Qt6::Color.new(245, 245, 248, 255))
    scene.foreground_brush.color.should eq(Qt6::Color.new(10, 10, 10, 24))
    scene.font.point_size.should eq(12)
    scene.palette.color(Qt6::ColorRole::Window).should eq(Qt6::Color.new(230, 230, 235, 255))
    scene.sticky_focus?.should be_true
    scene.minimum_render_size.should eq(0.5)
    scene.focus_on_touch?.should be_false
    scene_rect_changes.should eq(1)
    selection_changes.should be >= 1

    scene.active_panel = panel
    scene.active_window = panel
    scene.set_focus_item(panel, Qt6::FocusReason::OtherFocusReason)
    scene.focus_item.not_nil!.to_unsafe.should eq(panel.graphics_item_handle)
    scene.mouse_grabber_item.should be_nil

    all_items = scene.items
    all_items.size.should eq(3)
    all_items.any? { |item| item.to_unsafe == panel.graphics_item_handle }.should be_true
    all_items.any? { |item| item.to_unsafe == ellipse.to_unsafe }.should be_true
    all_items.any? { |item| item.to_unsafe == rect.to_unsafe }.should be_true

    point_items = scene.items(Qt6::PointF.new(8.0, 8.0))
    point_items.any? { |item| item.to_unsafe == rect.to_unsafe }.should be_true

    path = Qt6::QPainterPath.new
    path.add_rect(Qt6::RectF.new(0.0, 0.0, 24.0, 20.0))
    path_items = scene.items(path)
    path_items.any? { |item| item.to_unsafe == ellipse.to_unsafe }.should be_true

    scene.items(Qt6::RectF.new(0.0, 0.0, 24.0, 20.0), Qt6::GraphicsItemSelectionMode::IntersectsItemBoundingRect).size.should eq(3)
    scene.colliding_items(rect).any? { |item| item.to_unsafe == ellipse.to_unsafe }.should be_true
    scene.item_at(Qt6::PointF.new(3.0, 3.0)).should_not be_nil
    scene.selected_items.any? { |item| item.to_unsafe == ellipse.to_unsafe }.should be_true
    scene.items_bounding_rect.width.should be > 15.0
    scene.items_bounding_rect.height.should be > 10.0
    scene.style.should_not be_nil

    image = Qt6::QImage.new(80, 60)
    image.fill(Qt6::Color.new(255, 255, 255))
    Qt6::QPainter.paint(image) do |painter|
      scene.render(painter, Qt6::RectF.new(0.0, 0.0, 80.0, 60.0), scene.scene_rect, Qt6::AspectRatioMode::Keep)
    end
    image.pixel_color(8, 8).should_not eq(Qt6::Color.new(255, 255, 255, 255))

    scene.update(Qt6::RectF.new(0.0, 0.0, 12.0, 12.0))
    scene.invalidate(Qt6::RectF.new(0.0, 0.0, 12.0, 12.0), Qt6::GraphicsSceneLayer::ItemLayer | Qt6::GraphicsSceneLayer::BackgroundLayer)
    scene.advance
    scene.clear_selection
    scene.selected_items.should be_empty

    panel.release
    ellipse.release
    view.release
    scene.release
  end

  it "supports graphics objects" do
    app

    parent = Qt6::GraphicsObject.new
    child = Qt6::GraphicsObject.new(parent)
    effect = Qt6::GraphicsBlurEffect.new
    destroyed = false
    parent_changed = 0
    opacity_changed = 0
    visible_changed = 0
    enabled_changed = 0
    x_changed = 0
    y_changed = 0
    z_changed = 0
    rotation_changed = 0
    scale_changed = 0

    child.on_destroyed { destroyed = true }
    child.on_parent_changed { parent_changed += 1 }
    child.on_opacity_changed { opacity_changed += 1 }
    child.on_visible_changed { visible_changed += 1 }
    child.on_enabled_changed { enabled_changed += 1 }
    child.on_x_changed { x_changed += 1 }
    child.on_y_changed { y_changed += 1 }
    child.on_z_changed { z_changed += 1 }
    child.on_rotation_changed { rotation_changed += 1 }
    child.on_scale_changed { scale_changed += 1 }

    child.parent_item.not_nil!.to_unsafe.should eq(parent.to_unsafe)
    child.parent_object.not_nil!.to_unsafe.should eq(parent.to_unsafe)
    child.graphics_effect = effect
    child.graphics_effect.not_nil!.to_unsafe.should eq(effect.to_unsafe)
    child.grab_gesture(Qt6::GestureType::TapGesture)
    child.ungrab_gesture(Qt6::GestureType::TapGesture)
    child.signals_blocked?.should be_false
    child.block_signals = true
    child.signals_blocked?.should be_true
    child.opacity = 0.6
    child.block_signals = false
    child.opacity = 0.7
    child.visible = false
    child.enabled = false
    child.x = 11
    child.y = 12
    child.z_value = 4
    child.rotation = 25
    child.scale = 1.5

    parent_changed.should eq(0)
    opacity_changed.should eq(1)
    visible_changed.should eq(1)
    enabled_changed.should eq(1)
    x_changed.should eq(1)
    y_changed.should eq(1)
    z_changed.should eq(1)
    rotation_changed.should eq(1)
    scale_changed.should eq(1)

    filter = Qt6::EventFilter.new
    child.install_event_filter(filter)
    child.remove_event_filter(filter)

    parent.release
    destroyed.should be_true
  end

  it "supports graphics rect items" do
    app

    parent = Qt6::AbstractGraphicsShapeItem.new
    rect = Qt6::GraphicsRectItem.new(Qt6::RectF.new(0.0, 0.0, 20.0, 10.0), parent)
    pen = Qt6::QPen.new(Qt6::Color.new(120, 30, 40), 2.0)
    brush = Qt6::QBrush.new(Qt6::Color.new(50, 130, 210))

    rect.pen = pen
    rect.brush = brush

    rect.parent_item.not_nil!.to_unsafe.should eq(parent.to_unsafe)
    rect.rect.should eq(Qt6::RectF.new(0.0, 0.0, 20.0, 10.0))
    rect.contains?(Qt6::PointF.new(10.0, 5.0)).should be_true
    rect.contains?(Qt6::PointF.new(24.0, 5.0)).should be_false
    rect.opaque_area.empty?.should be_false
    rect.bounding_rect.width.should be > rect.rect.width
    rect.bounding_rect.height.should be > rect.rect.height

    rect.set_rect(2, 3, 18, 12)

    rect.rect.should eq(Qt6::RectF.new(2.0, 3.0, 18.0, 12.0))
    rect.bounding_rect.width.should be > 0.0
    rect.bounding_rect.height.should be > 0.0

    parent.release
  end

  it "supports graphics ellipse items" do
    app

    parent = Qt6::AbstractGraphicsShapeItem.new
    ellipse = Qt6::GraphicsEllipseItem.new(Qt6::RectF.new(0.0, 0.0, 20.0, 10.0), parent)
    pen = Qt6::QPen.new(Qt6::Color.new(140, 20, 30), 2.0)
    brush = Qt6::QBrush.new(Qt6::Color.new(40, 120, 200))

    ellipse.pen = pen
    ellipse.brush = brush

    ellipse.parent_item.not_nil!.to_unsafe.should eq(parent.to_unsafe)
    ellipse.rect.should eq(Qt6::RectF.new(0.0, 0.0, 20.0, 10.0))
    ellipse.contains?(Qt6::PointF.new(10.0, 5.0)).should be_true
    ellipse.contains?(Qt6::PointF.new(24.0, 5.0)).should be_false
    ellipse.opaque_area.empty?.should be_false
    ellipse.bounding_rect.width.should be > ellipse.rect.width
    ellipse.bounding_rect.height.should be > ellipse.rect.height

    ellipse.set_rect(2, 3, 18, 12)
    ellipse.start_angle = 16 * 90
    ellipse.span_angle = 16 * 180

    ellipse.rect.should eq(Qt6::RectF.new(2.0, 3.0, 18.0, 12.0))
    ellipse.start_angle.should eq(16 * 90)
    ellipse.span_angle.should eq(16 * 180)
    ellipse.bounding_rect.width.should be > 0.0
    ellipse.bounding_rect.height.should be > 0.0

    parent.release
  end

  it "supports graphics line items" do
    app

    parent = Qt6::AbstractGraphicsShapeItem.new
    line = Qt6::GraphicsLineItem.new(Qt6::LineF.new(1, 2, 21, 2), parent)
    pen = Qt6::QPen.new(Qt6::Color.new(220, 40, 60), 3.0)

    line.pen = pen

    line.parent_item.not_nil!.to_unsafe.should eq(parent.to_unsafe)
    line.pen.color.should eq(Qt6::Color.new(220, 40, 60, 255))
    line.pen.width.should eq(3.0)
    line.line.should eq(Qt6::LineF.new(1.0, 2.0, 21.0, 2.0))
    line.line.length.should eq(20.0)
    line.contains?(Qt6::PointF.new(10.0, 2.0)).should be_true
    line.contains?(Qt6::PointF.new(10.0, 8.0)).should be_false
    line.obscured_by?(parent).should be_false
    line.opaque_area.empty?.should be_true
    line.bounding_rect.width.should be > 20.0
    line.bounding_rect.height.should be > 0.0

    line.set_line(3, 4, 18, 12)

    line.line.should eq(Qt6::LineF.new(3.0, 4.0, 18.0, 12.0))
    line.line.length.should be > 16.0
    line.bounding_rect.width.should be > 0.0
    line.bounding_rect.height.should be > 0.0

    parent.release
  end

  it "supports graphics path items" do
    app

    parent = Qt6::AbstractGraphicsShapeItem.new
    original_path = Qt6::QPainterPath.new
    original_path.add_rect(Qt6::RectF.new(0.0, 0.0, 18.0, 10.0))
    item = Qt6::GraphicsPathItem.new(original_path, parent)
    pen = Qt6::QPen.new(Qt6::Color.new(180, 30, 80), 2.0)
    brush = Qt6::QBrush.new(Qt6::Color.new(30, 160, 200, 220))

    item.pen = pen
    item.brush = brush

    item.parent_item.not_nil!.to_unsafe.should eq(parent.to_unsafe)
    item.path.bounding_rect.should eq(Qt6::RectF.new(0.0, 0.0, 18.0, 10.0))
    item.path.element_count.should eq(original_path.element_count)
    item.pen.color.should eq(Qt6::Color.new(180, 30, 80, 255))
    item.pen.width.should eq(2.0)
    item.brush.color.should eq(Qt6::Color.new(30, 160, 200, 220))
    item.contains?(Qt6::PointF.new(6.0, 4.0)).should be_true
    item.contains?(Qt6::PointF.new(22.0, 4.0)).should be_false
    item.obscured_by?(parent).should be_false
    item.bounding_rect.width.should be > item.path.bounding_rect.width
    item.bounding_rect.height.should be > item.path.bounding_rect.height

    replacement_path = Qt6::QPainterPath.new
    replacement_path.add_ellipse(Qt6::RectF.new(2.0, 3.0, 12.0, 9.0))
    item.set_path(replacement_path)

    item.path.bounding_rect.should eq(Qt6::RectF.new(2.0, 3.0, 12.0, 9.0))
    item.path.element_count.should eq(replacement_path.element_count)
    item.contains?(Qt6::PointF.new(8.0, 7.0)).should be_true
    item.contains?(Qt6::PointF.new(0.0, 0.0)).should be_false
    item.bounding_rect.width.should be > 0.0
    item.bounding_rect.height.should be > 0.0

    parent.release
  end

  it "supports graphics pixmap items" do
    app

    parent = Qt6::AbstractGraphicsShapeItem.new
    pixmap = Qt6::QPixmap.new(8, 6)
    pixmap.fill(Qt6::Color.new(220, 60, 90))
    item = Qt6::GraphicsPixmapItem.new(pixmap, parent)
    replacement = Qt6::QPixmap.new(12, 9)
    replacement.fill(Qt6::Color.new(40, 120, 220))

    item.parent_item.not_nil!.to_unsafe.should eq(parent.to_unsafe)
    item.pixmap.width.should eq(8)
    item.pixmap.height.should eq(6)
    item.set_transformation_mode(Qt6::TransformationMode::Smooth)
    item.set_shape_mode(Qt6::GraphicsPixmapItemShapeMode::BoundingRectShape)
    item.set_offset(3, 4)

    item.transformation_mode.should eq(Qt6::TransformationMode::Smooth)
    item.shape_mode.should eq(Qt6::GraphicsPixmapItemShapeMode::BoundingRectShape)
    item.offset.should eq(Qt6::PointF.new(3.0, 4.0))
    item.bounding_rect.should eq(Qt6::RectF.new(3.0, 4.0, 8.0, 6.0))
    item.contains?(Qt6::PointF.new(4.0, 5.0)).should be_true
    item.contains?(Qt6::PointF.new(2.0, 2.0)).should be_false
    item.obscured_by?(parent).should be_false
    item.opaque_area.bounding_rect.width.should be > 0.0
    item.opaque_area.bounding_rect.height.should be > 0.0

    item.set_pixmap(replacement)

    item.pixmap.width.should eq(12)
    item.pixmap.height.should eq(9)
    item.bounding_rect.should eq(Qt6::RectF.new(3.0, 4.0, 12.0, 9.0))
    item.contains?(Qt6::PointF.new(10.0, 10.0)).should be_true
    item.contains?(Qt6::PointF.new(20.0, 20.0)).should be_false

    parent.release
  end

  it "supports graphics polygon items" do
    app

    parent = Qt6::AbstractGraphicsShapeItem.new
    polygon = Qt6::QPolygonF.new([
      Qt6::PointF.new(0.0, 0.0),
      Qt6::PointF.new(14.0, 0.0),
      Qt6::PointF.new(8.0, 10.0),
    ])
    item = Qt6::GraphicsPolygonItem.new(polygon, parent)
    pen = Qt6::QPen.new(Qt6::Color.new(160, 40, 90), 2.0)
    brush = Qt6::QBrush.new(Qt6::Color.new(30, 170, 120, 220))

    item.pen = pen
    item.brush = brush
    item.fill_rule = Qt6::FillRule::Winding

    item.parent_item.not_nil!.to_unsafe.should eq(parent.to_unsafe)
    item.polygon.size.should eq(3)
    item.polygon.bounding_rect.should eq(Qt6::RectF.new(0.0, 0.0, 14.0, 10.0))
    item.pen.color.should eq(Qt6::Color.new(160, 40, 90, 255))
    item.pen.width.should eq(2.0)
    item.brush.color.should eq(Qt6::Color.new(30, 170, 120, 220))
    item.fill_rule.should eq(Qt6::FillRule::Winding)
    item.contains?(Qt6::PointF.new(7.0, 3.0)).should be_true
    item.contains?(Qt6::PointF.new(13.5, 9.0)).should be_false
    item.obscured_by?(parent).should be_false
    item.bounding_rect.width.should be > item.polygon.bounding_rect.width
    item.bounding_rect.height.should be > item.polygon.bounding_rect.height

    replacement = Qt6::QPolygonF.new([
      Qt6::PointF.new(2.0, 1.0),
      Qt6::PointF.new(18.0, 1.0),
      Qt6::PointF.new(18.0, 8.0),
      Qt6::PointF.new(2.0, 8.0),
    ])
    item.set_polygon(replacement)

    item.polygon.size.should eq(4)
    item.polygon.bounding_rect.should eq(Qt6::RectF.new(2.0, 1.0, 16.0, 7.0))
    item.contains?(Qt6::PointF.new(10.0, 4.0)).should be_true
    item.contains?(Qt6::PointF.new(0.0, 0.0)).should be_false
    item.bounding_rect.width.should be > 0.0
    item.bounding_rect.height.should be > 0.0

    parent.release
  end

  it "supports graphics proxy widgets" do
    app

    parent = Qt6::GraphicsWidget.new
    container = Qt6::Widget.new
    container.resize(160, 50)
    field = Qt6::LineEdit.new("Proxy child", container)
    field.resize(90, 24)
    proxy = Qt6::GraphicsProxyWidget.new(container, parent)

    proxy.parent_item.should_not be_nil
    proxy.widget.not_nil!.to_unsafe.should eq(container.to_unsafe)

    root_rect = proxy.sub_widget_rect(container)
    child_rect = proxy.sub_widget_rect(field)
    root_rect.width.should be > 0.0
    root_rect.height.should be > 0.0
    child_rect.width.should be > 0.0
    child_rect.height.should be > 0.0

    child_proxy = proxy.create_proxy_for_child_widget(field)
    child_proxy.should_not be_nil
    child_proxy.not_nil!.widget.not_nil!.to_unsafe.should eq(field.to_unsafe)
    child_proxy.not_nil!.parent_item.should_not be_nil

    replacement = Qt6::Label.new("Replacement")
    replacement.resize(120, 30)
    proxy.set_widget(replacement).to_unsafe.should eq(proxy.to_unsafe)
    proxy.widget.not_nil!.to_unsafe.should eq(replacement.to_unsafe)
    proxy.sub_widget_rect(replacement).width.should be > 0.0
    proxy.sub_widget_rect(replacement).height.should be > 0.0

    parent.release
  end

  it "supports graphics item groups" do
    app

    group = Qt6::GraphicsItemGroup.new
    first = Qt6::GraphicsEllipseItem.new(0, 0, 10, 10)
    second = Qt6::GraphicsEllipseItem.new(20, 0, 8, 8)
    blocker = Qt6::GraphicsEllipseItem.new(0, 0, 4, 4)
    first.brush = Qt6::QBrush.new(Qt6::Color.new(200, 20, 20))
    second.brush = Qt6::QBrush.new(Qt6::Color.new(20, 120, 220))

    first.group = group
    group.add_to_group(second)

    first.group.not_nil!.to_unsafe.should eq(group.to_unsafe)
    second.group.not_nil!.to_unsafe.should eq(group.to_unsafe)
    first.parent_item.not_nil!.to_unsafe.should eq(group.to_unsafe)
    second.parent_item.not_nil!.to_unsafe.should eq(group.to_unsafe)
    group.bounding_rect.width.should be > 20.0
    group.bounding_rect.height.should be > 0.0
    group.opaque_area.empty?.should be_true
    group.obscured_by?(blocker).should be_false

    group.remove_from_group(second)
    second.group.should be_nil
    second.parent_item.should be_nil
    second.scene_bounding_rect.x.should be > 19.0
    group.bounding_rect.width.should be < 20.0

    group.release
    second.release
    blocker.release
  end

  it "supports graphics anchor layouts and anchors" do
    app

    parent = Qt6::GraphicsWidget.new
    layout = Qt6::GraphicsAnchorLayout.new
    first = Qt6::GraphicsWidget.new(parent)
    second = Qt6::GraphicsWidget.new(parent)

    parent.layout = layout
    parent.layout.not_nil!.to_unsafe.should eq(layout.to_unsafe)
    first.parent_item.should_not be_nil

    first.visible = false
    first.visible?.should be_false
    first.enabled = false
    first.enabled?.should be_false
    first.opacity = 0.75
    first.opacity.should eq(0.75)
    first.auto_fill_background = true
    first.auto_fill_background?.should be_true

    font = Qt6::QFont.new("Helvetica", 13, bold: true)
    first.font = font
    first.font.family.should eq(font.family)
    first.font.point_size.should eq(13)
    first.font.bold?.should be_true

    palette = Qt6::QPalette.new
    palette.set_color(Qt6::ColorRole::WindowText, Qt6::Color.new(12, 34, 56))
    first.palette = palette
    first.palette.color(Qt6::ColorRole::WindowText).should eq(Qt6::Color.new(12, 34, 56, 255))

    first.set_size_policy(Qt6::SizePolicy::MinimumExpanding, Qt6::SizePolicy::Fixed)
    first.horizontal_size_policy.should eq(Qt6::SizePolicy::MinimumExpanding)
    first.vertical_size_policy.should eq(Qt6::SizePolicy::Fixed)

    first.set_minimum_size(20, 10)
    first.set_preferred_size(40, 20)
    first.set_maximum_size(80, 40)
    second.set_preferred_size(50, 30)
    first.minimum_size.should eq(Qt6::SizeF.new(20.0, 10.0))
    first.preferred_size.should eq(Qt6::SizeF.new(40.0, 20.0))
    first.maximum_size.should eq(Qt6::SizeF.new(80.0, 40.0))

    first.set_geometry(2, 3, 40, 20)
    first.geometry.should eq(Qt6::RectF.new(2.0, 3.0, 40.0, 20.0))
    first.adjust_size

    anchor = layout.add_anchor(first, Qt6::AnchorPoint::AnchorLeft, second, Qt6::AnchorPoint::AnchorLeft)
    mirror = layout.anchor(first, Qt6::AnchorPoint::AnchorLeft, second, Qt6::AnchorPoint::AnchorLeft)

    anchor.set_spacing(12.5)
    anchor.set_size_policy(Qt6::SizePolicy::Expanding)
    layout.set_horizontal_spacing(3.0)
    layout.set_vertical_spacing(7.0)
    layout.invalidate

    mirror.not_nil!.to_unsafe.should eq(anchor.to_unsafe)
    anchor.spacing.should eq(12.5)
    anchor.size_policy.should eq(Qt6::SizePolicy::Expanding)
    layout.horizontal_spacing.should eq(3.0)
    layout.vertical_spacing.should eq(7.0)
    layout.count.should eq(2)

    parent.release
  end

  it "supports graphics grid layouts" do
    app

    parent = Qt6::GraphicsWidget.new
    layout = Qt6::GraphicsGridLayout.new
    first = Qt6::GraphicsWidget.new(parent)
    second = Qt6::GraphicsWidget.new(parent)

    parent.layout = layout
    parent.geometry = Qt6::RectF.new(0.0, 0.0, 120.0, 60.0)
    first.set_preferred_size(26, 27)
    layout.set_size_policy(Qt6::SizePolicy::Expanding, Qt6::SizePolicy::Fixed)
    layout.set_minimum_size(10, 11)
    layout.set_preferred_size(30, 31)
    layout.set_maximum_size(50, 51)
    parent.layout.should be_a(Qt6::GraphicsGridLayout)
    parent.layout.not_nil!.to_unsafe.should eq(layout.to_unsafe)
    previous_propagation = Qt6::GraphicsLayout.instant_invalidate_propagation?

    layout.set_contents_margins(1, 2, 3, 4)
    Qt6::GraphicsLayout.instant_invalidate_propagation = !previous_propagation
    layout.add_item(first, 0, 0, Qt6::AlignmentFlag::Center)
    layout.add_item(second, 0, 1, 2, 1, Qt6::AlignmentFlag::Bottom)
    layout.spacing = 6.5
    layout.horizontal_spacing = 7.5
    layout.vertical_spacing = 8.5
    layout.set_row_spacing(1, 11.0)
    layout.set_column_spacing(1, 12.0)
    layout.set_row_stretch_factor(0, 2)
    layout.set_column_stretch_factor(1, 3)
    layout.set_row_minimum_height(0, 14.0)
    layout.set_row_preferred_height(0, 18.0)
    layout.set_row_maximum_height(0, 22.0)
    layout.set_column_minimum_width(1, 16.0)
    layout.set_column_preferred_width(1, 20.0)
    layout.set_column_maximum_width(1, 24.0)
    layout.set_row_alignment(0, Qt6::AlignmentFlag::VCenter)
    layout.set_column_alignment(1, Qt6::AlignmentFlag::Right)
    layout.set_alignment(first, Qt6::AlignmentFlag::Center)
    layout.activate
    layout.activated?.should be_true
    layout.update_geometry

    layout.contents_margins.should eq(Qt6::MarginsF.new(1.0, 2.0, 3.0, 4.0))
    layout.horizontal_size_policy.should eq(Qt6::SizePolicy::Expanding)
    layout.vertical_size_policy.should eq(Qt6::SizePolicy::Fixed)
    layout.minimum_size.should eq(Qt6::SizeF.new(10.0, 11.0))
    layout.preferred_size.should eq(Qt6::SizeF.new(30.0, 31.0))
    layout.maximum_size.should eq(Qt6::SizeF.new(50.0, 51.0))
    layout.geometry.should eq(Qt6::RectF.new(0.0, 0.0, 50.0, 51.0))
    layout.contents_rect.should eq(Qt6::RectF.new(1.0, 2.0, 46.0, 45.0))
    layout.effective_size_hint(Qt6::GraphicsLayoutItemSizeHint::PreferredSize).width.should be >= 30.0
    layout.empty?.should be_false
    layout.parent_layout_item.not_nil!.to_unsafe.should eq(parent.to_unsafe)
    layout.graphics_layout?.should be_true
    layout.graphics_item.should be_nil
    Qt6::GraphicsLayout.instant_invalidate_propagation?.should eq(!previous_propagation)
    layout.horizontal_spacing.should eq(7.5)
    layout.vertical_spacing.should eq(8.5)
    layout.row_spacing(1).should eq(11.0)
    layout.column_spacing(1).should eq(12.0)
    layout.row_stretch_factor(0).should eq(2)
    layout.column_stretch_factor(1).should eq(3)
    layout.row_minimum_height(0).should eq(14.0)
    layout.row_preferred_height(0).should eq(18.0)
    layout.row_maximum_height(0).should eq(22.0)
    layout.column_minimum_width(1).should eq(16.0)
    layout.column_preferred_width(1).should eq(20.0)
    layout.column_maximum_width(1).should eq(24.0)
    layout.row_alignment(0).should eq(Qt6::AlignmentFlag::VCenter)
    layout.column_alignment(1).should eq(Qt6::AlignmentFlag::Right)
    layout.alignment(first).should eq(Qt6::AlignmentFlag::Center)
    layout.row_count.should eq(2)
    layout.column_count.should eq(2)
    layout.count.should eq(2)
    layout.item_at(0, 0).not_nil!.to_unsafe.should eq(first.to_unsafe)
    layout.item_at(0, 1).not_nil!.to_unsafe.should eq(second.to_unsafe)
    first.contents_margins.should eq(Qt6::MarginsF.new(0.0, 0.0, 0.0, 0.0))
    first.contents_rect.width.should be >= 0.0
    first.effective_size_hint(Qt6::GraphicsLayoutItemSizeHint::PreferredSize).should eq(Qt6::SizeF.new(26.0, 27.0))
    first.empty?.should be_false
    first.parent_layout_item.not_nil!.to_unsafe.should eq(layout.to_unsafe)
    first.graphics_layout?.should be_false
    first.owned_by_layout?.should be_false
    parent.parent_layout_item.should be_nil
    parent.graphics_layout?.should be_false

    layout.remove_item(first)
    layout.count.should eq(1)
    layout.item_at(0, 0).should be_nil
    layout.remove_at(0)
    layout.count.should eq(0)
    Qt6::GraphicsLayout.instant_invalidate_propagation = previous_propagation

    parent.release
  end

  it "supports graphics linear layouts" do
    app

    parent = Qt6::GraphicsWidget.new
    outer = Qt6::GraphicsLinearLayout.new(Qt6::Orientation::Horizontal)
    inner = Qt6::GraphicsLinearLayout.new(Qt6::Orientation::Vertical)
    first = Qt6::GraphicsWidget.new(parent)
    second = Qt6::GraphicsWidget.new(parent)

    parent.layout = outer
    parent.geometry = Qt6::RectF.new(0.0, 0.0, 160.0, 90.0)
    first.set_preferred_size(30, 20)
    second.set_preferred_size(25, 15)

    outer.add_item(first)
    outer.insert_stretch(1, 2)
    outer.insert_item(2, inner)
    inner.add_item(second)
    outer.spacing = 9.5
    outer.set_item_spacing(0, 6.5)
    outer.set_stretch_factor(first, 3)
    outer.set_stretch_factor(inner, 4)
    outer.set_alignment(first, Qt6::AlignmentFlag::Center)
    outer.set_alignment(inner, Qt6::AlignmentFlag::Bottom)
    outer.activate

    parent.layout.should be_a(Qt6::GraphicsLinearLayout)
    parent.layout.not_nil!.to_unsafe.should eq(outer.to_unsafe)
    outer.orientation.should eq(Qt6::Orientation::Horizontal)
    inner.orientation.should eq(Qt6::Orientation::Vertical)
    outer.spacing.should eq(9.5)
    outer.item_spacing(0).should eq(6.5)
    outer.stretch_factor(first).should eq(3)
    outer.stretch_factor(inner).should eq(4)
    outer.alignment(first).should eq(Qt6::AlignmentFlag::Center)
    outer.alignment(inner).should eq(Qt6::AlignmentFlag::Bottom)
    outer.count.should eq(2)
    outer.item_at(0).not_nil!.to_unsafe.should eq(first.to_unsafe)
    outer.item_at(1).not_nil!.to_unsafe.should eq(inner.to_unsafe)
    outer.geometry.width.should be > 0.0
    outer.geometry.height.should be > 0.0
    inner.parent_layout_item.not_nil!.to_unsafe.should eq(outer.to_unsafe)
    inner.graphics_layout?.should be_true
    inner.graphics_item.should be_nil
    second.parent_layout_item.not_nil!.to_unsafe.should eq(inner.to_unsafe)

    outer.remove_item(inner)
    outer.count.should eq(1)
    inner.parent_layout_item.should be_nil

    inner.release
    parent.release
  end

  it "supports graphics-view configuration and transforms" do
    app

    view = Qt6::GraphicsView.new
    view.resize(200, 140)
    view.show

    background = Qt6::QBrush.new(Qt6::Color.new(10, 20, 30))
    foreground = Qt6::QBrush.new(Qt6::Color.new(200, 210, 220))
    view.background_brush = background
    view.foreground_brush = foreground
    view.interactive = false
    view.scene_rect = Qt6::RectF.new(0.0, 0.0, 320.0, 240.0)
    view.alignment = Qt6::AlignmentFlag::Center
    view.render_hints = Qt6::PainterRenderHint::Antialiasing | Qt6::PainterRenderHint::TextAntialiasing
    view.set_render_hint(Qt6::PainterRenderHint::SmoothPixmapTransform)
    view.drag_mode = Qt6::GraphicsViewDragMode::ScrollHandDrag
    view.cache_mode = Qt6::GraphicsViewCacheModeFlag::CacheBackground
    view.transformation_anchor = Qt6::GraphicsViewViewportAnchor::AnchorUnderMouse
    view.resize_anchor = Qt6::GraphicsViewViewportAnchor::AnchorViewCenter
    view.viewport_update_mode = Qt6::GraphicsViewViewportUpdateMode::BoundingRectViewportUpdate
    view.optimization_flags = Qt6::GraphicsViewOptimizationFlag::DontSavePainterState
    view.set_optimization_flag(Qt6::GraphicsViewOptimizationFlag::DontAdjustForAntialiasing)

    transform = Qt6::QTransform.new
    transform.translate(5, 7)
    view.set_transform(transform)
    view.scale(2.0, 3.0)
    view.rotate(90)
    view.shear(0.5, 0.0)
    view.translate(1.0, 2.0)
    view.center_on(Qt6::PointF.new(12.0, 18.0))
    view.ensure_visible(Qt6::RectF.new(0.0, 0.0, 20.0, 20.0), 4, 5)
    view.fit_in_view(Qt6::RectF.new(0.0, 0.0, 40.0, 30.0), Qt6::AspectRatioMode::Keep)
    view.reset_cached_content

    view.background_brush.color.should eq(Qt6::Color.new(10, 20, 30, 255))
    view.foreground_brush.color.should eq(Qt6::Color.new(200, 210, 220, 255))
    view.interactive?.should be_false
    view.scene_rect.should eq(Qt6::RectF.new(0.0, 0.0, 320.0, 240.0))
    view.alignment.should eq(Qt6::AlignmentFlag::Center)
    view.render_hints.includes?(Qt6::PainterRenderHint::Antialiasing).should be_true
    view.render_hints.includes?(Qt6::PainterRenderHint::TextAntialiasing).should be_true
    view.render_hints.includes?(Qt6::PainterRenderHint::SmoothPixmapTransform).should be_true
    view.drag_mode.should eq(Qt6::GraphicsViewDragMode::ScrollHandDrag)
    view.cache_mode.should eq(Qt6::GraphicsViewCacheModeFlag::CacheBackground)
    view.transformation_anchor.should eq(Qt6::GraphicsViewViewportAnchor::AnchorUnderMouse)
    view.resize_anchor.should eq(Qt6::GraphicsViewViewportAnchor::AnchorViewCenter)
    view.viewport_update_mode.should eq(Qt6::GraphicsViewViewportUpdateMode::BoundingRectViewportUpdate)
    view.optimization_flags.includes?(Qt6::GraphicsViewOptimizationFlag::DontSavePainterState).should be_true
    view.optimization_flags.includes?(Qt6::GraphicsViewOptimizationFlag::DontAdjustForAntialiasing).should be_true
    view.transformed?.should be_true
    view.transform.map(Qt6::PointF.new(0.0, 0.0)).should_not eq(Qt6::PointF.new(0.0, 0.0))
    view.viewport_transform.map(Qt6::PointF.new(0.0, 0.0)).should_not eq(Qt6::PointF.new(0.0, 0.0))

    view.reset_transform
    view.transform.map(Qt6::PointF.new(0.0, 0.0)).should eq(Qt6::PointF.new(0.0, 0.0))
    view.transform.map(Qt6::PointF.new(2.0, 3.0)).should eq(Qt6::PointF.new(2.0, 3.0))

    view.release
  end

  it "supports gradients and advanced pen styling" do
    app

    gradient_canvas = Qt6::QImage.new(12, 12)
    gradient_canvas.fill(Qt6::Color.new(0, 0, 0, 0))
    conical_canvas = Qt6::QImage.new(12, 12)
    conical_canvas.fill(Qt6::Color.new(0, 0, 0, 0))

    linear = Qt6::QLinearGradient.new(0.0, 0.0, 10.0, 0.0)
    linear.set_color_at(0.0, Qt6::Color.new(255, 0, 0))
    linear.set_color_at(1.0, Qt6::Color.new(0, 0, 255))
    linear.stops.should eq([
      Qt6::GradientStop.new(0.0, Qt6::Color.new(255, 0, 0, 255)),
      Qt6::GradientStop.new(1.0, Qt6::Color.new(0, 0, 255, 255)),
    ])
    linear.start.should eq(Qt6::PointF.new(0.0, 0.0))
    linear.final_stop.should eq(Qt6::PointF.new(10.0, 0.0))
    linear.spread.should eq(Qt6::GradientSpread::PadSpread)
    linear.coordinate_mode.should eq(Qt6::GradientCoordinateMode::LogicalMode)

    configured_linear = Qt6::QLinearGradient.new(0.0, 0.0, 10.0, 0.0)
    configured_linear.spread = Qt6::GradientSpread::RepeatSpread
    configured_linear.coordinate_mode = Qt6::GradientCoordinateMode::ObjectBoundingMode
    configured_linear.spread.should eq(Qt6::GradientSpread::RepeatSpread)
    configured_linear.coordinate_mode.should eq(Qt6::GradientCoordinateMode::ObjectBoundingMode)

    radial = Qt6::QRadialGradient.new(Qt6::PointF.new(6.0, 8.0), 4.0)
    radial.set_color_at(0.0, Qt6::Color.new(255, 255, 255))
    radial.set_color_at(1.0, Qt6::Color.new(0, 0, 0))
    radial.stops.should eq([
      Qt6::GradientStop.new(0.0, Qt6::Color.new(255, 255, 255, 255)),
      Qt6::GradientStop.new(1.0, Qt6::Color.new(0, 0, 0, 255)),
    ])
    radial.center.should eq(Qt6::PointF.new(6.0, 8.0))
    radial.focal_point.should eq(Qt6::PointF.new(6.0, 8.0))
    radial.radius.should eq(4.0)
    radial.spread.should eq(Qt6::GradientSpread::PadSpread)
    radial.coordinate_mode.should eq(Qt6::GradientCoordinateMode::LogicalMode)
    configured_radial = Qt6::QRadialGradient.new(Qt6::PointF.new(6.0, 8.0), 4.0)
    configured_radial.spread = Qt6::GradientSpread::ReflectSpread
    configured_radial.coordinate_mode = Qt6::GradientCoordinateMode::StretchToDeviceMode
    configured_radial.spread.should eq(Qt6::GradientSpread::ReflectSpread)
    configured_radial.coordinate_mode.should eq(Qt6::GradientCoordinateMode::StretchToDeviceMode)

    offset_radial = Qt6::QRadialGradient.new(Qt6::PointF.new(6.0, 8.0), 4.0, Qt6::PointF.new(8.0, 8.0))
    offset_radial.set_color_at(0.0, Qt6::Color.new(255, 255, 255))
    offset_radial.set_color_at(1.0, Qt6::Color.new(0, 0, 0))
    offset_radial.focal_point.should eq(Qt6::PointF.new(8.0, 8.0))
    offset_radial.focal_point = Qt6::PointF.new(7.0, 8.0)
    offset_radial.focal_point.should eq(Qt6::PointF.new(7.0, 8.0))

    conical = Qt6::QConicalGradient.new(Qt6::PointF.new(6.0, 6.0), 0.0)
    conical.set_color_at(0.0, Qt6::Color.new(255, 0, 0))
    conical.set_color_at(0.5, Qt6::Color.new(0, 0, 255))
    conical.set_color_at(1.0, Qt6::Color.new(255, 0, 0))
    conical.stops.should eq([
      Qt6::GradientStop.new(0.0, Qt6::Color.new(255, 0, 0, 255)),
      Qt6::GradientStop.new(0.5, Qt6::Color.new(0, 0, 255, 255)),
      Qt6::GradientStop.new(1.0, Qt6::Color.new(255, 0, 0, 255)),
    ])
    conical.center.should eq(Qt6::PointF.new(6.0, 6.0))
    conical.angle.should eq(0.0)
    conical.angle = 90.0
    conical.angle.should eq(90.0)
    conical.spread.should eq(Qt6::GradientSpread::PadSpread)
    conical.coordinate_mode.should eq(Qt6::GradientCoordinateMode::LogicalMode)
    configured_conical = Qt6::QConicalGradient.new(Qt6::PointF.new(6.0, 6.0), 90.0)
    configured_conical.spread = Qt6::GradientSpread::ReflectSpread
    configured_conical.coordinate_mode = Qt6::GradientCoordinateMode::ObjectMode
    configured_conical.spread.should eq(Qt6::GradientSpread::ReflectSpread)
    configured_conical.coordinate_mode.should eq(Qt6::GradientCoordinateMode::ObjectMode)

    Qt6::QPainter.paint(gradient_canvas) do |painter|
      painter.antialiasing = false
      painter.pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1).tap { |pen| pen.style = Qt6::PenStyle::NoPen }
      painter.brush = Qt6::QBrush.new(linear)
      painter.draw_rect(Qt6::RectF.new(0.0, 0.0, 10.0, 4.0))
      painter.brush = Qt6::QBrush.new(radial)
      painter.draw_rect(Qt6::RectF.new(2.0, 4.0, 8.0, 8.0))
    end

    Qt6::QPainter.paint(conical_canvas) do |painter|
      painter.antialiasing = false
      painter.pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1).tap { |pen| pen.style = Qt6::PenStyle::NoPen }
      painter.brush = Qt6::QBrush.new(conical)
      painter.draw_ellipse(Qt6::RectF.new(0.0, 0.0, 12.0, 12.0))
    end

    offset_radial_canvas = Qt6::QImage.new(14, 14)
    offset_radial_canvas.fill(Qt6::Color.new(0, 0, 0, 0))
    Qt6::QPainter.paint(offset_radial_canvas) do |painter|
      painter.antialiasing = false
      painter.pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1).tap { |pen| pen.style = Qt6::PenStyle::NoPen }
      painter.brush = Qt6::QBrush.new(offset_radial)
      painter.draw_rect(Qt6::RectF.new(1.0, 1.0, 12.0, 12.0))
    end

    left = gradient_canvas.pixel_color(1, 1)
    middle = gradient_canvas.pixel_color(5, 1)
    right = gradient_canvas.pixel_color(8, 1)
    radial_center = gradient_canvas.pixel_color(6, 8)
    radial_edge = gradient_canvas.pixel_color(2, 8)
    offset_radial_left = offset_radial_canvas.pixel_color(6, 8)
    offset_radial_center = offset_radial_canvas.pixel_color(7, 8)
    offset_radial_right = offset_radial_canvas.pixel_color(8, 8)
    conical_samples = [
      conical_canvas.pixel_color(6, 1),
      conical_canvas.pixel_color(10, 6),
      conical_canvas.pixel_color(6, 10),
      conical_canvas.pixel_color(1, 6),
    ]

    left.red.should be > left.blue
    middle.red.should be > 0
    middle.blue.should be > 0
    right.blue.should be > right.red
    radial_center.red.should be > radial_edge.red
    radial_center.green.should be > radial_edge.green
    radial_center.blue.should be > radial_edge.blue
    offset_radial_left.red.should be > offset_radial_center.red
    offset_radial_center.red.should be > offset_radial_right.red
    offset_radial_left.green.should be > offset_radial_center.green
    offset_radial_center.green.should be > offset_radial_right.green
    offset_radial_left.blue.should be > offset_radial_center.blue
    offset_radial_center.blue.should be > offset_radial_right.blue
    conical_samples.all? { |sample| sample.alpha > 0 }.should be_true
    conical_samples.map { |sample| {sample.red, sample.green, sample.blue, sample.alpha} }.uniq.size.should be > 1
    conical_samples.any? { |sample| sample.red > 0 }.should be_true
    conical_samples.any? { |sample| sample.blue > 0 }.should be_true

    repeated_canvas = Qt6::QImage.new(12, 4)
    repeated_canvas.fill(Qt6::Color.new(0, 0, 0, 0))
    repeating = Qt6::QLinearGradient.new(0.0, 0.0, 0.5, 0.0)
    repeating.coordinate_mode = Qt6::GradientCoordinateMode::ObjectBoundingMode
    repeating.spread = Qt6::GradientSpread::RepeatSpread
    repeating.set_color_at(0.0, Qt6::Color.new(255, 0, 0))
    repeating.set_color_at(1.0, Qt6::Color.new(0, 0, 255))

    Qt6::QPainter.paint(repeated_canvas) do |painter|
      painter.antialiasing = false
      painter.pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1).tap { |pen| pen.style = Qt6::PenStyle::NoPen }
      painter.brush = Qt6::QBrush.new(repeating)
      painter.draw_rect(Qt6::RectF.new(0.0, 0.0, 12.0, 4.0))
    end

    repeat_left = repeated_canvas.pixel_color(1, 1)
    repeat_middle = repeated_canvas.pixel_color(4, 1)
    repeat_second_cycle = repeated_canvas.pixel_color(7, 1)
    repeat_right = repeated_canvas.pixel_color(10, 1)
    repeat_left.red.should be > repeat_left.blue
    repeat_middle.blue.should be > repeat_middle.red
    repeat_second_cycle.red.should be > repeat_second_cycle.blue
    repeat_right.blue.should be > repeat_right.red

    dash_canvas = Qt6::QImage.new(12, 12)
    dash_canvas.fill(Qt6::Color.new(0, 0, 0, 0))

    dashed_pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1)
    dashed_pen.cap_style = Qt6::PenCapStyle::FlatCap
    dashed_pen.join_style = Qt6::PenJoinStyle::RoundJoin
    dashed_pen.dash_pattern = [2.0, 2.0]
    dashed_pen.dash_offset = 0.0

    Qt6::QPainter.paint(dash_canvas) do |painter|
      painter.antialiasing = false
      painter.pen = dashed_pen
      painter.draw_line(Qt6::PointF.new(0.0, 6.0), Qt6::PointF.new(11.0, 6.0))
    end

    dashed_pen.style.should eq(Qt6::PenStyle::CustomDashLine)
    dashed_pen.join_style.should eq(Qt6::PenJoinStyle::RoundJoin)
    dashed_pen.dash_offset.should eq(0.0)
    dash_canvas.pixel_color(0, 6).should eq(Qt6::Color.new(0, 0, 0, 255))
    dash_canvas.pixel_color(1, 6).should eq(Qt6::Color.new(0, 0, 0, 255))
    dash_canvas.pixel_color(3, 6).should eq(Qt6::Color.new(0, 0, 0, 0))
    dash_canvas.pixel_color(4, 6).should eq(Qt6::Color.new(0, 0, 0, 255))
    dash_canvas.pixel_color(5, 6).should eq(Qt6::Color.new(0, 0, 0, 255))
    dash_canvas.pixel_color(7, 6).should eq(Qt6::Color.new(0, 0, 0, 0))
  end

  it "supports rounded primitives, polylines, arcs, and rect-based text" do
    app

    canvas = Qt6::QImage.new(40, 40)
    canvas.fill(Qt6::Color.new(0, 0, 0, 0))

    outline_pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1)
    fill_pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1)
    fill_pen.style = Qt6::PenStyle::NoPen
    polyline_pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 255), 1)
    polyline_pen.cap_style = Qt6::PenCapStyle::FlatCap

    polyline = Qt6::QPolygonF.new
    polyline << Qt6::PointF.new(2.0, 20.0)
    polyline << Qt6::PointF.new(10.0, 12.0)
    polyline << Qt6::PointF.new(18.0, 20.0)

    Qt6::QPainter.paint(canvas) do |painter|
      painter.antialiasing = false

      painter.pen = fill_pen
      painter.brush = Qt6::Color.new(240, 80, 80)
      painter.draw_rounded_rect(Qt6::RectF.new(2.0, 2.0, 12.0, 12.0), 3.0, 3.0)

      painter.pen = polyline_pen
      painter.brush = Qt6::QBrush.new(Qt6::Color.new(0, 0, 0, 0))
      painter.draw_polyline(polyline)

      painter.pen = outline_pen
      painter.draw_arc(Qt6::RectF.new(20.0, 2.0, 12.0, 12.0), 0, 90 * 16)

      painter.pen = fill_pen
      painter.brush = Qt6::Color.new(80, 220, 80)
      painter.draw_pie(Qt6::RectF.new(20.0, 16.0, 12.0, 12.0), 0, 90 * 16)

      painter.brush = Qt6::Color.new(80, 80, 240)
      painter.draw_chord(Qt6::RectF.new(20.0, 28.0, 12.0, 10.0), 0, 180 * 16)

      painter.pen = Qt6::Color.new(255, 255, 255)
      painter.draw_text(
        Qt6::RectF.new(0.0, 28.0, 18.0, 10.0),
        Qt6::AlignmentFlag::Center,
        "A"
      )
    end

    canvas.pixel_color(8, 8).should eq(Qt6::Color.new(240, 80, 80, 255))
    canvas.pixel_color(2, 2).should eq(Qt6::Color.new(0, 0, 0, 0))
    canvas.pixel_color(10, 12).should eq(Qt6::Color.new(0, 0, 255, 255))
    canvas.pixel_color(32, 8).should eq(Qt6::Color.new(0, 0, 0, 255))
    canvas.pixel_color(31, 20).should eq(Qt6::Color.new(80, 220, 80, 255))
    canvas.pixel_color(26, 31).should eq(Qt6::Color.new(80, 80, 240, 255))
    text_pixels = (28..37).sum do |y|
      (0..17).count { |x| canvas.pixel_color(x, y).alpha > 0 }
    end
    text_pixels.should be > 0
  end

  it "supports regions for clipping, combination, and widget masks" do
    app

    base = Qt6::QRegion.new(Qt6::Rect.new(0, 0, 8, 8))
    ellipse = Qt6::QRegion.new(Qt6::Rect.new(4, 0, 8, 8), Qt6::RegionType::Ellipse)
    combined = base.united(ellipse)
    overlap = combined.intersected(Qt6::Rect.new(4, 0, 4, 8))
    translated = overlap.translated(0, 8)
    xor_region = base.xored(Qt6::QRegion.new(Qt6::Rect.new(4, 0, 8, 8)))
    subtracted = combined.subtracted(base)

    base.empty?.should be_false
    base.null?.should be_false
    base.bounding_rect.should eq(Qt6::Rect.new(0, 0, 8, 8))
    base.contains?(Qt6::Rect.new(1, 1, 2, 2)).should be_true
    base.intersects?(Qt6::Rect.new(7, 7, 4, 4)).should be_true
    combined.intersects?(ellipse).should be_true
    overlap.bounding_rect.should eq(Qt6::Rect.new(4, 0, 4, 8))
    translated.bounding_rect.should eq(Qt6::Rect.new(4, 8, 4, 8))
    xor_region.contains?(Qt6::Rect.new(0, 0, 2, 2)).should be_true
    xor_region.contains?(Qt6::Rect.new(5, 0, 2, 2)).should be_false
    subtracted.empty?.should be_false
    combined.rect_count.should be > 0

    mutable = Qt6::QRegion.new(Qt6::Rect.new(0, 0, 4, 4))
    mutable.unite(Qt6::Rect.new(4, 0, 4, 4))
    mutable.bounding_rect.should eq(Qt6::Rect.new(0, 0, 8, 4))
    mutable.intersect(Qt6::Rect.new(2, 0, 4, 4))
    mutable.bounding_rect.should eq(Qt6::Rect.new(2, 0, 4, 4))
    mutable.subtract(Qt6::QRegion.new(Qt6::Rect.new(4, 0, 2, 4)))
    mutable.contains?(Qt6::Rect.new(4, 0, 1, 1)).should be_false
    mutable.exclusive_or(Qt6::QRegion.new(Qt6::Rect.new(0, 0, 2, 4)))
    mutable.contains?(Qt6::Rect.new(0, 0, 2, 2)).should be_true
    mutable.clear
    mutable.empty?.should be_true

    canvas = Qt6::QImage.new(16, 16)
    canvas.fill(Qt6::Color.new(0, 0, 0, 0))
    clip_region = Qt6::QRegion.new(Qt6::Rect.new(4, 4, 4, 4))

    Qt6::QPainter.paint(canvas) do |painter|
      painter.clip_region = clip_region
      painter.fill_rect(Qt6::RectF.new(0.0, 0.0, 16.0, 16.0), Qt6::Color.new(220, 40, 40))
    end

    canvas.pixel_color(5, 5).should eq(Qt6::Color.new(220, 40, 40, 255))
    canvas.pixel_color(2, 2).should eq(Qt6::Color.new(0, 0, 0, 0))

    window = Qt6::Widget.new
    window.resize(16, 16)
    window.mask = ellipse
    window.mask.bounding_rect.should eq(Qt6::Rect.new(4, 0, 8, 8))
    window.mask.empty?.should be_false
    window.mask = nil
    window.mask.empty?.should be_true
    window.release

    widget = Qt6::Widget.new
    widget.resize(24, 24)
    widget.show
    app.process_events

    update_region = Qt6::QRegion.new(Qt6::Rect.new(6, 8, 5, 4))
    widget.update(update_region).should eq(widget)
    widget.update(Qt6::Rect.new(2, 3, 4, 5)).should eq(widget)
    widget.release
  end

  it "supports integer polygons and polygon-backed regions" do
    app

    polygon = Qt6::QPolygon.new([
      Qt6::Point.new(0, 0),
      Qt6::Point.new(8, 0),
      Qt6::Point.new(8, 8),
      Qt6::Point.new(0, 8),
    ])
    polygon << Qt6::Point.new(0, 0)

    winding_points = [
      Qt6::Point.new(0, 0),
      Qt6::Point.new(8, 0),
      Qt6::Point.new(8, 8),
      Qt6::Point.new(0, 8),
      Qt6::Point.new(0, 0),
      Qt6::Point.new(2, 2),
      Qt6::Point.new(6, 2),
      Qt6::Point.new(6, 6),
      Qt6::Point.new(2, 6),
      Qt6::Point.new(2, 2),
    ]
    complex_polygon = Qt6::QPolygon.new(winding_points)

    region = Qt6::QRegion.new(polygon)
    odd_even_region = Qt6::QRegion.new(complex_polygon, Qt6::FillRule::OddEven)
    winding_region = Qt6::QRegion.new(complex_polygon, Qt6::FillRule::Winding)
    polygon_path = Qt6::QPainterPath.new
    polygon_path.add_polygon(polygon)

    canvas = Qt6::QImage.new(12, 12)
    canvas.fill(Qt6::Color.new(0, 0, 0, 0))
    outline = Qt6::QPolygon.new([
      Qt6::Point.new(0, 10),
      Qt6::Point.new(3, 7),
      Qt6::Point.new(6, 10),
    ])
    convex_float = Qt6::QPolygonF.new([
      Qt6::PointF.new(8.0, 0.0),
      Qt6::PointF.new(11.0, 0.0),
      Qt6::PointF.new(11.0, 3.0),
      Qt6::PointF.new(8.0, 3.0),
    ])

    Qt6::QPainter.paint(canvas) do |painter|
      no_pen = Qt6::QPen.new(Qt6::Color.new(0, 0, 0), 1)
      no_pen.style = Qt6::PenStyle::NoPen
      painter.pen = no_pen
      painter.brush = Qt6::Color.new(180, 40, 40)
      painter.draw_polygon(polygon)
      painter.brush = Qt6::Color.new(40, 220, 90)
      painter.draw_convex_polygon(convex_float)

      painter.pen = Qt6::Color.new(40, 180, 220)
      painter.brush = Qt6::Color.new(0, 0, 0, 0)
      painter.draw_polyline(outline)
      painter.brush = Qt6::Color.new(240, 180, 40)
      painter.draw_convex_polygon(Qt6::QPolygon.new([
        Qt6::Point.new(8, 8),
        Qt6::Point.new(11, 8),
        Qt6::Point.new(11, 11),
        Qt6::Point.new(8, 11),
      ]))
    end

    polygon.size.should eq(5)
    polygon[2].should eq(Qt6::Point.new(8, 8))
    polygon.bounding_rect.should eq(Qt6::Rect.new(0, 0, 9, 9))
    polygon.to_a.last.should eq(Qt6::Point.new(0, 0))
    polygon_path.contains(Qt6::PointF.new(2.0, 2.0)).should be_true
    polygon_path.contains(Qt6::PointF.new(9.0, 2.0)).should be_false

    region.bounding_rect.should eq(Qt6::Rect.new(0, 0, 8, 8))
    region.contains?(Qt6::Rect.new(2, 2, 2, 2)).should be_true
    odd_even_region.contains?(Qt6::Rect.new(3, 3, 1, 1)).should be_false
    winding_region.contains?(Qt6::Rect.new(3, 3, 1, 1)).should be_true
    canvas.pixel_color(2, 2).should eq(Qt6::Color.new(180, 40, 40, 255))
    canvas.pixel_color(9, 1).should eq(Qt6::Color.new(40, 220, 90, 255))
    canvas.pixel_color(3, 7).should eq(Qt6::Color.new(40, 180, 220, 255))
    canvas.pixel_color(9, 9).should eq(Qt6::Color.new(240, 180, 40, 255))

    window = Qt6::Widget.new
    window.resize(16, 16)
    window.mask = region
    window.mask.bounding_rect.should eq(Qt6::Rect.new(0, 0, 8, 8))
    window.release
  end

  it "supports monochrome bitmaps for masks, transforms, and file round-trips" do
    app

    source = Qt6::QImage.new(8, 8)
    source.fill(Qt6::Color.new(255, 255, 255))
    Qt6::QPainter.paint(source) do |painter|
      painter.fill_rect(Qt6::RectF.new(0.0, 0.0, 4.0, 8.0), Qt6::Color.new(0, 0, 0))
    end

    bitmap = Qt6::QBitmap.from_image(source)
    bitmap.null?.should be_false
    bitmap.size.should eq(Qt6::Size.new(8, 8))
    bitmap.to_image.pixel_color(1, 1).should eq(Qt6::Color.new(0, 0, 0, 255))
    bitmap.to_image.pixel_color(6, 1).should eq(Qt6::Color.new(255, 255, 255, 255))

    bitmap_region = Qt6::QRegion.new(bitmap)
    bitmap_region.bounding_rect.should eq(Qt6::Rect.new(0, 0, 4, 8))

    pixmap_bitmap = Qt6::QBitmap.from_pixmap(Qt6::QPixmap.from_image(source))
    Qt6::QRegion.new(pixmap_bitmap).bounding_rect.should eq(Qt6::Rect.new(0, 0, 4, 8))

    raw_bitmap = Qt6::QBitmap.from_data(
      Qt6::Size.new(8, 8),
      Bytes[
        0b00001111_u8,
        0b00001111_u8,
        0b00001111_u8,
        0b00001111_u8,
        0b00001111_u8,
        0b00001111_u8,
        0b00001111_u8,
        0b00001111_u8,
      ]
    )
    raw_bitmap.to_image.pixel_color(1, 1).should eq(Qt6::Color.new(0, 0, 0, 255))
    raw_bitmap.to_image.pixel_color(6, 1).should eq(Qt6::Color.new(255, 255, 255, 255))
    Qt6::QRegion.new(raw_bitmap).bounding_rect.should eq(Qt6::Rect.new(0, 0, 4, 8))

    transformed = raw_bitmap.transformed(Qt6::QTransform.new.scale(2.0, 1.0))
    transformed.size.should eq(Qt6::Size.new(16, 8))

    bitmap_path = File.join(Dir.tempdir, "crystal-qt6-bitmap-#{Process.pid}.png")
    bitmap.save(bitmap_path).should be_true
    loaded_bitmap = Qt6::QBitmap.from_file(bitmap_path)
    loaded_bitmap.null?.should be_false
    loaded_bitmap.size.should eq(Qt6::Size.new(8, 8))

    raw_bitmap.clear
    cleared_region = Qt6::QRegion.new(raw_bitmap)
    cleared_region.empty?.should be_true
    cleared_region.bounding_rect.should eq(Qt6::Rect.new(0, 0, 0, 0))
  end

  it "supports byte arrays, buffers, data-backed images, and mm-based pdf sizing" do
    app

    raw = Qt6::QByteArray.new(Bytes[1_u8, 2_u8, 3_u8, 4_u8])
    raw.size.should eq(4)
    raw.bytes.should eq(Bytes[1_u8, 2_u8, 3_u8, 4_u8])
    raw.clear
    raw.empty?.should be_true

    raw_pixels = Bytes[
      30_u8, 20_u8, 10_u8, 255_u8,
      60_u8, 50_u8, 40_u8, 255_u8,
      90_u8, 80_u8, 70_u8, 255_u8,
      120_u8, 110_u8, 100_u8, 255_u8,
    ]
    raw_image = Qt6::QImage.from_raw_data(raw_pixels, 2, 2, 8, Qt6::ImageFormat::ARGB32)
    raw_image.null?.should be_false
    raw_image.format.should eq(Qt6::ImageFormat::ARGB32)
    raw_image.bytes_per_line.should eq(8)
    raw_image.size_in_bytes.should eq(16)
    raw_image.bytes.should eq(raw_pixels)
    raw_image.pixel_color(0, 0).should eq(Qt6::Color.new(10, 20, 30, 255))
    raw_image.pixel_color(1, 1).should eq(Qt6::Color.new(100, 110, 120, 255))

    raw_copy = raw_image.copy
    raw_copy.set_pixel_color(0, 0, Qt6::Color.new(200, 10, 20, 255))
    raw_image.pixel_color(0, 0).should eq(Qt6::Color.new(10, 20, 30, 255))
    raw_copy.pixel_color(0, 0).should eq(Qt6::Color.new(200, 10, 20, 255))

    raw_region = raw_image.copy(Qt6::Rect.new(1, 0, 1, 2))
    raw_region.size.should eq(Qt6::Size.new(1, 2))
    raw_region.pixel_color(0, 0).should eq(Qt6::Color.new(40, 50, 60, 255))
    raw_region.pixel_color(0, 1).should eq(Qt6::Color.new(100, 110, 120, 255))

    premultiplied = raw_image.convert_to_format(Qt6::ImageFormat::ARGB32Premultiplied)
    premultiplied.format.should eq(Qt6::ImageFormat::ARGB32Premultiplied)
    premultiplied.bytes.size.should eq(premultiplied.size_in_bytes)

    grayscale = raw_image.convert_to_format(Qt6::ImageFormat::Grayscale8)
    grayscale.format.should eq(Qt6::ImageFormat::Grayscale8)
    grayscale.grayscale?.should be_true
    grayscale.depth.should eq(8)
    raw_image.has_alpha_channel?.should be_true
    raw_image.all_gray?.should be_false

    scaled = raw_image.scaled(4, 8, Qt6::AspectRatioMode::Keep, Qt6::TransformationMode::Smooth)
    scaled.size.should eq(Qt6::Size.new(4, 4))
    raw_image.scaled_to_width(6).size.should eq(Qt6::Size.new(6, 6))
    raw_image.scaled_to_height(8).size.should eq(Qt6::Size.new(8, 8))

    mirrored_horizontal = raw_image.mirrored(horizontal: true, vertical: false)
    mirrored_horizontal.pixel_color(0, 0).should eq(Qt6::Color.new(40, 50, 60, 255))
    mirrored_vertical = raw_image.mirrored(horizontal: false, vertical: true)
    mirrored_vertical.pixel_color(0, 0).should eq(Qt6::Color.new(70, 80, 90, 255))
    raw_image.rgb_swapped.pixel_color(0, 0).should eq(Qt6::Color.new(30, 20, 10, 255))

    inverted = raw_image.copy.invert_pixels
    inverted.pixel_color(0, 0).should eq(Qt6::Color.new(245, 235, 225, 255))

    image_scale = Qt6::QTransform.new.scale(2.0, 2.0)
    transformed_image = raw_image.transformed(image_scale)
    transformed_image.size.should eq(Qt6::Size.new(4, 4))

    image = Qt6::QImage.new(4, 4)
    image.fill(Qt6::Color.new(0, 0, 0, 0))
    image.set_pixel_color(1, 1, Qt6::Color.new(10, 20, 30))
    image.set_pixel_color(2, 2, Qt6::Color.new(200, 150, 100))

    byte_array = Qt6::QByteArray.new
    buffer = Qt6::QBuffer.new(byte_array)
    buffer.open(Qt6::IODeviceOpenMode::WriteOnly).should be_true
    image.save(buffer, "PNG").should be_true
    buffer.close
    buffer.open?.should be_false

    encoded = byte_array.bytes
    encoded.size.should be > 0

    image_from_data = Qt6::QImage.from_data(encoded, "PNG")
    image_from_data.null?.should be_false
    image_from_data.pixel_color(1, 1).should eq(Qt6::Color.new(10, 20, 30, 255))
    image_from_data.pixel_color(2, 2).should eq(Qt6::Color.new(200, 150, 100, 255))
    image.save_to_data("PNG").size.should be > 0

    pixmap_from_data = Qt6::QPixmap.from_data(encoded, "PNG")
    pixmap_from_data.null?.should be_false
    pixmap_from_data.depth.should be > 0
    pixmap_from_data.has_alpha_channel?.should be_true
    pixmap_from_data.to_image.pixel_color(2, 2).should eq(Qt6::Color.new(200, 150, 100, 255))
    pixmap_from_data.scaled(8, 4, Qt6::AspectRatioMode::Ignore, Qt6::TransformationMode::Smooth).size.should eq(Qt6::Size.new(8, 4))
    pixmap_from_data.scaled_to_width(8).size.should eq(Qt6::Size.new(8, 8))
    pixmap_from_data.scaled_to_height(6).size.should eq(Qt6::Size.new(6, 6))
    pixmap_from_data.transformed(image_scale).size.should eq(Qt6::Size.new(8, 8))
    pixmap_from_data.save_to_data("PNG").size.should be > 0

    implicit_buffer = Qt6::QBuffer.new
    implicit_buffer.open(Qt6::IODeviceOpenMode::WriteOnly).should be_true
    image.save(implicit_buffer, "PNG").should be_true
    implicit_buffer.close
    implicit_buffer.data.bytes.size.should be > 0

    pdf_path = File.join(Dir.tempdir, "crystal-qt6-mm-layout-#{Process.pid}.pdf")
    pdf = Qt6::QPdfWriter.new(pdf_path, title: "MM Layout", creator: "crystal-qt6 specs")
    pdf.set_page_size_millimeters(50.0, 40.0, Qt6::PageOrientation::Portrait)
    pdf.resolution = 96
    layout = Qt6::PageLayout.new(
      Qt6::PageSize.new(50.0, 40.0, Qt6::PageSizeUnit::Millimeter),
      Qt6::PageOrientation::Portrait,
      Qt6::MarginsF.new(5.0, 2.5, 5.0, 2.5)
    )
    pdf.page_layout = layout

    full_rect = pdf.page_layout_full_rect_points
    paint_rect = pdf.page_layout_paint_rect_points

    full_rect.width.should be > paint_rect.width
    full_rect.height.should be > paint_rect.height
    paint_rect.x.should be > 0.0
    paint_rect.y.should be > 0.0

    Qt6::QPainter.paint(pdf) do |painter|
      painter.draw_line(Qt6::PointF.new(0.0, 0.0), Qt6::PointF.new(20.0, 20.0))
    end

    pdf_header = begin
      pdf.release
      File.open(pdf_path) do |file|
        bytes = Bytes.new(5)
        file.read_fully(bytes)
        String.new(bytes)
      end
    end

    File.exists?(pdf_path).should be_true
    pdf_header.should eq("%PDF-")
  end

  it "supports url and filesystem utility wrappers" do
    app

    root_path = File.join(Dir.tempdir, "crystal-qt6-utils-#{Process.pid}")
    nested_relative = "maps/exports"
    nested_path = File.join(root_path, "maps", "exports")
    maps_path = File.join(root_path, "maps")
    file_path = File.join(root_path, "terrain.map")

    Dir.mkdir_p(root_path)
    File.write(file_path, "terrain")

    url = Qt6::QUrl.from_local_file(file_path)
    web_url = Qt6::QUrl.new("https://example.com/maps/view?id=7")
    dir = Qt6::QDir.new(root_path)
    file_info = Qt6::QFileInfo.new(file_path)

    url.valid?.should be_true
    url.local_file?.should be_true
    url.scheme.should eq("file")
    url.to_local_file.should eq(file_path)
    url.to_string.should contain(file_path)

    web_url.valid?.should be_true
    web_url.local_file?.should be_false
    web_url.scheme.should eq("https")
    web_url.path.should eq("/maps/view")

    dir.exists?.should be_true
    dir.path.should eq(root_path)
    dir.file_path("terrain.map").should eq(file_path)
    dir.absolute_file_path("terrain.map").should eq(file_path)
    dir.mkpath(nested_relative).should be_true

    Qt6::QDir.clean_path("#{root_path}/maps/../maps/exports").should eq(nested_path)
    Qt6::QDir.current_path.should eq(Dir.current)
    Qt6::QDir.home_path.should_not be_empty

    file_info.exists?.should be_true
    file_info.file?.should be_true
    file_info.dir?.should be_false
    file_info.file_name.should eq("terrain.map")
    file_info.base_name.should eq("terrain")
    file_info.suffix.should eq("map")
    file_info.absolute_file_path.should eq(file_path)
    file_info.absolute_path.should eq(root_path)
    file_info.directory.absolute_path.should eq(root_path)
    file_info.size.should eq(7_i64)
  ensure
    File.delete?(file_path) if file_path
    Dir.delete?(nested_path) if nested_path
    Dir.delete?(maps_path) if maps_path
    Dir.delete?(root_path) if root_path
  end

  it "supports file-backed qt io helpers" do
    app

    file_path = File.join(Dir.tempdir, "crystal-qt6-qfile-#{Process.pid}.txt")
    file = Qt6::QFile.new(file_path)

    Qt6::QFile.exists?(file_path).should be_false
    file.exists?.should be_false
    file.file_name.should eq(file_path)

    file.open(Qt6::IODeviceOpenMode::WriteOnly).should be_true
    file.open?.should be_true
    file.write("terrain\n").should eq(8_i64)
    file.flush.should be_true
    file.size.should eq(8_i64)
    file.close

    Qt6::QFile.exists?(file_path).should be_true
    file.exists?.should be_true

    file.open(Qt6::IODeviceOpenMode::ReadOnly).should be_true
    file.read_all.bytes.should eq("terrain\n".to_slice)
    file.close
    file.open?.should be_false

    renamed_path = File.join(Dir.tempdir, "crystal-qt6-qfile-renamed-#{Process.pid}.txt")
    file.file_name = renamed_path
    file.file_name.should eq(renamed_path)
    file.exists?.should be_false

    renamed = Qt6::QFile.new(renamed_path)
    renamed.open(Qt6::IODeviceOpenMode::WriteOnly).should be_true
    renamed.write(Bytes[1_u8, 2_u8, 3_u8, 4_u8]).should eq(4_i64)
    renamed.close
    renamed.size.should eq(4_i64)
    renamed.remove.should be_true
    renamed.exists?.should be_false
  ensure
    File.delete?(file_path) if file_path
    File.delete?(renamed_path) if renamed_path
  end

  it "supports shared qiodevice-style helpers for buffers and files" do
    app

    backing = Qt6::QByteArray.new
    buffer = Qt6::QBuffer.new(backing)

    buffer.open(Qt6::IODeviceOpenMode::ReadWrite).should be_true
    buffer.open?.should be_true
    buffer.position.should eq(0_i64)
    buffer.at_end?.should be_true
    buffer.write("roads").should eq(5_i64)
    buffer.size.should eq(5_i64)
    buffer.position.should eq(5_i64)
    buffer.at_end?.should be_true
    buffer.seek(0).should be_true
    buffer.position.should eq(0_i64)
    buffer.bytes_available.should eq(5_i64)
    buffer.at_end?.should be_false
    buffer.read_all.bytes.should eq("roads".to_slice)
    buffer.at_end?.should be_true
    buffer.seek(2).should be_true
    buffer.write("X").should eq(1_i64)
    buffer.close
    buffer.data.bytes.should eq("roXds".to_slice)

    file_path = File.join(Dir.tempdir, "crystal-qt6-iodevice-#{Process.pid}.txt")
    file = Qt6::QFile.new(file_path)
    file.open(Qt6::IODeviceOpenMode::WriteOnly).should be_true
    file.write("terrain\nroads").should eq(13_i64)
    file.position.should eq(13_i64)
    file.size.should eq(13_i64)
    file.close

    file.open(Qt6::IODeviceOpenMode::ReadOnly).should be_true
    file.position.should eq(0_i64)
    file.bytes_available.should eq(13_i64)
    file.at_end?.should be_false
    file.seek(8).should be_true
    file.position.should eq(8_i64)
    file.read_all.bytes.should eq("roads".to_slice)
    file.at_end?.should be_true
    file.close
  ensure
    File.delete?(file_path) if file_path
  end

  it "supports persisted settings stores" do
    app

    settings_path = File.join(Dir.tempdir, "crystal-qt6-settings-#{Process.pid}.ini")
    File.delete?(settings_path)

    settings = Qt6::QSettings.new(settings_path)
    settings.file_name.should eq(settings_path)
    settings.contains?("window/title").should be_false
    settings.value("window/title").should be_nil
    settings.value("window/missing", "fallback").should eq("fallback")

    settings.set_value("window/title", "Map Tool").should eq("Map Tool")
    settings.set_value("window/width", 1280).should eq(1280)
    settings.set_value("window/opacity", 0.85).should eq(0.85)
    settings.set_value("window/pinned", true).should eq(true)
    settings.sync

    File.exists?(settings_path).should be_true

    reopened = Qt6::QSettings.new(settings_path)
    reopened.contains?("window/title").should be_true
    reopened.value("window/title").should eq("Map Tool")
    reopened.value("window/width").should eq(1280)
    reopened.value("window/opacity").should eq(0.85)
    reopened.value("window/pinned").should eq(true)
    reopened.all_keys.sort.should eq(["window/opacity", "window/pinned", "window/title", "window/width"])

    reopened.remove("window/title").sync
    reopened.contains?("window/title").should be_false

    reopened.clear.sync
    reopened.all_keys.should be_empty
  ensure
    File.delete?(settings_path) if settings_path
  end

  it "supports desktop integration helpers" do
    app

    temp_path = Qt6::StandardPaths.writable_location(Qt6::StandardLocation::TempLocation)
    home_path = Qt6::StandardPaths.writable_location(Qt6::StandardLocation::HomeLocation)
    home_locations = Qt6::StandardPaths.standard_locations(Qt6::StandardLocation::HomeLocation)
    app_config_locations = Qt6::StandardPaths.standard_locations(Qt6::StandardLocation::AppConfigLocation)

    temp_path.should_not be_empty
    home_path.should_not be_empty
    home_locations.should contain(home_path)
    app_config_locations.should_not be_empty
    Qt6::StandardPaths.display_name(Qt6::StandardLocation::DocumentsLocation).should_not be_empty

    Qt6::DesktopServices.open_url(Qt6::QUrl.new).should be_false
  end

  it "loads standalone SVG files and exposes element bounds" do
    app
    svg_path = File.join(Dir.tempdir, "crystal-qt6-standalone-#{Process.pid}.svg")
    File.write(svg_path, <<-SVG)
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="12" viewBox="0 0 20 12">
        <rect id="box" x="2" y="1" width="6" height="4" fill="#ff0000"/>
        <rect id="accent" x="12" y="2" width="4" height="6" fill="#0000ff"/>
      </svg>
    SVG

    renderer = Qt6::QSvgRenderer.new(svg_path)
    renderer.load(svg_path).should be_true
    canvas = Qt6::QImage.new(20, 12)
    canvas.fill(Qt6::Color.new(255, 255, 255))
    element_canvas = Qt6::QImage.new(20, 12)
    element_canvas.fill(Qt6::Color.new(255, 255, 255))
    bounded_element_canvas = Qt6::QImage.new(10, 10)
    bounded_element_canvas.fill(Qt6::Color.new(255, 255, 255))

    Qt6::QPainter.paint(canvas) do |painter|
      renderer.render(painter)
    end

    Qt6::QPainter.paint(element_canvas) do |painter|
      renderer.render(painter, "box")
    end

    Qt6::QPainter.paint(bounded_element_canvas) do |painter|
      renderer.render(painter, "accent", Qt6::RectF.new(0.0, 0.0, 10.0, 10.0))
    end

    renderer.valid?.should be_true
    renderer.default_size.should eq(Qt6::Size.new(20, 12))
    renderer.view_box.should eq(Qt6::RectF.new(0.0, 0.0, 20.0, 12.0))
    renderer.element_exists?("box").should be_true
    renderer.element_exists?("accent").should be_true
    renderer.element_exists?("missing").should be_false
    renderer.bounds_on_element("box").should eq(Qt6::RectF.new(2.0, 1.0, 6.0, 4.0))
    renderer.bounds_on_element("accent").should eq(Qt6::RectF.new(12.0, 2.0, 4.0, 6.0))
    canvas.pixel_color(3, 2).should eq(Qt6::Color.new(255, 0, 0, 255))
    canvas.pixel_color(13, 3).should eq(Qt6::Color.new(0, 0, 255, 255))
    element_canvas.pixel_color(3, 2).should eq(Qt6::Color.new(255, 0, 0, 255))
    bounded_element_canvas.pixel_color(1, 1).should eq(Qt6::Color.new(0, 0, 255, 255))
  end

  it "supports clipboard access and file-backed image loading helpers" do
    application = app
    source_path = File.join(Dir.tempdir, "crystal-qt6-image-source-#{Process.pid}.png")
    source = Qt6::QImage.new(12, 10)
    source.fill(Qt6::Color.new(255, 255, 255))
    source.set_pixel_color(4, 3, Qt6::Color.new(12, 34, 56, 255))
    source.save(source_path).should be_true

    loaded_image = Qt6::QImage.from_file(source_path)
    loaded_image.null?.should be_false
    loaded_image.size.should eq(Qt6::Size.new(12, 10))
    loaded_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    reusable_image = Qt6::QImage.new(1, 1)
    reusable_image.load(source_path).should be_true
    reusable_image.size.should eq(Qt6::Size.new(12, 10))
    reusable_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    loaded_pixmap = Qt6::QPixmap.from_file(source_path)
    loaded_pixmap.null?.should be_false
    loaded_pixmap.size.should eq(Qt6::Size.new(12, 10))
    loaded_pixmap.to_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    reusable_pixmap = Qt6::QPixmap.new(1, 1)
    reusable_pixmap.load(source_path).should be_true
    reusable_pixmap.size.should eq(Qt6::Size.new(12, 10))
    reusable_pixmap.to_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    reader = Qt6::QImageReader.new(source_path)
    reader.file_name.should eq(source_path)
    reader.can_read?.should be_true
    reader.size.should eq(Qt6::Size.new(12, 10))
    reader.format.should eq("png")
    reader.auto_transform?.should be_false
    reader.auto_transform = true
    reader.auto_transform?.should be_true
    reader.format = "png"
    reader.format.should eq("png")

    reader_image = reader.read
    reader_image.null?.should be_false
    reader_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    second_reader = Qt6::QImageReader.new(source_path)
    reused_reader_image = Qt6::QImage.new(1, 1)
    second_reader.read(reused_reader_image).should be_true
    reused_reader_image.size.should eq(Qt6::Size.new(12, 10))
    reused_reader_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    encoded_png = source.save_to_data("PNG")
    buffer = Qt6::QBuffer.new
    buffer.open(Qt6::IODeviceOpenMode::ReadWrite).should be_true
    source.save(buffer, "PNG").should be_true
    buffer.position.should be > 0
    buffer.seek(0).should be_true
    buffer.peek(8).bytes.should eq(encoded_png[0, 8])
    buffer.read(8).bytes.should eq(encoded_png[0, 8])

    device_loaded_image = Qt6::QImage.new(1, 1)
    buffer.seek(0).should be_true
    device_loaded_image.load(buffer, "PNG").should be_true
    device_loaded_image.size.should eq(Qt6::Size.new(12, 10))
    device_loaded_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    buffer.seek(0).should be_true
    device_reader = Qt6::QImageReader.new(buffer, "png")
    device_reader.can_read?.should be_true
    device_reader.size.should eq(Qt6::Size.new(12, 10))
    device_reader.read.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    writable_formats = Qt6::QImageWriter.supported_image_formats.map(&.downcase)
    writable_mime_types = Qt6::QImageWriter.supported_mime_types
    writable_formats.includes?("png").should be_true
    writable_mime_types.includes?("image/png").should be_true

    writer_path = File.join(Dir.tempdir, "crystal-qt6-image-writer-#{Process.pid}.png")
    writer = Qt6::QImageWriter.new(writer_path, "png")
    writer.file_name.should eq(writer_path)
    writer.format.should eq("png")
    writer.quality = 90
    writer.quality.should eq(90)
    writer.compression = 1
    writer.compression.should eq(1)
    writer.optimized_write = true
    writer.optimized_write?.should be_true
    writer.progressive_scan_write = true
    writer.progressive_scan_write?.should be_true
    writer.can_write?.should be_true
    writer.write(source).should be_true

    writer_loaded_image = Qt6::QImageReader.new(writer_path).read
    writer_loaded_image.size.should eq(Qt6::Size.new(12, 10))
    writer_loaded_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    writer_buffer_bytes = Qt6::QByteArray.new
    writer_buffer = Qt6::QBuffer.new(writer_buffer_bytes)
    writer_buffer.open(Qt6::IODeviceOpenMode::WriteOnly).should be_true
    device_writer = Qt6::QImageWriter.new(writer_buffer, "png")
    device_writer.format.should eq("png")
    device_writer.can_write?.should be_true
    device_writer.write(source).should be_true
    writer_buffer.close
    writer_buffer_bytes.bytes.size.should be > 0

    device_writer_image = Qt6::QImage.from_data(writer_buffer_bytes.bytes, "PNG")
    device_writer_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    clipboard = application.clipboard
    clipboard.clear
    clipboard.text = "clipboard sample"
    application.process_events
    clipboard.has_text?.should be_true
    clipboard.text.should eq("clipboard sample")

    clipboard.image = loaded_image
    application.process_events
    clipboard.has_image?.should be_true
    clipboard_image = clipboard.image
    clipboard_image.null?.should be_false
    clipboard_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    clipboard.pixmap = loaded_pixmap
    application.process_events
    clipboard.has_pixmap?.should be_true
    clipboard_pixmap = clipboard.pixmap
    clipboard_pixmap.null?.should be_false
    clipboard_pixmap.to_image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))

    mime_data = Qt6::MimeData.new
    mime_data.text = "mime sample"
    mime_data.html = "<b>mime sample</b>"
    mime_data.image = loaded_image
    mime_data.set_data("application/x-crystal-qt6-layer", Bytes[1_u8, 7_u8, 9_u8])
    mime_data.has_html?.should be_true
    mime_data.has_image?.should be_true
    mime_data.image.pixel_color(4, 3).should eq(Qt6::Color.new(12, 34, 56, 255))
    mime_data.formats.should contain("application/x-crystal-qt6-layer")
    clipboard.mime_data = mime_data
    application.process_events

    clipboard_mime = clipboard.mime_data
    clipboard_mime.should_not be_nil
    clipboard_mime = clipboard_mime.not_nil!
    clipboard_mime.has_text?.should be_true
    clipboard_mime.text.should eq("mime sample")
    clipboard_mime.has_html?.should be_true
    clipboard_mime.html.should contain("mime sample")
    clipboard_mime.formats.should contain("application/x-crystal-qt6-layer")
    clipboard_mime.has_format?("application/x-crystal-qt6-layer").should be_true
    clipboard_mime.data("application/x-crystal-qt6-layer").should eq(Bytes[1_u8, 7_u8, 9_u8])
    clipboard.clear
  end

  it "loads SVG content from memory" do
    app
    svg_markup = <<-SVG
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="10" viewBox="0 0 18 10">
        <rect id="memory-box" x="4" y="2" width="6" height="4" fill="#00aa00"/>
      </svg>
    SVG

    renderer = Qt6::QSvgRenderer.from_data(svg_markup)
    renderer.valid?.should be_true
    renderer.default_size.should eq(Qt6::Size.new(18, 10))
    renderer.element_exists?("memory-box").should be_true

    image = Qt6::QImage.new(18, 10)
    image.fill(Qt6::Color.new(255, 255, 255))

    Qt6::QPainter.paint(image) do |painter|
      renderer.render(painter)
    end

    image.pixel_color(5, 3).should eq(Qt6::Color.new(0, 170, 0, 255))

    widget = Qt6::QSvgWidget.from_data(svg_markup)
    widget.size_hint.should eq(Qt6::Size.new(18, 10))
    widget.resize(18, 10)
    widget.show
    app.process_events

    preview = widget.grab
    preview.null?.should be_false
    preview.width.should be >= 18
    preview.height.should be >= 10
    widget.release
  end

  it "displays SVG content in QSvgWidget" do
    application = app
    svg_path = File.join(Dir.tempdir, "crystal-qt6-widget-#{Process.pid}.svg")
    File.write(svg_path, <<-SVG)
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="16" viewBox="0 0 24 16">
        <rect x="3" y="2" width="8" height="6" fill="#ff0000"/>
      </svg>
    SVG

    widget = Qt6::QSvgWidget.new(svg_path)
    renderer = widget.renderer

    renderer.valid?.should be_true
    renderer.default_size.should eq(Qt6::Size.new(24, 16))
    renderer.element_exists?("missing").should be_false
    widget.size_hint.should eq(Qt6::Size.new(24, 16))
    widget.resize(24, 16)
    widget.visible?.should be_false
    widget.show
    application.process_events
    widget.update
    application.process_events

    preview = widget.grab

    widget.visible?.should be_true
    widget.size.should eq(Qt6::Size.new(24, 16))
    preview.null?.should be_false
    preview.width.should be >= 24
    preview.height.should be >= 16

    render_probe = Qt6::QImage.new(24, 16)
    render_probe.fill(Qt6::Color.new(255, 255, 255))
    Qt6::QPainter.paint(render_probe) do |painter|
      renderer.render(painter)
    end
    render_probe.pixel_color(4, 3).should eq(Qt6::Color.new(255, 0, 0, 255))

    widget.release
  end
end
